### ISSUE TITLE
“Continue to upgrade” generates two erros before upgrade confirmation

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#5414] opened 2020-05-22 10:20 UTC
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.172.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Steps to reproduce
1. Go to  https://123done-stage.dev.lcip.org/ page and make a subscription.
2. Load this page https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/products/prod_GVNS86uMUO3VRM using the same browser session.
3. Check  the “authorization” box. 
4. Click the “Confirm upgrade” blue button.

#### Expected result:
- The subscription upgrade to the new plan is made with succes user is redirected to the confirmation page.

#### Actual result:
- The message ”Plan update failed. An internal error occurred” is displayed. 
- Dismiss the message and repeat STR 4 => “Plan update failed. Subscription was already cancelled.”

#### Notes:
- Refreshing the page after dismissing the second message, will redirect the user to the upgrade confirmation page.
![subscrupdate](https://user-images.githubusercontent.com/15685960/82657977-eb664c00-9c2e-11ea-86ea-4f5f028c9663.gif)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1954)
┆Issue Number: FXA-1954

**Comment by data-sync-user** [comment] 2020-05-27 14:39
➤ Chelsea Lewis commented:

Added to current sprint and assigned to [~lorchard@mozilla.com] as he has a PR in waiting for review to resolve.

**Comment by madalincm** [comment] 2020-06-02 15:00
Verified this in stage, using Fx77 and Windows 10 (64-bit).
The issue is still reproducing:
![image](https://user-images.githubusercontent.com/15685441/83535640-df19a300-a4fa-11ea-905b-7e7634b212df.png)
Reopening the issue.

**Comment by data-sync-user** [comment] 2020-06-02 17:35
➤ Les Orchard commented:

I can reproduce. However, it looks like auth-server in staging hasn't been updated to v1.173.0 where this fix was landed:

➜  ~ date && curl https://api-accounts.stage.mozaws.net/__version__
Tue Jun  2 10:24:10 PDT 2020
{
  "version": "1.172.0",
  "commit": "3a6a83ac76b01f1d4d3f8ae92a4098b11e6a0bd8",
  "source": "https://github.com/mozilla/fxa"
}

**Closed** 2020-06-02 17:48 UTC
Labels: severity:normal, status:bug

**Comment by ValentinaPC** [comment] 2020-06-03 06:04
Verified as fixed in stage, using Fx76 and Windows 10 (64-bit).
Postfix video below.
![confirmupgrade](https://user-images.githubusercontent.com/15685960/83601442-46763800-a579-11ea-90e4-c98a8be0b898.gif)
