### ISSUE TITLE
Create account/Sign in flow pages are not correctly translated on RTL builds

### ISSUE THREAD

**Issue by AlinOIlea** [mozilla/fxa#2605] opened 2019-09-25 13:11 UTC
Environment:
Windows, stage server

Steps:

   1. Go to about:welcome page.
   2. Enter a known valid email address and follow the flow to sign-in.

Expected result:
The text is translated into the RTL language and is displayed correct on all pages.

Actual result:
Some text is translated, some text is not translated. Question marks and dots are displayed at the beginning of the sentence also. (See attachments).

![Screenshot_2019-09-24 You did it You’re signed in ar](https://user-images.githubusercontent.com/55795743/65603828-0bb20e00-dfaf-11e9-949f-b30f1768dcb4.png)

![Screenshot_2019-09-24 Check your texts arr](https://user-images.githubusercontent.com/55795743/65603837-110f5880-dfaf-11e9-879a-23f6f582f59c.png)

**Comment by SorinaFlorean** [comment] 2019-09-25 13:25
Reproducible also on the tablet - Samsung Galaxy Tab S3 (Android 8.0). 
![Screenshot_20190925-162404_Firefox Beta](https://user-images.githubusercontent.com/24588037/65605054-1c638380-dfb1-11e9-9ac5-eaaf0ee84315.jpg)

**Comment by davismtl** [comment] 2019-09-25 18:36
This is L10N and we don't control how quickly they localize and if they have contributors available.

Strings were submitted to them within our standard delays. 

Some of these strings have been available for localization for a few months too.

@ryanfeeley you did a great job at getting contributors to prioritize quickly recently. Do you think you can ask for some help again?

@SorinaFlorean is that Arabic or Persian?

**Comment by clouserw** [comment] 2019-10-04 15:56
This is the same root cause as  Bug 1585420 - the strings aren't translated.  The L10n team said they would mail the localizers but to leave the pages partially translated (vs disabling them) so I will wontfix this bug.  Thanks.

**Closed by clouserw** 2019-10-04 15:56 UTC
