### ISSUE TITLE
problem tracking monitor signin metrics

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/fxa#2009] opened 2019-07-30 18:22 UTC
The number of unique user IDs that are checking/creating authentication tokens with monitor is many times the users that are generating login and registration events, which really should not happen:

https://analytics.amplitude.com/mozilla-corp/chart/rf0ojfa

It appears that we are not tracking `fxa_login - complete` events for monitor in many cases. I believe this may be primarily due to how the monitor login flow on the /[whatsnew](https://www.mozilla.org/en-US/firefox/68.0/whatsnew/) page was implemented. see [this user](https://analytics.amplitude.com/mozilla-corp/project/178231/search/amplitude_id%3D32337161840) for a typical example of the events that fire when a user goes through this flow:

<img width="524" alt="image" src="https://user-images.githubusercontent.com/5625313/62154133-5e2ec100-b2c3-11e9-8686-eb37798735cc.png">

Thus for users signing in to monitor through the whatsnew page we are only getting `view` and `submit` events, followed by the auth token events.

From a metrics perspective since the users are generating auth token events that are associated with monitor we can still infer how many users are signing in, but when we count login and registration complete events (which we often do), we are under counting substantially. And since we are not triggering all the events in the funnel, we cannot analyze it in detail for drop-offs. Also, it makes it harder to know the number of users that are signing into monitor with an existing account vs the number making a new account. 

cc @davismtl @sandysage

**Comment by philbooth** [comment] 2019-07-30 19:31
We return a `deviceId` property in the response from `GET /metrics-flow`. The `/whatsnew` page just needs to propagate that as `device_id` in the query params when it redirects to FxA, then this will all work correctly. Just checked now and I don't see any `device_id`.

**Comment by irrationalagent** [comment] 2019-07-31 17:26
Yes, we should fix that, but (and I'm genuinely unsure) does that explain why we are not tracking the login complete event specifically? I had a hunch that it had to do with the weird force-auth/one-click signin flow. would we still expect login complete to fire here?
![out](https://user-images.githubusercontent.com/5625313/62233581-b629fe00-b37d-11e9-9c10-4283fb30384b.gif)

**Comment by philbooth** [comment] 2019-07-31 17:37
> does that explain why we are not tracking the login complete event specifically?

By "not tracking" do you mean not assigning it into the appropriate user's flow, or do you mean not sending that event to Amplitude at all? It explains the former, but not the latter.

**Comment by irrationalagent** [comment] 2019-07-31 17:43
Yea, I think the latter is occurring. If you look at https://analytics.amplitude.com/mozilla-corp/chart/rf0ojfa there do not seem to be login/reg events associated with monitor occurring at a scale that would be consistent with the number of user_ids that are checking tokens with that service.

**Comment by philbooth** [comment] 2019-07-31 18:10
> I think the latter is occurring.

If these missing events were both not assigned to the correct user and also, not associated with the correct service/client id, could that explain the symptoms you're seeing?

My problem looking at the code is I can't see a way for events not to be emitted at all, at least not in a way that's specific to a particular service. We just blanket emit the events from the auth server, the only things that are conditional are the event properties and user properties.

**Comment by irrationalagent** [comment] 2019-07-31 18:15
If they were not assigned to the same user I would assume they would be assigned to A user, in which case the overall counts should still be higher. 

it could be that they are being assigned to the wrong client_id though. ill look into that.

**Comment by shane-tomlinson** [comment] 2019-08-01 07:46
> Yes, we should fix that, but (and I'm genuinely unsure) does that explain why we are not tracking the login complete event specifically? I had a hunch that it had to do with the weird force-auth/one-click signin flow. would we still expect login complete to fire here?

Ref - https://github.com/mozilla/fxa/issues/1050 where a similar problem also manifests sending notifications to basket.

cached signins don't trigger a `login - complete` message because no login to FxA actually occurs. An authorization occurs, but no login.

**Comment by philbooth** [comment] 2019-08-01 07:58
> cached signins don't trigger a `login - complete` message because no login to FxA actually occurs. An authorization occurs, but no login.

Ahhh, sorry @irrationalagent. Reading @shane-tomlinson's comment forced me to go back and read yours properly and it turns out I wasn't really paying attention last night. That situation in your gif, no, we do not expect it to generate the signin success/complete events. Ignore the other stuff I said.

**Comment by philbooth** [comment] 2019-08-01 08:01
(we should be able to do something to make it work though, having a look at it now)

**Comment by shane-tomlinson** [comment] 2019-08-01 08:01
A bit more context - for cached signins, the backend isn't hit to log an `fxa_login - complete`. All we do is generate OAuth creds using the existing sessionToken. 

If `fxa_login - complete` is needed, then the problem is going to become *worse* once we fix #1371 and ask for a password in fewer places by using cached credentials as often as possible.

We could try to issue an `fxa_login - complete` whenever we call [sessionReauth](https://github.com/mozilla/fxa/blob/48685eac6008cefa8259a1ce95689b852484cc7d/packages/fxa-content-server/app/scripts/models/account.js#L578) - which calls [/session/reauth](https://github.com/mozilla/fxa/blob/48685eac6008cefa8259a1ce95689b852484cc7d/packages/fxa-auth-server/lib/routes/session.js#L82) on the auth server. Perhaps instead of just passing in a `verificationMethod`, we could pass in a new `verificationReason` and if that reason is something like `authorization` or `re-auth` and the session is valid, the log a `fxa_login - complete`?

**Comment by rfk** [comment] 2019-08-01 09:02
Another option could be to issue `fxa_login - complete` *later* in the flow, at the point where the OAuth code is redeemed for a token (which signals the completion of the flow from the relier's perspective, rather than FxA's perspective).

**Comment by shane-tomlinson** [comment] 2019-08-01 09:17
> Another option could be to issue fxa_login - complete later in the flow, at the point where the OAuth code is redeemed for a token (which signals the completion of the flow from the relier's perspective, rather than FxA's perspective).

This is a good option I hadn't considered. I think we'd have to propagate OS/browser info, possibly requiring stashing info in redis.

We'd also want to handle implicit grants.

**Comment by irrationalagent** [comment] 2019-08-02 15:31
@rfk's idea seems like a good one from my perspective, since it will be closer to the client's definition of "done". @davismtl can override me, but I think we definitely want to count these "login to another service with cached credentials" situations as a login.

we may also want to consider adding a "service_added" event or similar to catch the _first_ cases of a user adding a secondary service. ill file a separate bug for that.

Related to this I think

**Comment by davismtl** [comment] 2019-08-02 18:05
>  I think we definitely want to count these "login to another service with cached credentials" situations as a login.

Yes! 
@irrationalagent Perhaps we add a property to distinguish the two types of logins. (?)

**Closed** 2019-09-16 16:52 UTC
