### ISSUE TITLE
Account deletion fails, but Stripe customer and subscription deletion are successful (production)

### ISSUE THREAD

**Issue by stlhood** [mozilla/fxa#3119] opened 2019-10-24 05:45 UTC
## Description

When trying to delete an FxA account in *production*, FxA reports an error and the account is not deleted. However, the associated Stripe customer and subscription(s) *are* deleted.

### Steps to reproduce

- Log into a production FxA account that has an active subscription.
- Delete the FxA account.

### Expected result

The FxA account should be deleted and a confirmation displayed. The associated Stripe customer and subscription(s) should also be deleted.

### Actual result

The FxA account is not deleted. Instead, an error is shown: "System unavailable, try again soon." Screenshot:

![image](https://user-images.githubusercontent.com/42821/67456520-e59b8000-f5e5-11e9-8590-79ca12330599.png)

The browser console shows an HTTP 500 on https://api.accounts.firefox.com/v1/account/destroy.

### Environment

Example users to look at:
- slangtonhood+vpn4@mozilla.com (deletion attempt at around 10PM PT on 10/23
- slangtonhood+vpn1@mozilla.com (deletion attempt at around 10:38PM PT on 10/23

**Comment by shane-tomlinson** [comment] 2019-10-24 12:49
I just signed up and deleted an account, without having any subscriptions, and no problem. So perhaps the failure has something to do with having a subscription.

cc @bbangert and @lmorchard

**Comment by johngruen** [comment] 2019-10-24 18:48
I can reproduce this on prod with a subscription

**Comment by johngruen** [comment] 2019-10-24 18:49
In the browser console:
```
System unavailable, try again soon raven.js:51
    t raven.js:51
    error logger.js:69
    captureError error-utils.js:63
    logError base.js:769
    o base.js:80
    Underscore 2
    _submitForm form.js:240
    _submitForm form.js:230
    invokeHandler base.js:1054
    default progress_indicator.js:42
    default progress_indicator.js:42
    invokeHandler base.js:1054
    default sign_in_password.js:72
    default sign_in_password.js:71
    validateAndSubmit form.js:213
    validateAndSubmit form.js:193
    invokeHandler base.js:1054
    default allow_only_one_submit.js:24
    default allow_only_one_submit.js:24
    onFormSubmit form.js:148
    invokeHandler base.js:1054
    default prevent_default_then.js:19
    jQuery 2
    r raven.js:360
    t raven.js:991
    jQuery 6
    Backbone 2
    _attachEvents form.js:252
    afterRender form.js:89
    a/n.mixin/</i[n]/< Backbone
    Underscore 2
    n Backbone
    render base.js:295
    render base.js:288
    render base.js:267
    openPanel recovery_codes.js:70
    openPanel recovery_codes.js:65
    a/n.mixin/</i[n]/< Backbone
    Underscore 2
    n Backbone
    showChildView security_events.js:13
    showChildView security-events.js:15
    showChildView settings.js:109
    showChildView authorization.js:15
```

**Comment by johngruen** [comment] 2019-10-24 18:52
I also got a 400 and a 500 while doing this...one of these might be a red herring b/c i fat-fingered my password before submitting it

**Comment by johngruen** [comment] 2019-10-24 18:53
Note...After the error got returned, I was able to delete my account on the second hit of the delete button.

**Comment by lmorchard** [comment] 2019-10-24 20:50
I think this is an error coming from subhub. I got subhub running locally against my personal stripe account, pointed my local fxa stack at it. Created a user, subscribed to a product, then deleted the account. This is the error I saw in the subhub console:

```
sub         |   File "/subhub/sub/payments.py", line 245, in delete_customer
sub         |     deleted_customer=deleted_customer.user_id,
sub         | AttributeError: 'bool' object has no attribute 'user_id'
```

Looks like [a `logger.debug()` statement](https://github.com/mozilla/subhub/blob/master/src/sub/payments.py#L245) is trying to output `deleted_customer.user_id`. However, [`deleted_customer` is the result](https://github.com/mozilla/subhub/blob/master/src/sub/payments.py#L235) of a [`delete_user()` call](https://github.com/mozilla/subhub/blob/master/src/sub/payments.py#L251), which [returns a bool](https://github.com/mozilla/subhub/blob/master/src/sub/payments.py#L256).

**Comment by bbangert** [comment] 2019-10-25 15:17
Marty has pushed a fix for this to production that should resolve this. Please re-open if reproduced again.

**Closed by bbangert** 2019-10-25 15:17 UTC
Labels: [QA]:Blocker issue
