### ISSUE TITLE
Needs Verification: Focused input still needs a click when tabbing through subscription fields

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa#3089] opened 2019-10-23 11:18 UTC
From @rbillings 

> I really hate that when signing up for a subscription using tab will move the outline of the box to the next field - but the focus isn't moved and you are unable to type until you actually click in the next field. Repros on Chrome & Safari.

@rbillings I am unable to reproduce this issue. Tabbing works fine for me and i do not need to click into the fields. Can you provide more detail here and we can ask Softvision to verify?

**Comment by rbillings** [comment] 2019-10-23 16:05
In the form I type in the name field, click tab, the focus moves to the card # field but when I type nothing happens until I click into the field- then I can add numbers. Doing more testing, I was able to get the focus to move with tabs after I got an error [ex: entering a letter into the CVC field]. This still repros on both Chrome and Safari. I was not able to repro this on Firefox.

**Comment by johngruen** [comment] 2019-10-28 16:09
@bsurd can you repro this? I cannot

**Comment by LZoog** [comment] 2019-11-25 15:24
@rbillings Can we double check that this is still an issue in Chrome? I cannot reproduce. #3303 was closed as the Stripe team said there are known issues on their end for focusing form fields in Safari, but I am not experiencing this in Chrome.

**Comment by rbillings** [comment] 2019-11-25 18:29
I'm happy to say I can no longer repro this in Chrome.

**Closed** 2019-12-04 20:40 UTC
