### ISSUE TITLE
connected services do not appear on delete account section

### ISSUE THREAD

**Issue by janiceahn** [mozilla/fxa#1989] opened 2019-07-29 18:36 UTC
@LZoog the connected products/services do not seem to be appearing on my delete account section. i only have the nightly browser connected but it should appear as Firefox browser:

![image](https://user-images.githubusercontent.com/6219141/62073088-fe2a1300-b20d-11e9-82e1-14f6c02980c9.png)
![image](https://user-images.githubusercontent.com/6219141/62073110-097d3e80-b20e-11e9-8249-e9929232deb5.png)

**Comment by lmorchard** [comment] 2019-07-29 18:40
Probably also a dupe of #1984 - we're working through an issue in this section right now

**Closed** 2019-07-29 18:54 UTC
