### ISSUE TITLE
Remove support for the fxaccounts:verified WebChannel message

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#3554] opened 2019-12-03 10:31 UTC
The `fxaccounts:verified` WebChannel message is from a time before Push notifications immediately notified the browser when the user verified their account, it was a way of having the browser update its state quickly instead of waiting for the next poll.

Now that Push messages are enabled everywhere, the `fxaccounts:verified` message isn't even listened for, see https://searchfox.org/mozilla-central/search?q=fxaccounts%3Averified&path=

No real reason for us to send this.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-65)
┆Issue Number: FXA-65

**Comment by raghav4** [comment] 2020-02-17 04:46
@clouserw @johngruen @dannycoates @shane-tomlinson  do we have to simply remove it from the `COMMANDS`? If so shall I do it?

**Comment by LZoog** [comment] 2021-03-29 16:16
@raghav4 if you're still interested in working on this, that does seem to be part of the issue but if you search the codebase for `VERIFIED` (case-sensitive) you'll find other references to this that will need to be removed too. Thanks!

**Comment by Tosin-Bakare** [comment] 2021-03-31 15:25
Hello @LZoog can I work on this?

**Comment by LZoog** [comment] 2021-03-31 16:03
@Tosin-Bakare Since there hasn't been other interest in this in more than a year, sure thing, I will assign you! Thanks! :)

**Comment by Tosin-Bakare** [comment] 2021-04-01 10:26
Hello @LZoog @jodyheavener I am an Outreachy applicant and I have not been able to access both firefox & Mozilla chatrooms. Please I'll like to know if there is any other way to go about it. Below is one of the links "https://chat.mozilla.org/#/room/#fxa:mozilla.org"   Thank you.

**Comment by jodyheavener** [comment] 2021-04-01 13:41
Hey @Tosin-Bakare, sorry to hear you're running into difficulties. If you haven't already I recommend checking out our [Wiki page for Matrix](https://wiki.mozilla.org/Matrix#Getting_Started). Can you describe the problem you're facing - can you not access any of the chatrooms, or just those specific ones?

**Comment by Tosin-Bakare** [comment] 2021-04-01 16:35
Thank you @jodyheavener , After checking out the links I realized I cannot access any of the chatrooms.  Is there any other way to go about it?

**Comment by Tosin-Bakare** [comment] 2021-04-16 16:07
Dear @LZoog, the link to solving the above issue keeps leading to a page that states "No results for current query". Does this mean the issue is no longer available? 

https://searchfox.org/mozilla-central/search?q=fxaccounts%3Averified&path=

**Comment by jodyheavener** [comment] 2021-05-10 19:11
I'm not super familiar with this issue but I think we'd like to remove the command from our codebase, since it's not longer used (e.g. [here](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/app/scripts/lib/channels/web.js#L44:L44), but I'm not entirely sure, I don't see where it's being sent). @mozilla/fxa-devs is that correct?

**Comment by LZoog** [comment] 2021-05-17 15:10
Hey @Tosin-Bakare, we'll go ahead and unassign you from this issue. If you're still interested in working on it please let us know and we'll reassign you and try to get more context on how to close it out, thanks!

**Comment by Tosin-Bakare** [comment] 2021-05-17 15:20
Hello @LZoog , I’ll like to be reassigned to it, and yes let’s get more context on how to close it. 

Thank you.

**Closed** 2021-06-18 19:07 UTC
Labels: Orphaned, code_quality, good first issue
