### ISSUE TITLE
[FxA-Settings] Unclear error submitting a used email address as a secondary

### ISSUE THREAD

**Issue by rbillings** [mozilla/fxa#7479] opened 2021-02-09 19:55 UTC
## Description

Ugly error when trying to add a secondary email address that is already linked to a different account.
Submitted by: pdehaan

### Steps to reproduce

- Manage account
- Secondary email: add one that is already linked to a different account

### Expected result

An error that is more succinct

### Actual result

Unexpected error value: { code: 400, errno: 140, error: "Bad Request", message: "Email already exists", info: "https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/docs/api.md#response-format", reported: true }

<img width="332" alt="Screen Shot 2021-02-09 at 11 53 52 AM" src="https://user-images.githubusercontent.com/737878/107420232-865cca00-6acd-11eb-9f8e-cb10b19849a6.png">

### Environment

macOS / Chrome

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3017)
┆Issue Number: FXA-3017

**Comment by rbillings** [comment] 2021-02-09 19:57
From the bug report: Same when adding secondary email address that is your primary email address:

Unexpected error value: { code: 400, errno: 139, error: "Bad Request", message: "Can not add secondary email that is same as your primary", info: "https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/docs/api.md#response-format", reported: true }

I can also get a 422 when setting my secondary email address to 4@0.4 (which passes validation, because it’s definitely email-adjacent):

Unexpected error value: { code: 422, errno: 151, error: "Unprocessable Entity", message: "Failed to send email", info: "https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/docs/api.md#response-format", reported: true }

**Comment by rbillings** [comment] 2021-02-09 19:57
Lauren Z: I’ve seen this come up in more than what was found here (so far). If we don’t already have an issue filed for this, the solve should probably include checking how we’re handling/displaying all failed queries/mutations and establish (or reestablish) a pattern.

**Comment by vasilicatamas** [comment] 2021-02-10 15:14
@rbillings I think this issue is a dupe of [7018](https://github.com/mozilla/fxa/issues/7018)

**Comment by data-sync-user** [comment] 2021-02-11 18:46
➤ Chelsea Lewis commented:

[~vtamas@mozilla.com] can you confirm if this is resolved? we believe it was fixed in late dec/early jan

**Comment by vasilicatamas** [comment] 2021-02-12 14:19
The validation error is no longer accompanied by the "Unexpected error value: { code: 400, errno: 139, error: ...." part, which means that we can closed this bug as invalid and leave open the 7018 because the "Email already exists" error is too vague and it's not the same comparing it to the one displayed in the old Settings page "This email was already verified by another user".

![Screenshot_37](https://user-images.githubusercontent.com/18114210/107778914-53286e00-6d4d-11eb-887f-8a7595ac6ab0.png)

**Closed by vasilicatamas** 2021-02-12 14:19 UTC
