### ISSUE TITLE
Replace Recovery code link is unresponsive after Password reset

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/fxa#4753] opened 2020-04-03 14:55 UTC
**Affected platforms:**
Windows Pro 10 64-bit
Android 8.0.0

**Firefox version:**
74.0 (202003090951590) Production and stage
Firefox Preview on Nightly 200402 (Build #2015732243)

**Preconditions:**
Create an account and enable Two-step authentication. 

**Steps to reproduce:**
1.In Manage account page navigate to Password field and click to change it. 
2. Add valid old and new password and click on the Change button. 
3. After password is updated go to Two-step authentication and click on Change button. 
4. Click on the "replace recovery codes" link. 

**Expected result:** 
Recovery code modal with new codes show pop up. 

**Actual Results:**
Replace Recovery code link is unresponsive. 

![Replace Recovery code link is unresponsive after changing the account password](https://user-images.githubusercontent.com/53306802/78373988-f9ef9a00-75d3-11ea-9e53-f088107b91df.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1489)
┆Issue Number: FXA-1489

**Comment by imskr** [comment] 2020-04-04 01:06
Can I work on this @mirunacurtean

**Comment by mirunacurtean** [comment] 2020-04-06 08:02
Looks like it could be a variation on https://github.com/mozilla/fxa/issues/4257.

**Comment by data-sync-user** [comment] 2020-04-07 20:23
➤ Wil Clouser commented:

Are you able to attach any errors you see in the console?  This seems like a JS error just from looking at the report.  Thank you

**Comment by mirunacurtean** [comment] 2020-04-08 08:15
Yes. 
![Replace ecovery code link console error](https://user-images.githubusercontent.com/53306802/78760671-2d427800-798a-11ea-9bbf-74939c2a4d9e.PNG)
[console-export-2020-4-8_11-14-8.txt](https://github.com/mozilla/fxa/files/4449131/console-export-2020-4-8_11-14-8.txt)

**Comment by data-sync-user** [comment] 2021-01-20 21:04
➤ Barry Chen commented:

Marking this as a duplicate of FXA-1193 since the cause of the bug is the same.

**Comment by data-sync-user** [comment] 2021-01-20 21:06
➤ Barry Chen commented:

Will fix in FXA-1193

**Closed** 2021-01-20 21:06 UTC

**Comment by vasilicatamas** [comment] 2021-02-01 15:24
This issue is verified as fixed on FxA [Train 1.199.0] under Windows 10 64-bit and Android 9. "Replace Recovery codes" modal is successfully displayed after changing the account password,

![issue77](https://user-images.githubusercontent.com/18114210/106478624-0d98b500-64b2-11eb-8d04-d09978d41e63.gif)
