### ISSUE TITLE
Define UTM Parameters

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#205] opened 2016-11-15 19:54 UTC
To investigate:
- Which ones are we using?
- Which ones does Cmore plan on using in desktop attribution project?
- What type of sanity checks to we want to do?
- How do we want each parameter to be used?
- Is there a nomenclature that should be respected?

**Comment by vladikoff** [comment] 2017-08-16 18:17
We cleaned up the UTM params and added extra validation. Please reopen if anything else is needed here

**Comment by davismtl** [comment] 2017-08-16 18:21
I don't think we've answered most of the questions from the issue. If we have (my apologies), please include a link to read more details.

**Comment by vladikoff** [comment] 2017-08-16 18:23
@davismtl I think we updated these to send things like `/firefox/sync` in params, but I will reopen if there are still questions about this.

**Comment by philbooth** [comment] 2018-09-17 16:32
This seems like it might be a duplicate of mozilla/fxa-amplitude-send#44. Closing, but re-open if they're different.

**Closed by philbooth** 2018-09-17 16:32 UTC
Labels: 2018, waffle:backlog
