### ISSUE TITLE
Make verification code fields more forgiving

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#2501] opened 2019-09-13 13:51 UTC
Noticed during the last [Sync Fest](https://docs.google.com/document/d/1vV-NKmXINm-M_oYmERZlcKOXFKGwsNeV8uQM_ugbW8g/edit#) was the our verificiation code input fields are not very forgiving.

<img width="408" alt="image" src="https://user-images.githubusercontent.com/68213/64867510-8112fb80-d60b-11e9-85f2-733dd4836c91.png">

There are two approaches we could take:
1. STRICT: Limit the fields to 6 digits
1. TOLERANT: Accept the first six digits entered as the code

Is there a preference?

As this is top of funnel I'm marking it P1.

**Comment by clouserw** [comment] 2019-09-13 16:09
Duplicate of #2498

**Closed by clouserw** 2019-09-13 16:09 UTC
Labels: P1
