### ISSUE TITLE
error message upon logging into dev server

### ISSUE THREAD

**Issue by janiceahn** [mozilla/fxa#1988] opened 2019-07-29 18:33 UTC
after signing into the dev server, i'm redirected to the settings page. unclear why this error message appears: 
![image](https://user-images.githubusercontent.com/6219141/62072974-c02cef00-b20d-11e9-914a-efa7a6964b81.png)

**Comment by lmorchard** [comment] 2019-07-29 18:34
This is probably a duplicate of #1984

**Closed** 2019-07-29 18:54 UTC
