### ISSUE TITLE
[iOS] "list of common passwords" link not working

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa#2590] opened 2019-09-24 08:53 UTC
Environment:
iOS, stage server

Steps to reproduce:
1. Go to "Sign in to Sync".
2. Enter a valid email and tap on "Continue".
3. Tap on the password field and wait for the password bubble to be displayed.
4. Tap on "list of common passwords" from the bubble.

Expected result: https://support.mozilla.org/en-US/kb/password-strength is opened in a new tab.

Actual results: the content is not displayed.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-369)
┆Issue Number: FXA-369

**Comment by shane-tomlinson** [comment] 2019-09-24 08:58
Hmm, since FxA within Firefox for iOS can't open new tabs, the appropriate behavior here is probably to show the link URL inline.

cc @ryanfeeley

**Comment by vasilicatamas** [comment] 2021-01-19 13:46
This issue is no longer reproducible on Firefox Daylight 30.0 (3279) under iOS 13.6. The list of common passwords is successfully opened in a new tab. Closing.

![issue74](https://user-images.githubusercontent.com/18114210/105042882-740ee380-5a6d-11eb-912f-4ca5631ddb9d.gif)

**Comment by vasilicatamas** [comment] 2021-01-19 13:47
This issue is no longer reproducible on Firefox Daylight 30.0 (3279) under iOS 13.6. The list of common passwords is successfully opened in a new tab. Closing.

![issue74](https://user-images.githubusercontent.com/18114210/105042882-740ee380-5a6d-11eb-912f-4ca5631ddb9d.gif)

**Closed by vasilicatamas** 2021-01-19 13:46 UTC
Labels: needs:ux
