### ISSUE TITLE
Update FPN icon on payments Server

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa#4834] opened 2020-04-09 19:42 UTC
https://github.com/mozilla/fxa/blob/80a62a9da504f49825b891acdc1da7f32d58bbb8/packages/fxa-payments-server/src/images/fpn.js

Need to update to reflect new logo.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1551)
┆Issue Number: FXA-1551

**Comment by data-sync-user** [comment] 2020-07-02 17:40
➤ Dave Justice commented:

[~jgruen@mozilla.com] Can I get a link to the new svg to replace with here?

**Comment by data-sync-user** [comment] 2020-07-09 13:35
➤ John Gruen commented:

Marking this as complete since the icons are on the CDN and the rest of the work is effectively a dupe of 2194

**Comment by data-sync-user** [comment] 2020-07-09 13:37
➤ John Gruen commented:

Scratch that, I think what we should do here is reset the default image to something that's obviously a default image. This will help for debugging and testing. I don't beleive the work here blocks 179, so i am reopening and pushing this out

**Closed** 2020-07-17 14:38 UTC
