### ISSUE TITLE
The survey disappears after the page refresh

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#5559] opened 2020-06-05 14:07 UTC
**Build**
Stage [Train 1.174.0]

**Affected platforms**
Windows 10 64-bit
Android 9
iOS 13.4.1

**Steps to reproduce**
1. Launch Firefox with a new profile and login using a Firefox account.
2. Go to https://accounts.stage.mozaws.net/reset_password
3. Refresh the page.

**Expected results**
The survey is still displayed after a page refresh.

**Actual Results**
The survey disappears after refreshing the page.

![issue5](https://user-images.githubusercontent.com/18114210/83885237-bab60480-a74e-11ea-8ecf-d544226b8a25.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2049)
┆Issue Number: FXA-2049

**Comment by data-sync-user** [comment] 2020-06-09 20:22
➤ Wil Clouser commented:

This is working as we think it was designed.  [~adavis@mozilla.com] [~jgruen@mozilla.com]  can you clarify when the survey should be shown?

Depending on that answer, this may be a significant amount of work (storing which surveys people have seen [maybe there are more than 1 surveys active], which devices they've seen a survey on, etc.)

**Comment by data-sync-user** [comment] 2020-06-09 20:33
➤ Chelsea Lewis commented:

[~bchen@mozilla.com] as we discussed in triage, perhaps this is indeed a requirement which was missed. 

Per the requirements document ( https://docs.google.com/document/d/1HUWdFuC7jks8yStxfJtttuGqHHQ5kp3aA39BmcEV6gA/edit# ),
... to be easy to dismiss but if dismissed, they can re-open it after completing whatever step they are at.
If a user should be able to dismiss at any point of the survey and then come back to complete it later, it lends me to believe they should also be able to refresh their page in between that dismissal and completion.

**Comment by data-sync-user** [comment] 2020-06-09 21:33
➤ Alex Davis commented:

>  to be easy to dismiss but if dismissed, they can re-open it after completing whatever step they are at.

We're already covering that as it was intended by allowing users to collapse the survey. However, I admit that if the user were to complete what he's doing (e.g. submit the form) then the redirect will probably kill the survey.

I feel comfortable with the way it is now because if we allow the survey to persist refreshes and redirects, we will also need a way for users to completely dismiss the survey rather than just collapsing them.

I wouldn't close this but I might mark this as a story for future improvements.

**Comment by data-sync-user** [comment] 2020-06-16 00:50
➤ Dave Justice commented:

I'm assuming this has to do with the value we are setting in local storage, I think this can be a quick fix once I verify that is the cause. Will swing around to this once higher priority issues are resolved.

**Comment by data-sync-user** [comment] 2020-06-17 15:00
➤ John Gruen commented:

So we're going to mark this as wontfix and maybe file a different issue to better persist the survey across views in the future, this is the expected behavior for now

**Closed by data-sync-user** 2020-06-17 15:00 UTC
