### ISSUE TITLE
FxA payment server passes "undefined_oauth" service parameter

### ISSUE THREAD

**Issue by YeonjooSmith** [mozilla/fxa#11897] opened 2022-02-09 17:21 UTC
## Description
After the service parameter for the VPN service instrumentation from Bedrock([bedrock#10701](https://github.com/mozilla/bedrock/issues/10701), [bedrock#10704](https://github.com/mozilla/bedrock/pull/10704)), the `fxa-payments-server` and the `fxa-auth-server` started to pass `undefined_oauth` for the service parameter. The auth server has been updated to pass the service parameter for the VPN service(`guardian-vpn`) througth fxa issue [#10839](https://github.com/mozilla/fxa/issues/10839). However, the payment server still passes `undefined_oauth` instead of `guardian-vpn`.  

## Impact
The `service` parameter is used for the ETL work to create tables used to monitor the VPN service user journey. When `service` parameter is not appropriately linked or changed, some of the event logs for VPN users get lost like [DVPN-94](https://mozilla-hub.atlassian.net/browse/DVPN-94). The data engineers are working on fixing this issue by changing how logs associated with the VPN service is filtered for now in a detouring way. However, having the consistent service parameter for all three servers (content, auth, payment) used to monitor user journeys for the VPN service will make the ETL job easier in the long run. 

### Steps to reproduce
1. Go through the VPN acquisition funnel from the VPN product site(mozilla.org/vpn) to the payment confirmation page. For each web page in the funnel steps, save the flow id in the URL like [this doc](https://docs.google.com/document/d/1ObfTqpi5ixAKdcdSK8RL-l6q20T_fQ40alSvMObZroU/edit?usp=sharing). 
2. Check the logs for the flow id and user id associated with it and check the service parameter for `logger = fxa payments server`
<img width="712" alt="image" src="https://user-images.githubusercontent.com/49305857/153254937-0d19c3cd-e9e3-49c2-abe0-a19f06ffb716.png">

### Expected result
'service' parameter should be either NULL or `guardian-vpn`

### Actual result
`service` parameter appears as `undefined_oauth`. See [this spreadsheet](https://docs.google.com/spreadsheets/d/1IjOLbzGfFfISnKFfpc5sqhWBpx9rJKlXqd84SqV8R6c/edit?usp=sharing) for the test case query result.  

### Environment
Safari and Firefox Nightly

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4588)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/22371">image-20220331-191914.png</a>

**Comment by data-sync-user** [comment] 2022-02-09 19:17
➤ Barry Chen commented:

This is caused by the Payments server’s metrics transform function not being initialized with a list of services.  We should have the init call on Payments match the one in content-server.  See https://github.com/mozilla/fxa/blob/50e124b518a15898f457b468260a7b7128029da0/packages/fxa-payments-server/server/lib/amplitude.js#L37 ( https://github.com/mozilla/fxa/blob/50e124b518a15898f457b468260a7b7128029da0/packages/fxa-payments-server/server/lib/amplitude.js#L37|smart-link )  and https://github.com/mozilla/fxa/blob/50e124b518a15898f457b468260a7b7128029da0/packages/fxa-content-server/server/lib/amplitude.js#L460 ( https://github.com/mozilla/fxa/blob/50e124b518a15898f457b468260a7b7128029da0/packages/fxa-content-server/server/lib/amplitude.js#L460|smart-link )

**Comment by data-sync-user** [comment] 2022-02-23 17:53
➤ Anna Sobiepanek commented:

https://github.com/mozilla-services/cloudops-infra/pull/3830 ( https://github.com/mozilla-services/cloudops-infra/pull/3830|smart-link )  additional pull

**Comment by data-sync-user** [comment] 2022-03-01 21:39
➤ Yeonjoo Yoo commented:

I queried the events logged by the payment server ( https://sql.telemetry.mozilla.org/queries/84528/source ) and the service parameter is still not emitting. Am I missing something?

**Comment by data-sync-user** [comment] 2022-03-01 23:37
➤ Barry Chen commented:

Our production deploy was delayed to Monday Feb 28 mid-day so that’s likely the reason.

**Comment by data-sync-user** [comment] 2022-03-08 19:53
➤ Barry Chen commented:

This doesn’t appear to be fixed in production.  Moving back to To Do.

**Comment by data-sync-user** [comment] 2022-03-30 23:23
➤ Barry Chen commented:

I noticed today, while doing some unrelated queries, that the “service” property is now properly populated.  Yeonjoo Yoo  please verify and let me know.  Thanks!

**Comment by data-sync-user** [comment] 2022-03-31 14:56
➤ Yeonjoo Yoo commented:

Barry Chen I just confirmed(query ( https://console.cloud.google.com/bigquery?sq=470293616514:daf34062c8fe4b0fa1ce3b1105ef905f )) that the service parameter started showing up from March 9th! Thank you for letting me know 🙂

**Comment by data-sync-user** [comment] 2022-04-01 14:54
➤ Barry Chen commented:

Yeonjoo Yoo Thank you for the additional investigation/verification.

**Closed by data-sync-user** 2022-04-01 14:54 UTC
