### ISSUE TITLE
Sub Plat Payment Page — Zip form field error

### ISSUE THREAD

**Issue by janiceahn** [mozilla/fxa#2867] opened 2019-10-11 20:15 UTC
The field-level error message shows as soon as the user enters a character.

The error should appear once the user leaves that form field, otherwise it will show through the field entry process (until user enters the full five digits).
<img width="467" alt="Screen Shot 2019-10-11 at 4 14 19 PM" src="https://user-images.githubusercontent.com/6219141/66682144-4a4bf780-ec42-11e9-870e-c69ff830adb2.png">

**Comment by lmorchard** [comment] 2019-10-11 20:23
I think this is a duplicate of #2853 and #2096 - we may have a fix for it already, but the code hasn't been deployed.

**Comment by LZoog** [comment] 2019-10-11 22:17
This is definitely a dupe of at least #2096, I'm going to close this for now.

**Closed by LZoog** 2019-10-11 22:17 UTC
