### ISSUE TITLE
Confusing message in the modal after multiple clicks on the "Cancel" subscription button

### ISSUE THREAD

**Issue by rlr** [mozilla/fxa#3115] opened 2019-10-24 00:44 UTC
Issue reported by @SoftVision-LorandJanos in another repo:

#### Notes:
 The modal displayed after the second  click on the "Cancel" button informs the user that the cancellation failed after the second click on the "Cancel" button, but doesn't inform the user about the success of the actual cancellation of subscription.

#### Affected versions:
- Firefox Release 69.0.1
- Firefox Beta 70.0b9
- Firefox Nightly 71.0a1

#### Affected Platforms:
- Windows 10 (64-bit)
- MacOS 10.14.5
- Linux Ubuntu 16.04 (64-bit)

#### Prerequisites:
You have an active [Redacted] subscription.

#### Steps to reproduce
1. Go to the [Manage Subscriptions](https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/subscriptions).
2. Click on the "Cancel" button.
3. Check the box to confirm cancellation.
4. Click on the "Cancel Subscription" button multiple times.

#### Expected result:
A modal is displayed with the title "We're sorry to see you go".

#### Actual result:
- A modal is displayed that tells the user that the "Cancelling subscription failed" because the "Subscription has already been cancelled".
- The modal with the title "We're sorry to see you go" is not displayed.

![Screenshot_2019-10-22 Firefox Accounts Payments Server](https://user-images.githubusercontent.com/48829350/67285475-4b9ddf80-f4e0-11e9-8793-a62e0d97ba72.png)

**Comment by johngruen** [comment] 2019-10-25 09:34
@bbangert I suspect this is related to #3106 or #3061 or both

**Comment by bbangert** [comment] 2019-10-25 15:10
#3061 was due to a Lambda timeout from what we can verify, its been fixed so the issue closed. This actually sounds like a possible UX or state issue in the client.

**Comment by LZoog** [comment] 2019-10-25 16:00
I agree with Ben, without diving deep into this, it looks like we might be sending the request twice and updating the state to show the latest response (subscription failed to cancel since it's already canceled). We probably need to display a spinner on the button after it's been clicked once.

**Comment by shane-tomlinson** [comment] 2019-10-25 16:27
@LZoog - are you working on this? If so, can you assign it to yourself?

**Comment by LZoog** [comment] 2019-10-25 18:11
@shane-tomlinson I'll grab it, seems up my ally.

**Comment by LZoog** [comment] 2019-10-25 18:40
_Actually_ it looks like we already have a spinner in place for that state and a conditional to disable the button if so. :/ I'm having a hard time reproducing this in dev. I see it on stage, so I'll keep digging...

**Comment by LZoog** [comment] 2019-10-25 18:46
Ah, this looks like this has been addressed recently in #2971 by @meandavejustice.

I'm going to add that commit to the list of commits for the Train 148.9 release. Please reopen if this issue is not fixed with that release.

**Closed by LZoog** 2019-10-25 18:46 UTC
Labels: [QA]:Blocker issue

**Comment by SoftVision-LorandJanos** [comment] 2019-10-29 10:24
This issue is no longer reproducible [Subscription settings](https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/subscriptions?device_id=36edae75f33541d1ba6ff882c993b873&flow_begin_time=1572344262024&flow_id=b9120ef71213dd9d01501d7bc04248f8e050f9deed097e6cd7facbf0b072781e), using the latest Firefox Release (70.0), Beta (71.0b4) and Nightly (72.0a1). Verified on Windows 10 x64, Mac 10.14.2 and Linux Ubuntu 16.04 x64.
