### ISSUE TITLE
"Email Preferences" button not displayed in Manage Account page on iOS

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#4023] opened 2020-02-03 09:29 UTC
**Build:**
Stage [Train 1.155.0]

**Affected platforms:**
iOS 13.1.2

**Steps to reproduce:**
1. Launch Firefox and login into fxa using a mozilla account.
2. Go to https://accounts.stage.mozaws.net/settings
3. Check the “Email preferences” button from the bottom of the page.

**Expected results:**
“Email preferences” button is successfully displayed.

 **Actual Results:**
“Email preferences” button misses from Manage Account page.

**Notes:**
This issue reproduces only on iOS.

![Screenshot_20](https://user-images.githubusercontent.com/18114210/73641161-440ddb00-4678-11ea-8aeb-4f7ee09aacaf.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1017)
┆Issue Number: FXA-1017
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/12451/RecordIt-1580807325.mp4">RecordIt-1580807325.mp4</a>

**Comment by data-sync-user** [comment] 2020-02-03 21:58
➤ Jared Hirsch commented:

Yup, I can confirm this happens on both production and staging servers.

**Comment by data-sync-user** [comment] 2020-02-03 22:06
➤ Jared Hirsch commented:

This is a wontfix: it's working as intended.

Looking at the original issue ( https://github.com/mozilla/fxa-content-server/issues/5465 ), it appears that the unsubscribe button didn't work on iOS, so it was removed.

**Comment by data-sync-user** [comment] 2020-02-03 22:30
➤ Jared Hirsch commented:

This is a wontfix: it's working as intended.

Looking at the original issue ( https://github.com/mozilla/fxa-content-server/issues/5465 ), it appears that the unsubscribe button didn't work on iOS, so it was removed.

**Comment by data-sync-user** [comment] 2020-02-04 09:20
➤ Vasilica Tamas commented:

The Email Preferences UI has changed and the “Unsubscribe” button was replaced by a checkbox. Tested on iOS, by sending the Email Preferences tab from desktop to iOS via “Send tab to device” option and I successfully managed to subscribe and unsubscribe from the iOS side - see attached video.

**Closed** 2020-02-06 17:30 UTC
