### ISSUE TITLE
service parameter not passed from the fxa content server 

### ISSUE THREAD

**Issue by YeonjooSmith** [mozilla/fxa#11130] opened 2021-11-23 17:42 UTC
## Description
I was testing the acquisition funnel for the VPN and check if a bug(#10838) on the CTA was fixed.  
I went through the steps to subscribe VPN with a couple of different ways yesterday and check the flow ids, I see that the service parameter is not logged. It was passed before when I tested it in October but it is not anymore so something might have been changed. 

### Why is it important
the service parameter is the indicator to filter VPN customers from FxA data to track the user journey. The auth server and the payment server does not pass the service parameter so the service parameter from the content server is only one that let me weave all the event logs related to the VPN service from different servers. 

### Steps to reproduce
[Here](https://docs.google.com/document/d/1aBVBs_f-pt6XYQNdgUmI4E7-6et6nSMMfpajVHGhrWQ/edit?usp=sharing) is the steps that I went through with the url that includes flow id in each step to test the funnel in 11/21/2021. Also this document has links for the query and query results. 
 
### Expected result
From my testing funnel results in October([query here](https://sql.telemetry.mozilla.org/queries/83017/source), [query result in the spreadsheet](https://docs.google.com/spreadsheets/d/1HwB_zAEk8dBwTWNa9E3XzaFRLcXA_ndJI2X8PsWRl_8/edit?usp=sharing)), the content server should have the service parameter as `guardian-vpn`.  

### Actual result
The service parameter missing. Please refer to the doc link in **Steps to reproduce**. 

### Environment
included in the doc

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4255)

**Comment by YeonjooSmith** [comment] 2021-11-23 17:56
cc:@vbudhram

**Comment by data-sync-user** [comment] 2021-11-23 19:58
➤ Bianca Danforth commented:

Yeonjoo Yoo : I want to make sure I understand the issue here – so when you are an existing FxA user, logged out and going through the passwordless checkout flow, you do not see the service query param as expected in each of the URLs in the steps you describe here ( https://docs.google.com/document/d/1aBVBs_f-pt6XYQNdgUmI4E7-6et6nSMMfpajVHGhrWQ/edit# )?

Vijay Budhram Are you working on this already? Just want to make sure we don’t duplicate our efforts here.

**Comment by YeonjooSmith** [comment] 2021-11-23 20:07
@biancadanforth  To be clear, I don't know how FxA content server get the service parameter. What I am pointing out is that in the service parameter in logs from the content server in this query result(https://docs.google.com/spreadsheets/d/1HwB_zAEk8dBwTWNa9E3XzaFRLcXA_ndJI2X8PsWRl_8/edit#gid=1445295622) is missing. It was not missing when I tested in October (https://docs.google.com/spreadsheets/d/1HwB_zAEk8dBwTWNa9E3XzaFRLcXA_ndJI2X8PsWRl_8/edit?usp=sharing).

**Comment by data-sync-user** [comment] 2021-11-23 20:11
➤ Yeonjoo Yoo commented:

Bianca Danforth To be clear, I don't know how FxA content server get the service parameter. What I am pointing out is that in the service parameter in logs from the content server in this query result(https://docs.google.com/spreadsheets/d/1HwB_zAEk8dBwTWNa9E3XzaFRLcXA_ndJI2X8PsWRl_8/edit#gid=1445295622 ( https://docs.google.com/spreadsheets/d/1HwB_zAEk8dBwTWNa9E3XzaFRLcXA_ndJI2X8PsWRl_8/edit#gid=1445295622|smart-link ) ) is missing. It was not missing when I tested in October (

https://docs.google.com/spreadsheets/d/1HwB_zAEk8dBwTWNa9E3XzaFRLcXA_ndJI2X8PsWRl_8/edit?usp=sharing ( https://docs.google.com/spreadsheets/d/1HwB_zAEk8dBwTWNa9E3XzaFRLcXA_ndJI2X8PsWRl_8/edit?usp=sharing|smart-link ) 

).

**Comment by data-sync-user** [comment] 2021-11-23 20:27
➤ Bianca Danforth commented:

Okay thanks Yeonjoo (by the way I think those links to the queries are the same doc? I see the “service” column in both).

I’ll leave this ticket here for the FxA team to triage (as opposed to the SubPlat team), since the content server is largely in their area of expertise.

**Comment by data-sync-user** [comment] 2021-11-23 20:38
➤ Yeonjoo Yoo commented:

Bianca Danforth  Thank you for pointing out the links! I just edited the links so that they support my point.

**Comment by data-sync-user** [comment] 2021-11-24 19:32
➤ Anna Sobiepanek commented:

Vijay Budhram  is this a dupe of https://mozilla-hub.atlassian.net/browse/FXA-4148 ( https://mozilla-hub.atlassian.net/browse/FXA-4148|smart-link ) 

Yeonjoo Yoo  is this blocking your analysis of the Conversion Funnel Optimization you are working on?

**Comment by data-sync-user** [comment] 2021-11-29 14:49
➤ Yeonjoo Yoo commented:

Anna Sobiepanek Vijay Budhram Isn’t this different from FxA-4148 as the fxa content server previously emitted the service parameter but not anymore? That is my reason that I filed this bug. 

  * is this blocking your analysis of the Conversion Funnel Optimization you are working on? 
    * Yes. This is  an unexpected blocker. The service parameter in the content server identifies users that go through FxA for the VPN service.

**Closed** 2021-11-30 17:58 UTC
