### ISSUE TITLE
OAuth relier logins leave behind a separate "web session" in devices-and-apps view

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#946] opened 2019-04-26 14:43 UTC
I'm signed into Lockbox on my phone, but the session shows up as 2 web sessions.

<img width="533" alt="Screenshot 2019-04-26 at 15 41 30" src="https://user-images.githubusercontent.com/848085/56815724-f2f3cf80-6839-11e9-97e4-e43656507454.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-829)
┆Issue Number: FXA-829

**Comment by vladikoff** [comment] 2019-04-26 14:45
@shane-tomlinson in addition, do you get sync devices in there?

**Comment by vladikoff** [comment] 2019-04-26 14:45
ref https://github.com/mozilla/fxa/issues/466

**Comment by shane-tomlinson** [comment] 2019-04-26 14:54
> @shane-tomlinson in addition, do you get sync devices in there?

<img width="510" alt="Screenshot 2019-04-26 at 15 53 27" src="https://user-images.githubusercontent.com/848085/56816451-7bbf3b00-683b-11e9-8faf-e6660850f755.png">

<img width="497" alt="Screenshot 2019-04-26 at 15 53 57" src="https://user-images.githubusercontent.com/848085/56816476-8679d000-683b-11e9-8224-969ddd53e385.png">

**Comment by vladikoff** [comment] 2019-04-26 14:57
> do you get sync devices in there?

I guess that's a no? that's strange!

**Comment by vladikoff** [comment] 2019-04-29 20:16
I checked with jbuck and Lockbox has a `canGrant` set to `1`, so it doesn't show an APP entry in Devices & Apps, which is confusing. 

see https://github.com/mozilla/fxa/blob/00c619bec9b00aa162551263a9ad6b394e45b453/packages/fxa-auth-server/fxa-oauth-server/lib/db/mysql/index.js#L223


cc @rfk

**Comment by rfk** [comment] 2019-05-02 04:32
From conversation with Shane, what I think is happening here is:

1. You initiate signin in the Lockbox app, which load FxA in a webview.
2. You enter your username and password in the webview, which creates a sessionToken.
3. That sessionToken is used to authorize an OAuth token for Lockbox.

Because the sessionToken from (2) is never explicitly deleted, and it never gets claimed by a device record, it hangs around as a "web session" until it expires.  IIRC sessionTokens without a device record expire after 4 weeks.

Because the Lockbox OAuth client has `canGrant=1`, its OAuth token does not show up in the "devices and apps" list.  The filtering that Vlad links above was designed to avoid showing tokens owned by Firefox instances that also have a sessionToken.  But in this case, the sessionToken is not owned by Lockbox - it's used by the webview as part of signing in to Lockbox but is orphaned as soon as the login process completes.

I think we have two things to do here.

a) The devices and apps list should *always* show OAuth refresh tokens, even if they're held by clients with `canGrant=1`. The only time we shouldn't show a refresh token if when it's attached to a device record, in which case we show the device record.

b) The sessionToken from step (2) above either needs to be explicitly deleted at the end of the login flow, or it needs to automagically end up on a device record alongside Lockbox's refresh token.

I think we can fix (a) as part of https://github.com/mozilla/fxa/issues/466, but I'm not really sure how to accomplish either of the options in (b) without doing something gross.

**Comment by callahad** [comment] 2019-05-14 17:27
I think I just ran into case (a). Lockbox has live access to my synced logins, but there is no evidence of it in my Devices and Apps list, and thus nothing to revoke if I lose my phone.

![where-is-lockbox](https://user-images.githubusercontent.com/24193/57718448-368d6c80-7675-11e9-868f-01dd6dd9458e.png)

I don't see Fenix in there either, but it can totally sync, too.

This is scary: what else has access to my synced data that I might not know about? How can I protect myself if I lose my device?

**Comment by rfk** [comment] 2019-05-15 20:40
Thanks @callahad, just wanted to note here that we're not ignoring this, will hopefully have an update shortly...

**Comment by rfk** [comment] 2019-05-28 04:09
So https://github.com/mozilla/fxa/pull/1178 should fix the issue of lockbox not appearing in the "devices and apps" list, with follow-up work in https://github.com/mozilla/fxa/issues/466.

The remaining issue here is that the Lockbox login process generates sessionToken which is not handed off to the app, and which just hangs around as an extra "web session" until it expires. I'm not entirely sure what to do about this one. We could either:

1. Have fxa-content-server delete the sessionToken before redirecting back to the app at the end of the OAuth dance.
2. Arrange for the sessionToken to get attached to a device record for the corrsponding Lockbox instance.

I kinda lean towards (2).

**Comment by mcomella** [comment] 2019-07-16 00:20
I experienced something similar when developing Firefox for Fire TV FxA login in https://github.com/mozilla-mobile/firefox-tv/issues/2445: after logging in, users have both a "Web Session" and a "Firefox for Fire TV" in their accounts.firefox.com dashboard:

![image](https://user-images.githubusercontent.com/759372/61257152-a3c88700-a724-11e9-9ad3-6fb83a7910b9.png)

**Comment by rfk** [comment] 2019-07-16 02:04
Ref my earlier comment https://github.com/mozilla/fxa/issues/946#issuecomment-496358119, I still feel like the right outcome here is for these sessionTokens to wind up attached to the device record of the corresponding app instance.  If we can arrange for that to happen, then the view here in the devices-and-apps list will automatically do the right thing, and we'll also get other benefits like ensuring the user is signed out of FxA on the web when they sign out of Fenix or FireTV.

I'm not 100% sure how to make that happen though. One option would be adding a `sessionTokenId` field to the OAuth `codes` table, and then when the code is exchanged for OAuth tokens, we can link the `sessionTokenId` to the [placeholder device record](https://github.com/mozilla/fxa/blob/91c94c7464190cab341dfed27f00b93018571788/packages/fxa-auth-server/lib/routes/utils/oauth.js#L57) that gets created.

At least the `codes` table is small, so adding a new column to it shouldn't be too bad.

**Comment by sv-sdeiac** [comment] 2020-02-14 12:06
Hello, about the duplication of the devices on the "Devices & apps".
In the Fenix app, when you are connected to an affected account and want to share something with a specific device, it is very difficult to find the specific session since the list is populated with a couple of duplicates from the previous logins. 
From a QA perspective:
For the Fenix application, since it is a different UI to share something to a different device, can we make an option to long tap to a specific device so we can delete it(from the list=disconnecting)? An example is the selection of multiple entries from the History page.

**Comment by data-sync-user** [comment] 2021-05-28 17:46
➤ Wil Clouser commented:

This is fixed in the new settings redesign

**Closed by data-sync-user** 2021-05-28 17:46 UTC
