### ISSUE TITLE
Add support for multiple redirect uris

### ISSUE THREAD

**Issue by jbuck** [mozilla/fxa#5488] opened 2020-05-28 15:46 UTC
An oauth relier is migrating from one domain to another. To make this migration not require a simultaneous deploy of the relier and FxA db change it'd be great to allow multiple uris in the database (maybe space-separated like the scopes column?). If the redirect_uri exactly matches one of the space-separated uris in the database then the sign-in request will be allowed to proceed.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1999)
┆Issue Number: FXA-1999

**Comment by vladikoff** [comment] 2020-05-28 16:03
I think for Lockbox/Lockwise in the past we just did a redirect on the old domain to the new one. Not sure if that can work here

**Comment by jbuck** [comment] 2020-05-28 16:52
@6a68 found this [older feature request](https://github.com/mozilla/fxa/issues/1045)

**Comment by 6a68** [comment] 2020-05-28 19:40
@jbuck would it be easy to just do a redirect from the old domain to the new one?

**Comment by 6a68** [comment] 2020-06-01 18:20
@jbuck what are the two redirect URLs? trying to determine if a varchar(256) field will be good enough to hold both

**Comment by data-sync-user** [comment] 2020-06-01 20:10
➤ Jared Hirsch commented:

Doesn't look like there will be time for me to work on this after all.

Unassigning and putting this back in the backlog.

**Comment by clouserw** [comment] 2020-06-01 21:03
I'm going to mark this as a duplicate of the above issue.  

@jbuck we should pursue one of the other options in the mean time though as it doesn't look like we'll have time to finish this.

**Closed by clouserw** 2020-06-01 21:03 UTC
