### ISSUE TITLE
The payment confirmation email is not sent

### ISSUE THREAD

**Issue by madalincm** [mozilla/fxa#5108] opened 2020-04-24 13:00 UTC
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Windows 10 (64-bit)

#### Preconditions
- existent FxA account with no subscriptions

#### Steps to reproduce
1. Open the [stage website](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn)
2. Click on the Subscribe now button and complete the subscription process.
3. Observe the received emails.

#### Expected result:
- The payment confirmation email is sent.

#### Actual result:
- The payment confirmation email is not sent.

#### Notes
- fxa account used to reproduce this issue today: mcotetiu+mt01@mozilla.com, mcotetiu+mt02@mozilla.com, mcotetiu+mt03@mozilla.com

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1765)
┆Issue Number: FXA-1765

**Comment by lmorchard** [comment] 2020-04-27 16:54
Took a look at our Stripe settings on staging and realized our webhook subscription is missing 3 of the new events for these emails. Looks like they are `invoice.payment_failed`, `invoice.payment_succeeded`, and `customer.source.expiring`. I added them on the SUB_PLAT_STAGE:

<img width="214" alt="Capture" src="https://user-images.githubusercontent.com/21687/80398690-e18a3c80-886c-11ea-88d3-e9e664db1392.PNG">

I *think* that resolves this issue without a code change, because I see both a download email and a payment confirmed email when I subscribe to Firfefox Guardian on stage.

**Comment by bsurd** [comment] 2020-04-28 12:07
Verified today and an invoice is received when making a subscription.

**Comment by bsurd** [comment] 2020-04-28 12:27
Reopening due to #5133  and #5134.

**Comment by lmorchard** [comment] 2020-04-28 16:04
> Reopening due to #5133 and #5134.

Since the email arrived, it looks like this issue is fixed. Closing this issue, since #5133 & #5134 are new follow-on issues with the email that arrived.

**Closed by lmorchard** 2020-04-28 16:04 UTC
Labels: severity:major, status:bug
