### ISSUE TITLE
Refactor inlined CSS (fxa-auth-server)

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#13439] opened 2022-06-24 22:32 UTC
## Description

A few inlined styles in the /packages/fxa-auth-server.
Feel free to close this if these are just email templates or whatever.

### Steps to reproduce

```sh
git grep -n " style=" packages | grep -Ev "\.(md|svg):" | grep -v "/123done/" | grep -Ev "\.(test|stories)\."

packages/fxa-auth-server/lib/senders/email.js:154:    return `href="${url}" style="color: #0a84ff; text-decoration: none; font-family: sans-serif;"`;
packages/fxa-auth-server/lib/senders/email.js:2906:    links.accountSettingsLinkAttributes = `href="${links.accountSettingsUrl}" target="_blank" rel="noopener noreferrer" style="color:#ffffff;font-weight:500;"`;
packages/fxa-auth-server/lib/senders/email.js:2913:    links.cancellationSurveyLinkAttributes = `href="${links.cancellationSurveyUrl}" style="text-decoration: none; color: #0060DF;"`;
```

### Expected result

What should happen?

### Actual result

What happened.

### Environment

What browser and operating system are you using?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5430)

**Comment by LZoog** [comment] 2022-06-27 14:32
This is basically a dupe of FXA-4761 / #12259 but with two more call outs.

I'm going to close that one in favor of this one, since this covers them all.

**Comment by cknowles-admin** [comment] 2022-08-11 17:44
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.

**Closed by cknowles-admin** 2022-08-11 17:44 UTC
Labels: maintenance
