### ISSUE TITLE
Recovery keys should also act as 2FA recovery codes

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#476] opened 2019-01-04 00:52 UTC
From IRC, a user went to the trouble of generating an account recovery key, and then used it to get back into their account after losing their 2FA device.  They (quite reasonably) expected that the recovery key would function as a 2FA recovery code, but it didn't, and now they're locked out of their account.

We recently addressed some 2FA-related issues around password reset, so we don't want to rush into any change here.  But would it be reasonable for the password-reset procedure to generate a 2FA-verified session token when a recovery key is used?

Alternately, can we make it clearer that they do *not* function this way?

See also [Bug 1517654](https://bugzilla.mozilla.org/show_bug.cgi?id=1517654); chat log for reference:

```
<DouglasK> I've lost access to my firefox sync acct due to a lost device.  I know I can't get the data, and that's fine... but is there any way to just reset the full account and start over with my existing email address?
I can reset my password all the live long day, but can't reset the acct.  acct is under the same email as I'm registered on IRC with.
Mentioning rfkelly and ckarlof while it's still before 17h00 GMT-8.
<•rfkelly>Hi DouglasK; do you have two-step authentication enabled on your account?
<DouglasK> Yup... and the device is no longer in existence.
<•rfkelly> gotcha; unfortunately, unless you have saved 2FA recovery codes, there is currently no way to bypass the 2FA requirement and regain access to your account
<DouglasK> Is there any way to delete the account and start fresh?
<•rfkelly> you don't have any devices where the account is currently signed in, is that correct?
<DouglasK> I may have one.  But as I've changed the password in an attempt to regain access, it'll be signed out.
<•rfkelly> deleting the account also requires 2FA; I'm sorry I can't help you :-(
ideally we would have operational procedures for securely dealing with 2FA lockout and account recovery, but we don't have the resources or procedures to do so securely at this time
<DouglasK> Understood.  What really suck is that I understood the long hex string could regain access if ever auth was lost.
<•rfkelly> oh, you generated an "account recovery key"?
<DouglasK> Yes.  And it doesn't get me past 2fa.
<•rfkelly> yeah; I agree it should but it currently doesn't; /cc vbudhram adavis ^
I assume you've since used it and it is now no longer working?
<DouglasK> I don't know.
<•rfkelly> did you enter it in during a password reset attempt?
<DouglasK> Yes, during the first one.
Then, when I wanted to gen a new one, it wouldn't let me.
<•rfkelly> ugh, this really sucks; we let you down here with a bad product experience, giving you something that feels a lot like a 2FA recovery code but actually isn't
<DouglasK> If you ever find a way to delete the account from the servers, I'll be happy enough.  I'd like to create an account using the main account on my personal domain.
<•rfkelly> understood; could you please file a bug at [1] and give us your account details so that we can remember to follow up?
[1] https://bugzilla.mozilla.org/enter_bug.cgi?product=Cloud%20Services&component=Server:%20Firefox%20Accounts
by "account details" i mean just the email address - I can mark the bug confidential if you'd prefer not to have that in a public bug
<DouglasK> The other thing is this:  While I was still signed in, I tried to disable 2fa and it wouldn't do it.
Anyhoo.. I'll log the bug... I appreciate you even listening.
<•rfkelly> thanks for reporting this; I'm going to file an issue to ensure we follow up on the "recovery keys" vs "2fa recovery codes" thing because that really is a bad outcome
are you happy for me to copy-paste this chat log into a github issue?
<DouglasK> Sure thing.
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-655)
┆Issue Number: FXA-655

**Comment by rfk** [comment] 2020-08-17 03:56
See https://bugzilla.mozilla.org/show_bug.cgi?id=1658570 for another user who expected the "recovery key" to act as a "recovery code" (and who does not appear to have any recovery codes, hence would likely be very happy to be able to use the recovery key instead!)

**Comment by data-sync-user** [comment] 2021-05-21 17:11
➤ Wil Clouser commented:

If we did this, we'd need to expire the recovery key that was used, which would mean we'd also need a flow that says something about "you used your key, now regenerate a new one."  This is a good idea, but realistically it's an edge case and not something we're going to get to on our roadmap so I'm going to wontfix this.

**Closed by data-sync-user** 2021-05-21 17:11 UTC
Labels: fxa-auth-server

**Comment by data-sync-user** [comment] 2021-05-25 15:19
➤ Alex Davis commented:

> If we did this, we'd need to expire the recovery key that was used,

Yes but we already have some of those flows.

> realistically it's an edge case 

It's not really edge case. It's super confusing for our users that we have both recovery keys and recovery codes. Somewhere between 4-9% of users have recovery codes. If they also acted as recovery keys, that would be golden.

Ultimately, the goal is to reduce data loss caused by password resets.

There's an opportunity but it's up to you to decide how to prioritize (or if it's worth prioritizing).
