### ISSUE TITLE
Provide a way for reliers to confirm a user's login state without re-entering password

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#590] opened 2018-10-24 23:13 UTC
This is a followup to https://github.com/mozilla/fxa-content-server/issues/6658 and in service of https://github.com/mozilla/addons/issues/732.

To support enforcing 2FA on developer accounts in AMO, they'd like to do a flow like the following:

1. Have the user do an initial FxA OAuth flow without requiring 2FA.
2. Lookup the resulting userid in the AMO database to see if they're a developer.
3. If so, check whether they used 2FA during the login at (1).
4. If not, have the user do another FxA OAuth flow, this time passing query parameters to insist that they use 2FA

Such a flow is possible as of train-124, thanks to #6545 which added support for the `acr_values` query parameter.  However, due to various rough edges in our session handling (#5916), the user will be forced to enter their password twice - once for the OAuth flow at (1) and again for the OAuth flow at (4).

Can we provide a way for the relier to avoid a second password prompt at (4), that doesn't allow them to skip the initial authorization step at (1)?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-736)
┆Issue Number: FXA-736

**Comment by shane-tomlinson** [comment] 2019-06-20 21:21
ref https://github.com/mozilla/fxa/issues/640

**Comment by rfk** [comment] 2019-06-27 04:33
In a bit more detail, here's what would be required for `id_token_hint` approach described above:

* Add `id_token_hint` as a parameter on the OAuth relier model.
* During setup of the model, validate that `id_token_hint` contains a valid `id_token`
  * We could post it to a server-side verifier, or check the JWT signature in web content
  * If the given `id_token` is invalid, or its audience doesn't match the requesting client, error out.
* During signin, if a valid `id_token_hint` is present:
  * treat the signin as a `force_auth` flow for the user identified in said token.
  * if we have an existing `sessionToken` for that user, use it without any further prompting (don't prompt for their password, don't show the "continue to X" button, nothing)

I *think* this would give us all the desired properties, and interact nicely with #589 to allow AMO to guide developers into setting up 2FA on their account.

**Comment by shane-tomlinson** [comment] 2019-07-29 14:13
Ref https://github.com/mozilla/fxa/issues/1979 to support RP initiated logout.

**Comment by 6a68** [comment] 2019-10-03 21:04
I'm not sure if there's engineering work here beyond what's captured in #2132. Leaving unestimated.

**Comment by data-sync-user** [comment] 2020-04-09 18:34
➤ Jared Hirsch commented:

I think we're safe to dupe this to https://jira.mozilla.com/browse/FXA-261.

**Comment by data-sync-user** [comment] 2020-04-09 18:34
➤ Jared Hirsch commented:

Closing as a dupe of 261.

**Closed by data-sync-user** 2020-04-09 18:34 UTC
Labels: fxa-content-server
