### ISSUE TITLE
Update Content Server to use @sentry/node

### ISSUE THREAD

**Issue by chenba** [mozilla/fxa#3726] opened 2019-12-18 23:55 UTC
It's still using `raven`.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2)
┆Priority: Medium
┆Issue Number: FXA-2

**Comment by data-sync-user** [comment] 2020-01-10 17:11
➤ Wil Clouser commented:

This is a duplicate of FXA-876

**Closed by data-sync-user** 2020-01-10 17:11 UTC
Labels: cat:code-quality
