### ISSUE TITLE
The "Got it" button is not functional when the navigation link "Why is more than one device required?" is middle clicked [bz1555669]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#1460] opened 2019-05-31 00:44 UTC
From https://bugzilla.mozilla.org/show_bug.cgi?id=1555669

**Affected versions:**
67.0.1 (64-bit)

**Affected platforms:**
Windows 7 x64

**Prerequisites:**
To be able to see the about:welcome page on a version where this is not implemented please go to about:config and set:

identity.fxaccounts.autoconfig.uri to https://accounts.stage.mozaws.net
browser.newtabpage.activity-stream.fxaccounts.endpoint to https://accounts.stage.mozaws.net
Restart the browser.

**Steps to reproduce:**

- Launch the browser
- Fill in with a new valid e-mail address
- Complete the user creation flow until you reach the form with syncing a mobile number
- Middle click on the "Why is more than one device required?" button
- A new tab is opened with the explanation for the above question -> Click on "Got it" button

**Expected:**
The explanation prompt should be dismissed after clicking on the button.

**Actual result:**
The "Got it" button is not functional, the overlay with the explanation will not be dismissed. 
Recording: https://streamable.com/cf7xp

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-156)
┆Issue Number: FXA-156

**Comment by data-sync-user** [comment] 2021-02-12 15:23
➤ Vasilica Tamas commented:

This can be marked as a dupe of FXA-450 ( https://jira.mozilla.com/browse/FXA-450 )

**Comment by data-sync-user** [comment] 2021-02-12 15:26
➤ Vasilica Tamas commented:

marking as duplicated

**Closed by data-sync-user** 2021-02-12 15:26 UTC
