### ISSUE TITLE
Can't get fxa_rp_button views working in some Amplitude charts

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/fxa#2662] opened 2019-09-30 19:47 UTC
We use fxa_rp_button views to measure views of e.g. the Monitor button on WhatsNew pages. We can see how the button is performing using an Event Segmentation chart:

https://analytics.amplitude.com/mozilla-corp/chart/is6sk9j

However, when we try to create a funnel analysis or retention analysis with the exact same parameters, the data seem broken -- one of the events will be zero.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-386)
┆Issue Number: FXA-386

**Comment by irrationalagent** [comment] 2019-09-30 19:57
Right now the [/whatsnew](https://www.mozilla.org/en-US/firefox/69.0/whatsnew/all/) page hits our metrics endpoint on page load to retrieve a (new, randomly generated) device_id and flow_id. 

On our end, we log a `fxa_rp_button` event with those two values. 

If the user continues the flow by clicking the monitor button, the page passes device_id and flow_id back to us as query parameters. 

I think that we may be clobbering the device_id that they are passing us. A further complication is that a user might already be signed into the browser when they click the button on the /whatsnew page. This means that they should already have a device_id (since they are already any FxA user). So for users that are signed in, the /whatsnew page may have to retrieve the user's current device_id and include that instead of requesting a new one. 

My understanding is that amplitude needs device_id to link events to the same user/flow, therefore the /whatsnew page needs to pass us a device_id in order for us to associate the `fxa_rp_button` event to subsequent steps in the funnel. Am I wrong about that? 

@philbooth any guidance here?

**Comment by philbooth** [comment] 2019-10-01 12:57
> I think that we may be clobbering the device_id that they are passing us.

That's possible, although the code around it is pretty simple and it's not obvious to me how it might be going wrong yet:

https://github.com/mozilla/fxa/blob/7a14b1f65a7511d001ef33f4b74f47b9f11435a6/packages/fxa-content-server/app/scripts/models/flow.js#L55-L61

> This means that they should already have a device_id (since they are already any FxA user).

Actually, as you probably just noticed in the code above, `device_id` is regenerated on every page refresh if it's not in the query string. That was deliberately chosen as a good-enough easy implementation while we waited on an official proposal for persistent, cross-product device ids. And it's why we do things like e.g. set an explicit `sync_device_count` property rather than depend on Amplitude's own device count mechanism.

The only thing `device_id` is good for right now is linking back to events that occur before the `user_id` can be read from the db (or written to it, for sign-ups).

**Comment by philbooth** [comment] 2019-10-01 13:20
> > I think that we may be clobbering the device_id that they are passing us.
>
> That's possible, although the code around it is pretty simple and it's not obvious to me how it might be going wrong yet

Actually, what the code linked above does show is that the resume token takes precedence over the query string, so if they were passing a device id and a different device id was in the resume token it would be possible for it to be clobbered. But the resume token shouldn't be there at all when the relier first navigates to us, so it seems unlikely.

**Comment by hoosteeno** [comment] 2019-10-01 14:32
Here's the flow we're debugging:

https://www.mozilla.org/en-US/firefox/welcome/1/

When I go through that flow, I get the following parameters (formatted to make easier to read):

```
# On the button, before I click it:
https://monitor.firefox.com/oauth/init?
form_type=button&
entrypoint=mozilla.org-firefox-welcome-1&
utm_source=mozilla.org-firefox-welcome-1&
utm_campaign=welcome-1-monitor&
utm_medium=referral&
deviceId=370113fc965f410d8794acdf6098d799&
flowBeginTime=1569939862929&
flowId=348524a9b0922a18b88cc58b5e00aa86ca9a6fb4092e5c7d7b30c968ee732a4e

# After Monitor sends us through its OAuth init
https://accounts.firefox.com/oauth/signin
?client_id=302d56ef2a9af9fa&
redirect_uri=https%3A%2F%2Fmonitor.firefox.com%2Foauth%2Fconfirmed&
scope=profile&
response_type=code&
state=3fb2e4a8493be1b2f9b22ad5b9f006799e7db898e6e4020b0cfc209ae02ed91763729f7f72488329&
access_type=offline&
action=email&
form_type=button&
entrypoint=mozilla.org-firefox-welcome-1&
utm_source=mozilla.org-firefox-welcome-1&
utm_campaign=welcome-1-monitor&
utm_medium=referral&
deviceId=370113fc965f410d8794acdf6098d799&
flowBeginTime=1569939862929&
flowId=348524a9b0922a18b88cc58b5e00aa86ca9a6fb4092e5c7d7b30c968ee732a4e
```

The device ID doesn't change from the original fxa_rp_button through to the registration form.

**Comment by philbooth** [comment] 2019-10-01 15:01
> When I go through that flow, I get the following parameters (formatted to make easier to read)

I think the last three parameter names listed there all wrong fwiw. FxA expects them to be in snake_case rather than camelCase:

https://github.com/mozilla/fxa/blob/743c09e468d3c5929fb22b4530368c7da9afd5a2/packages/fxa-content-server/app/scripts/models/flow.js#L44-L57

So, to be explicit:

* `deviceId` needs to be `device_id`.
* `flowBeginTime` needs to be `flow_begin_time`.
* `flowId` needs to be `flow_id`.

I realise that's different to the property names returned by GET /metrics-flow`, which *are* in camelCase. Maybe we should consider accepting both snake_case and camelCase in the query string instead, as it seems this kind of confusion is likely to happen again.

(historical note: the two parts of this were implemented at completely different times by different people, so we didn't notice the discrepancy until it was already out in the wild)

**Comment by hoosteeno** [comment] 2019-10-01 15:15
As a single relier among a network of reliers, in light of the challenge of implementing metrics correctly and debugging them in time to avoid data loss, and considering that the two cases are already mixed in the server, I endorse completely the application of [Postel's law](https://en.wikipedia.org/wiki/Robustness_principle) here. FxA should accept either case. :)

**Comment by clouserw** [comment] 2019-10-14 17:10
With that PR merged, is there still work to do here?

**Comment by clouserw** [comment] 2019-10-21 17:04
@irrationalagent

**Comment by vbudhram** [comment] 2019-10-28 17:28
from mtg: @irrationalagent anything to do here? Is this still and issue?

**Comment by irrationalagent** [comment] 2019-10-28 17:44
Sorry.... so as far as I can tell this is [functioning as intended](https://analytics.amplitude.com/mozilla-corp/chart/new/jmst51i).

**Comment by data-sync-user** [comment] 2021-05-07 17:05
➤ Wil Clouser commented:

closing amplitude issues

**Closed by data-sync-user** 2021-05-07 17:05 UTC
