### ISSUE TITLE
"Manage subscription" page does not have “Terms of Service - Privacy Notice” footer

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#5676] opened 2020-06-16 05:13 UTC
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.175.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Preconditions
- existent FxA account with active subscription;

#### Steps to reproduce
1. Go to “Manage subscription” page -  https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/subscriptions 
2. Observe page footer.

#### Expected result:
- There is a page footer containing the “Terms of Service “ and  “Privacy Notice” links.

#### Actual result:
- There is no page footer.
![image](https://user-images.githubusercontent.com/15685960/84734222-0ff0e200-afa9-11ea-916c-a954f19587ef.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2125)
┆Issue Number: FXA-2125

**Comment by data-sync-user** [comment] 2020-06-23 20:23
➤ Wil Clouser commented:

From triage: John says this is by design.

**Comment by data-sync-user** [comment] 2020-06-23 20:23
➤ Wil Clouser commented:

wontfix

**Closed by data-sync-user** 2020-06-23 20:23 UTC
Labels: severity:normal, status:bug

**Comment by ValentinaPC** [comment] 2020-06-24 06:54
@clouserw Given the fact that those links were there in the past (see below screenshot from old mock-ups), we thought that would be expected to see them now, too.
![image](https://user-images.githubusercontent.com/15685960/85510895-ae5ff180-b600-11ea-9181-dd5d2798b3df.png)

**Comment by clouserw** [comment] 2020-06-24 14:06
@ValentinaPC it may be a design change, but my comment came from our triage with the Product Manager.  I think they didn't want to have those links because each product has its own ToS and privacy policy and those links would be confusing.
