### ISSUE TITLE
Subscription payments flow gets confused when switching between sign in and create account and back.

### ISSUE THREAD

**Issue by rlr** [mozilla/fxa#2504] opened 2019-09-13 15:09 UTC
Screen recording: https://cl.ly/fa9713360900

STR:

1- Go to: https://accounts.stage.mozaws.net/subscriptions/products/prod_FiJ42WCzZNRSbS
2- Enter username and password
3- Click "Create an account" link
4- Click "Have an account? Sign in" link
5- Click "Sign in" button
6- I end up on account settings page instead of payment form

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-351)
┆Issue Number: FXA-351

**Comment by shane-tomlinson** [comment] 2019-09-16 08:20
We have a stated goal of deprecating the legacy signin/signup flows and instead [use email-first for all flows](https://github.com/mozilla/fxa/issues/639). In the email-first flow there is no ability to switch directly between signin and signup.

**Comment by rlr** [comment] 2019-09-17 19:09
@shane-tomlinson I am getting similar behavior when going through email-first flow:

1- Sign out of https://accounts.stage.mozaws.net
2- Go to https://accounts.stage.mozaws.net/subscriptions/products/prod_FiJ42WCzZNRSbS?action=email
3- Enter email address and click continue
4- Enter password and click continue
5- I end up on account page (https://accounts.stage.mozaws.net/settings?action=email) instead of payment form.

**Comment by lmorchard** [comment] 2019-09-18 18:01
> 2- Go to https://accounts.stage.mozaws.net/subscriptions/products/prod_FiJ42WCzZNRSbS?action=email

FWIW, `?action=email` not supported on the subscription product redirect, I don't think. The issue is that there is no email-first flow there right now

**Comment by rlr** [comment] 2019-09-18 18:18
> FWIW, `?action=email` not supported on the subscription product redirect, I don't think. The issue is that there is no email-first flow there right now

ah ok. Makes sense.

I'm cool if this gets WONTFIXED because I am now authenticating before sending them to the subscription flow. That way I have an auth'd user when they are redirected back.

**Comment by data-sync-user** [comment] 2021-05-07 16:52
➤ Wil Clouser commented:

wontfix for last comment

**Closed by data-sync-user** 2021-05-07 16:52 UTC
