### ISSUE TITLE
Ensure that appropriate product icon is used for each subscription

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa#3244] opened 2019-11-05 16:29 UTC
Currently we hard code FPN icons on the payments server, for this epic, we will need to find a way to swap icons on a per product basis, places we will need to address are as follows:

- [x] On the payments server in the upgrade UI
- [ ] On the payments server on the payment verified redirect
- [ ] On the payments server on in reactivation confirmation modal

**Comment by lmorchard** [comment] 2019-11-05 17:01
FWIW, we *could* use Product metadata in Stripe to specify URLs for these icons - assuming we add Product metadata to subhub responses.

Otherwise, we'll need to code up some mapping of product ID to icon URL on the payments-server side, probably in a hard-coded JS module or server config settings.

**Comment by lmorchard** [comment] 2019-11-05 17:03
Could also consider this related to #2026 - insofar as the product download email has a hardcoded icon right now, too.

**Comment by LZoog** [comment] 2019-11-11 17:02
This is basically a dupe of #3039, I threw it in the accessibility epic for payments since the SVGs don't have alt text, but a fix here should close that issue too.

**Closed** 2019-11-26 18:49 UTC
