### ISSUE TITLE
Zip code field is the only field where validation is happening when typing

### ISSUE THREAD

**Issue by madalincm** [mozilla/fxa#2853] opened 2019-10-11 14:05 UTC
#### Affected versions:
- Firefox Release 69.0.1
- Firefox Beta 70.0b9
- Firefox Nightly 71.0a1

#### Affected Platforms:
- Windows 10 (64-bit)
- MacOS 10.14.5
- Linux Ubuntu 16.04 (64-bit)

#### Precondition
-The user is on the Subscriptions page and he is filling credit card details for a subscription
https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/subscriptions

#### Steps to reproduce
1. Fill the Name, Card number, Exp date and CVC and observe that the validation happens when those fields lose focus
2. Click in the Zip code field and start typing

#### Expected result:
- The validation is consistent across the form, the validation for zip code is happening when the field loses focus.

#### Actual result:
- Validation for the zip code filed is happening as you type and for Name, Card number, Exp date and CVC fields on loose focus
![validationOnZipCodeField](https://user-images.githubusercontent.com/15685441/66657876-2344f400-ec49-11e9-93b2-879668fb39a2.gif)

**Comment by clouserw** [comment] 2019-10-11 15:15
This kinda feels like a dupe of #2096, just 1 character later.  @meandavejustice

**Comment by lmorchard** [comment] 2019-10-11 16:30
I think it is a dupe of #2096 - I don't think that fix has gone out in any deployments yet

**Comment by lmorchard** [comment] 2019-10-21 16:11
https://github.com/mozilla/fxa/commit/7c9565410a56cb5ce74c93b7a27e711fc56058e8

**Closed by lmorchard** 2019-10-21 16:11 UTC
Labels: [QA]:Minor issue, status:bug
