### ISSUE TITLE
"Primary/secondary account set" not translated

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa#905] opened 2019-04-22 15:32 UTC
Environment:
Android, Production server

Steps to reproduce:
1. Change the language to Portuguese, Romanian, Chinese.
2. Go to Manage account and add a secondary email.
3. Change the email to be primary 2-3 times.

Expected results: the success message is translated.

Actual results: the success message is not translated.

**Comment by shane-tomlinson** [comment] 2019-04-22 15:42
I think this is the same root cause as https://github.com/mozilla/fxa/issues/902

@vbudhram - This came up [before, and I thought we fixed it?](https://github.com/mozilla/fxa-content-server/issues/6728)

**Comment by clouserw** [comment] 2019-04-22 17:25
Closing as a dupe of #902

**Closed by clouserw** 2019-04-22 17:25 UTC
