### ISSUE TITLE
“$undefined” pricing values are listed in subscription upgrade mail

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#5417] opened 2020-05-22 10:46 UTC
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.172.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Preconditions
- existent FxA account with active upgraded subscription;

#### Steps to reproduce
1. Go to subscription upgrade email.
2. Observe the upgrade billing plan section.

#### Expected result:
- User is informed with the new pricing details after the last subscription upgrade plan.

#### Actual result:
- Instead of pricing details, the“$undefined” string is displayed.

![image](https://user-images.githubusercontent.com/15685960/82659311-29fd0600-9c31-11ea-8056-71c5b948cbf4.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1958)
┆Issue Number: FXA-1958

**Comment by data-sync-user** [comment] 2020-05-26 16:56
➤ Les Orchard commented:

I can reproduce this issue and will have a fix shortly. Looks like it's the same email as FXA-1957

**Comment by data-sync-user** [comment] 2020-05-26 18:31
➤ Les Orchard commented:

https://github.com/mozilla/fxa/pull/5442

**Comment by ValentinaPC** [comment] 2020-06-02 07:25
Verified this in stage, using Fx76 and Windows 10 (64-bit).
Seems like the "$undefined" value is still there.
Please see screenshot bellow.
![image](https://user-images.githubusercontent.com/15685960/83492023-53345680-a4bb-11ea-92fb-65079ab341b6.png)

**Comment by data-sync-user** [comment] 2020-06-02 17:35
➤ Les Orchard commented:

I can reproduce. However, it looks like auth-server in staging hasn't been updated to v1.173.0 where this fix was landed:

➜  ~ date && curl https://api-accounts.stage.mozaws.net/__version__
Tue Jun  2 10:24:10 PDT 2020
{
  "version": "1.172.0",
  "commit": "3a6a83ac76b01f1d4d3f8ae92a4098b11e6a0bd8",
  "source": "https://github.com/mozilla/fxa"
}

**Closed** 2020-06-02 17:47 UTC
Labels: severity:major, status:bug

**Comment by ValentinaPC** [comment] 2020-06-03 07:19
Verified as fixed in stage, using Fx76 and Windows 10 (64-bit).
Postfix screenshot below.
![image](https://user-images.githubusercontent.com/15685960/83604132-55abb480-a57e-11ea-8bb9-6209f0acc360.png)
