### ISSUE TITLE
No subscription products images in subscription upgrade mail

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#5416] opened 2020-05-22 10:28 UTC
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.172.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Preconditions
- existent FxA account with active upgraded subscription;

#### Steps to reproduce
1. Go to subscription upgrade email.
2. Observe product images.

#### Expected result:
- The images are displayed.

#### Actual result:
- The images are not displayed.

![image](https://user-images.githubusercontent.com/15685960/82658674-1dc47900-9c30-11ea-816a-666dbc7f74af.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1956)
┆Issue Number: FXA-1956

**Comment by data-sync-user** [comment] 2020-05-22 19:00
➤ Wil Clouser commented:

Are you able to give us the URLs of the images its trying to load?

What email client are you using?

Please verify you are not blocking remote images in the email client

**Comment by ValentinaPC** [comment] 2020-05-25 11:40
> 
> 
> ➤ Wil Clouser commented:
> 
> Are you able to give us the URLs of the images its trying to load?
> 
> What email client are you using?
> 
> Please verify you are not blocking remote images in the email client

- I am not able to provide you the URLs of the images, but I can tell you that the 2 products used to upgrade are: "One, two, three Done...PRO" and "One, two, three Done...PRO PLUS" .
- I am using Thunderbird email client, but I've verified this using Gmail, also, and the results is the same.

**Note:** the product images are rendered as expected in browser, during subscription flow. See below screenshot.
![image](https://user-images.githubusercontent.com/15685960/82809780-8f513100-9e95-11ea-8a3d-e86a4269646c.png)

**Comment by clouserw** [comment] 2020-05-26 15:10
Would you forward the email to me please?  Thanks

**Comment by data-sync-user** [comment] 2020-05-26 16:38
➤ Les Orchard commented:

Looks like "One, Two, Three Done...PRO PLUS" in stage Stripe is missing `emailIconURL` from product metadata ( https://mozilla.github.io/ecosystem-platform/docs/fxa-engineering/fxa-sub-platform#product-metadata ). I just now copied the URL from the web icon, but we should ensure that's filled out in prod.

**Comment by data-sync-user** [comment] 2020-05-26 16:38
➤ Les Orchard commented:

The "One, Two, Three Done...PRO" product does have an `emailIconURL` in stage Stripe, so I'm not sure why the image on the left would be blank. Will take a look at the email code

**Comment by data-sync-user** [comment] 2020-05-26 17:10
➤ Les Orchard commented:

Can reproduce and think I found the issue - them mailer expects `productIconOld` / `productIconNew` while the event handling code is passing in `productIconURLNew` / `productIconURLOld`. Will have a fix shortly

**Comment by data-sync-user** [comment] 2020-05-26 18:31
➤ Les Orchard commented:

https://github.com/mozilla/fxa/pull/5442

**Comment by ValentinaPC** [comment] 2020-05-27 05:33
> 
> 
> Would you forward the email to me please? Thanks

Probably the email is too late, but, I've sent it anyway. :)

**Comment by ValentinaPC** [comment] 2020-06-02 07:23
Verified this in stage, using Fx76 and Windows 10 (64-bit).
Seems like the product pictures are still unavailable, via email.
See screenshot below.
![image](https://user-images.githubusercontent.com/15685960/83491776-f5a00a00-a4ba-11ea-9225-51f7f96a6c78.png)

**Comment by data-sync-user** [comment] 2020-06-02 17:35
➤ Les Orchard commented:

I can reproduce. However, it looks like auth-server in staging hasn't been updated to v1.173.0 where this fix was landed:

➜  ~ date && curl https://api-accounts.stage.mozaws.net/__version__
Tue Jun  2 10:24:10 PDT 2020
{
  "version": "1.172.0",
  "commit": "3a6a83ac76b01f1d4d3f8ae92a4098b11e6a0bd8",
  "source": "https://github.com/mozilla/fxa"
}

**Closed** 2020-06-02 17:48 UTC
Labels: severity:minor, status:bug

**Comment by ValentinaPC** [comment] 2020-06-03 06:28
Verified this in stage, using Fx76 and Windows 10 (64-bit).
The product images are displayed, my question is related to the first product image - "One, two, three Done...PRO" : is that ok, @lmorchard ? Thanks!
![image](https://user-images.githubusercontent.com/15685960/83603130-85f25380-a57c-11ea-95c0-5c028cf38ed3.png)
