### ISSUE TITLE
[email-service] allow X-Verify-Short-Code header to pass through

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#5423] opened 2020-05-22 17:47 UTC
X-Verify-Short-Code headers, used in automated tests, were not being passed through by the email-service (traced with ngrep and debug logging on fxa-email-service). They are removed in the email-service, I think because we whitelist `X-*` headers in the code below:

https://github.com/search?q=X-Verify-Code+repo%3Amozilla%2Ffxa+extension%3Ars&type=Code&ref=advsearch&l=&l=

There are possibly other headers that need to be added.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1963)
┆Issue Number: FXA-1963

**Comment by data-sync-user** [comment] 2020-05-22 19:09
➤ Wil Clouser commented:

Thanks.  This is likely a dupe of https://jira.mozilla.com/browse/FXA-1811 but has good context

**Comment by data-sync-user** [comment] 2020-05-26 20:35
➤ Wil Clouser commented:

Closing as a duplicate

**Closed by data-sync-user** 2020-05-26 20:35 UTC
