### ISSUE TITLE
Authorize this sign-in shows a full keyboard and not a numpad on Android

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#3525] opened 2019-11-28 19:45 UTC
Keyboard below can be digits only now right? or do we still need to support letters?

![image](https://user-images.githubusercontent.com/128755/69829357-a0263000-11ed-11ea-95c0-0008eae8c8b2.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-589)
┆Issue Number: FXA-589

**Comment by shane-tomlinson** [comment] 2019-11-29 11:41
https://github.com/mozilla/fxa/blob/50b7bcf1ff3a3f016c0552a5044965301f9e790c/packages/fxa-content-server/app/scripts/templates/sign_in_token_code.mustache#L18 - Caused by this commit: https://github.com/mozilla/fxa/commit/66892894a0a4aa5004f2aedfb1b7c1ae83379fbe

@vbudhram - how come we aren't using type=number there?

**Comment by data-sync-user** [comment] 2021-03-26 20:58
➤ Jared Hirsch commented:

Closing, the code is alphanumeric.

**Closed by data-sync-user** 2021-03-26 20:58 UTC
