### ISSUE TITLE
Wrong page is displayed if an error is received at subscription and we refresh the page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#6336] opened 2020-08-28 10:20 UTC
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.186.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Prerequisites:
- Have a FxA account with NO subscription;

#### Steps to reproduce:
1. Load the Mozilla VPN main page: https://stage-vpn.guardian.nonprod.cloudops.mozgcp.net/
2. Click on the “Try Mozilla VPN” button;
3. Complete all mandatory fields and use a card that returns an error at subscription i.e. “3566002020360505”
4. Click the “Pay Now” button;
5. After receiving the subscription error, refresh the page;

#### Expected result:
- All fields are empty,the user can re enter valid data.

#### Actual result:
- User is redirected to the “multiple product” subscription page;

#### Notes:
- Any product user wants to subscribe after, returns the same page;
- “Pay now” from multiple product subscription page is also not working and returning the same error as the initial classic subscription form.
![wrong page](https://user-images.githubusercontent.com/15685960/91550422-30d29d80-e931-11ea-9313-99d27ff347f2.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2494)
┆Issue Number: FXA-2494

**Comment by chenba** [comment] 2020-08-31 15:20
@ValentinaPC If you don't refresh the page after receiving the error, but enter a working card, are you able to subscribe successfully then?

**Comment by ValentinaPC** [comment] 2020-09-01 07:33
@chenba Tried your suggestion, and did not refreshed the page, and entered a working card. 
User was not redirected to the “multiple product” subscription page, but the error message was still displayed and user was not able to subscribe successfully.
I've used the card number mentioned in the issue STRs and "4242 4242 4242 4242" for the working card number.
![norefresh](https://user-images.githubusercontent.com/15685960/91819187-713a6000-ec3e-11ea-9434-5001dd3800c9.gif)

**Comment by chenba** [comment] 2020-09-01 14:43
The team agreed that we'd have the frontend send a request to remove the failed payment method when this occurs.

**Comment by data-sync-user** [comment] 2020-09-01 16:18
➤ Barry Chen commented:

There are really two problems: 1) the retry, and 2) the refresh.

The retry issue can be fixed on the frontend by ignoring an "existing" card on a customer that does not have any subscriptions.  I'll fix this first.

The refresh solution is the one in the previous comment.

**Comment by data-sync-user** [comment] 2020-09-01 19:13
➤ Barry Chen commented:

Turned out the retry issue also required a call to Stripe to pay the invoice.

**Comment by data-sync-user** [comment] 2020-09-01 21:58
➤ Barry Chen commented:

https://github.com/mozilla/fxa/pull/6353 ( https://github.com/mozilla/fxa/pull/6353 ) actually fixes both retry and refresh.

I'll create another patch to remove the payment method that's caused by failed card.  It's more a cleanup task, however, since it doesn't affect functionality.

**Closed** 2020-09-09 16:25 UTC
Labels: severity:normal, status:bug

**Comment by ValentinaPC** [comment] 2020-09-29 08:19
Verified as fixed in stage, using Fx81 and Windows 10 (64-bit).
Postfix video below.
![refresh111](https://user-images.githubusercontent.com/15685960/94531689-94f4c400-0245-11eb-9259-694fd443fe5a.gif)
