### ISSUE TITLE
Events Come in to Amplitude in the wrong order

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#3446] opened 2019-11-21 18:28 UTC
## Description

When doing funnel analysis, there's one platform that always have very different results from the others. That is Android. When looking at event streams, the events are often in the wrong order which means that we're not applying the right timestamps to them.

What sort of stumps me is why the heck Android is so much worse than all other platforms?
- Performance of devices?
- Performance of network connection?

Examples:
- `code submit` comes before `reg - submit`
https://analytics.amplitude.com/mozilla-corp/project/178231/search/amplitude_id%3D122936515458?sessionHandle=W6G81s3_W6G9%2FYS_ByflluC_rg3_8764f034957442f3ad3beba75e447bd0&eventId=741c642e-0b4a-11ea-a7a4-02903a7c935a
- `reg submit` comes after `reg created` 
https://analytics.amplitude.com/mozilla-corp/project/178231/search/amplitude_id%3D122936523522?sessionHandle=W6G%252BBQE_W6G%252BB80_ByflnsC_rg3_381d91d1af9c47ffaf20716ba89c2c68&eventId=52d8c376-0c16-11ea-8d65-06d9b9c89de0
- Same problem as last one, `reg submit` comes after `reg created` 
https://analytics.amplitude.com/mozilla-corp/project/178231/search/amplitude_id%3D122938958850?sessionHandle=W6HD4qK_W6HD8LV_Byfu6QC_rg3_c2123bd2584243898dc5ca14911da40d&eventId=b2dc2042-0b4e-11ea-b31e-069b3728d75a
- `reg submit` comes after `reg created` 
https://analytics.amplitude.com/mozilla-corp/project/178231/search/amplitude_id%3D123131388995?sessionHandle=W6Nn8Jb_W6Nn9A%2F_ByrM%252BRD_rg3_78847f1786704999a2ed78072b444c30&eventId=a153084e-0c4e-11ea-b986-025f9f11d14a

I feel like I might have reported this already but I can't find an open issue.

Potentially related?
https://github.com/mozilla/fxa/issues/3399

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-569)
┆Issue Number: FXA-569

**Comment by shane-tomlinson** [comment] 2019-11-22 10:12
I imagine most of the problem is that events come from different sources with different clocks. For example [reg created](https://github.com/mozilla/fxa/blob/1e9c309dcf7cd837acb8c082becced88150e8c75/packages/fxa-auth-server/lib/routes/account.js#L247) comes from the Auth server whereas [reg submit come from the content server front end, i.e., the user's device](https://github.com/mozilla/fxa/blob/1e9c309dcf7cd837acb8c082becced88150e8c75/packages/fxa-content-server/app/scripts/views/mixins/flow-events-mixin.js#L55). 

The time on auth server generated events are all based on the [clock on the auth-server](https://github.com/mozilla/fxa/blob/1e9c309dcf7cd837acb8c082becced88150e8c75/packages/fxa-auth-server/lib/metrics/context.js#L164), which is synchronized to the "real" time using NTP.

Content server generated events have a problem where the time is based on the clock of the user's device. Whenever dealing with millions of devices, the clocks on some subset of those devices is going to be skewed from the "real" time.  [We try to account for this by estimating a timestamp](https://github.com/mozilla/fxa/blob/1e9c309dcf7cd837acb8c082becced88150e8c75/packages/fxa-auth-server/lib/routes/account.js#L247) based on flowBeginTime returned by the content server. Since the content server is also synchronized to the "real" time using NTP, this means we are closer. 

*However*, network latency throws off this estimation, and this will be especially apparent on mobile devices with both slow networks and slow processors. flowBeginTime is set as soon as the page HTML is generated, if it takes, e.g., 3 to 10 seconds to download and parse the HTML and JS, this time is not accounted for in the estimation (simply because we don't know how to calculate that with any accuracy without making more network requests) and events appear 3 to 10 seconds in the future.

So if, e.g., there is 3 seconds of latency, we have this situation where we hit "submit", the way the time is estimated makes it appear that the event occurs 3 seconds in the future. The "created" event, which is created on the auth server, appears to occur right now. And events show up in Amplitude out of order.

**Comment by data-sync-user** [comment] 2021-03-26 20:48
➤ Jared Hirsch commented:

Closing this for now

**Closed by data-sync-user** 2021-03-26 20:48 UTC
