### ISSUE TITLE
[auth server] Ditch bluebird

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#2323] opened 2019-08-27 09:01 UTC
After it cropped up in conversation during @lmorchard's async/await workshop, I spent the day on Friday experimenting with what it would take to remove bluebird from the auth server and `fxa-shared`. This issue is to record what I learned, so I can move on to more important stuff.

The following non-standard static `Promise` methods are used across `fxa-auth-server` and `fxa-shared`:

* `Promise.defer`
* `Promise.delay`
* `Promise.each`
* `Promise.mapSeries`
* `Promise.method`
* `Promise.promisify`
* `Promise.promisifyAll`
* `Promise.props`
* `Promise.using` (in combination with the instance method `.disposer`)

They're all pretty straightforward to shim (or at least, they should be).

There's a shim implementation of the bluebird API with native promises in npm, [`bluebird-api`](https://www.npmjs.com/package/bluebird-api). I tried using it and a direct swap is not possible in our codebase, because the behaviour of `Promise.using` is different between the two. Actual bluebird passes the respective resource to each disposer function whereas the shim doesn't. I tried to work around that by caching the resource in a closure that but the tests were still failing, so maybe there are other differences too. I pushed my work-in-progress to the [`pb/ditch-bluebird` branch](https://github.com/mozilla/fxa/compare/pb/ditch-bluebird?expand=1). If we're going to persevere with this approach, we'll probably want to open PRs against  `bluebird-api` to fix any compatibility issues.

I also spent a bit of time just implementing our own shims for the subset of functionality we actually use. It's not very much code so the maintenance burden should be fairly low, but I still didn't get the tests all passing there so maybe I don't know what I'm talking about. I pushed my work-in-progress to the [`pb/ditch-bluebird-wip` branch](https://github.com/mozilla/fxa/compare/pb/ditch-bluebird-wip?expand=1).

**Comment by clouserw** [comment] 2019-08-30 15:51
marking as duplicate of #482.  Please add comments there, thanks!

**Closed by clouserw** 2019-08-30 15:51 UTC
