### ISSUE TITLE
Multiple copies of FPN appear when I click "Delete"

### ISSUE THREAD

**Issue by arthur-mozilla** [mozilla/fxa#2450] opened 2019-09-10 11:23 UTC
<img width="721" alt="image" src="https://user-images.githubusercontent.com/48572191/64609794-8f021b80-d382-11e9-950a-51c0b6919adc.png">

**Comment by clouserw** [comment] 2019-09-13 15:34
This might be caused by installing FPN over and over (different versions, etc.).  But definitely something buggy here.

**Comment by clouserw** [comment] 2019-09-16 16:23
Also note #1802

**Comment by clouserw** [comment] 2019-09-16 16:24
@LZoog is this something that you were working on?  We can't find the duplicate we thought either so we might be imagining things

**Comment by lmorchard** [comment] 2019-09-16 16:29
Also related to #2256 and #2019? (I think these were the issues I was thinking might be related / duplicate)

**Comment by rfk** [comment] 2019-09-16 20:10
> Also related to #2256 and #2019?

Similar to, but FPN is an OAuth RP so these are refresh tokens. We should consider applying similar "roll up all tokens with the same name into a single entry" for refresh tokens as we currently do for session tokens on the deletion screen.

**Comment by rfk** [comment] 2019-12-02 20:13
This should be fixed as of 445f18aa086fdb762cc86922ac9ee01c8617f234, please re-open if it's still occurring.

**Closed by rfk** 2019-12-02 20:13 UTC
