### ISSUE TITLE
[FxA-Settings] Suggest time limit for notifications to display

### ISSUE THREAD

**Issue by rbillings** [mozilla/fxa#7487] opened 2021-02-09 20:29 UTC
## Description

Auto close notifications after _n_ seconds? I just realize i’ve had a floating “Two-step authentication enabled” notification hovering at the top of my screen for about 5 minutes as I [poorly] multitask.

Submitted by: pdehaan

### Steps to reproduce

Clear steps describing how to reproduce the issue. Providing a URL, screenshot.

### Expected result

Notification disappears after set amount of time

### Actual result

<img width="312" alt="Screen Shot 2021-02-09 at 12 27 24 PM" src="https://user-images.githubusercontent.com/737878/107424319-5bc14000-6ad2-11eb-889a-8573ddfbf80f.png">

### Environment

macOS

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3026)
┆Issue Number: FXA-3026

**Comment by vasilicatamas** [comment] 2021-02-10 15:38
This issue is a dupe of [#7029](https://github.com/mozilla/fxa/issues/7029)

**Closed** 2021-02-10 15:46 UTC
Labels: status:duplicate
