### ISSUE TITLE
[FxA-Settings] Connected services has only one icon type

### ISSUE THREAD

**Issue by rbillings** [mozilla/fxa#7480] opened 2021-02-09 19:59 UTC
## Description

All my Connected Services icons are the same (wireframe globe).
Submitted by: pdehaan

### Steps to reproduce

- Manage account
- Connected Services

### Expected result

Different icons for different services

### Actual result

Connected services uses only one icon for all services

### Environment

macOS

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3018)
┆Issue Number: FXA-3018

**Comment by rbillings** [comment] 2021-02-09 20:14
I was not able to reproduce this- so it may have been fixed since the original report.

**Comment by vasilicatamas** [comment] 2021-02-10 15:18
This issue is a dupe of #7251

**Closed** 2021-02-10 15:47 UTC
Labels: status:duplicate
