### ISSUE TITLE
Change billing confirmation is weird

### ISSUE THREAD

**Issue by juliastarkov** [mozilla/fxa#3342] opened 2019-11-12 23:34 UTC
## Description

The visual/interaction of the notification is off. The purple bar should be the width of the white card below it; it is too wide now. We also added an X (to close) specifically because we didn't want it to auto-disappear. If we chose to do this, we should remove the X. 

### Steps to reproduce

Changing the billing information will reproduce the issue. 

<img width="1201" alt="Screen Shot 2019-11-12 at 3 27 05 PM" src="https://user-images.githubusercontent.com/26334275/68719747-d31bc300-0561-11ea-9ba3-567357a39d67.png">

### Expected result

A purple "pill" shaped bar that is the width of the white area and that does not disappear in a couple of seconds, as seen in the mockup below. 

<img width="721" alt="Screen Shot 2019-11-12 at 3 34 16 PM" src="https://user-images.githubusercontent.com/26334275/68719781-eaf34700-0561-11ea-967e-abe6b56058cd.png">

### Environment

Firefox Release on Mac.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-539)
┆Issue Number: FXA-539

**Comment by data-sync-user** [comment] 2021-03-26 20:33
➤ Jared Hirsch commented:

[~bchen@mozilla.com]Have you worked on this issue recently, possibly?

**Comment by data-sync-user** [comment] 2021-03-29 14:39
➤ Barry Chen commented:

I'm marking this as a duplicate of FXA-3225.  There's a PR currently open to update the width of that alert bar.  And the overall UX will be changing soon.

**Closed by data-sync-user** 2021-03-29 14:39 UTC
Labels: maybemaybemaybe
