### ISSUE TITLE
Password strength bubbles can overlap each other

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#3055] opened 2019-10-21 23:33 UTC
Description:
It is possible to have both password bubble appear at the same time, overlapping each other.

Steps to reproduce:
- in the first password field, enter a valid password
- wait for the bubble to disappear
- delete some of the password to have less than 8 characters (making it invalid)
- tab to the second password field

Expected results:
- the password bubble should have re-appeared faster on the first field and not only when focus is on the second field.
- don't show both bubbles at the same time. Prioritize the first one.

Actual result:
- we wait until the tab to re-validate the password if all conditions were met once
![Screen Shot 2019-10-21 at 4.29.27 PM.png](https://images.zenhubusercontent.com/5ca2448cb4170956617cd475/83b4f447-d86b-45f3-85bd-0ac39c252382)
- we display both bubbles one on top of each other
![Screen Shot 2019-10-21 at 4.23.27 PM.png](https://images.zenhubusercontent.com/5ca2448cb4170956617cd475/413eb854-1697-49d9-89a9-311220786504)

**Comment by davismtl** [comment] 2019-10-21 23:33
CC @ryanfeeley since you detected this first

**Comment by chenba** [comment] 2019-11-22 19:41
I cannot reproduce this.

**Comment by chenba** [comment] 2019-11-22 19:49
Found and filed a related issue: https://github.com/mozilla/fxa/issues/3465

**Comment by chenba** [comment] 2019-12-06 15:42
Closing this since I cannot reproduce it.

**Closed by chenba** 2019-12-06 15:42 UTC
Labels: P3, cat:growth, cat:ux
