### ISSUE TITLE
[FxA-Settings] "Generate a new recovery key" option redirects to the old Settings page

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#7815] opened 2021-03-15 09:40 UTC
**Build**
Stage [Train 1.202.1]

**Affected platforms**
Windows 10
macOS 10.14.6

**Prerequisites:**
The user has enabled a recovery key

**Steps to reproduce**

1. Go to Sign In Page and click on the "Forgot password?".
1. Insert the email and click on the "Begin reset".
1. Go to email and click on the "Create new password".
1. Insert the recovery key and click on the "Confirm recovery key".
1. Complete the fields with the new password and click on the "Change" button.
1. Click on the "Generate a new recovery key".

**Expected results**
The Recovery key section from New Settings page is successfully displayed.

**Actual Results**
The user is redirected to the old Settings page.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3180)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15455/gif25.gif">gif25.gif</a> | <a href="https://jira.mozilla.com/secure/attachment/15549/Screen+Shot+2021-03-16+at+10.11.08+AM.png">Screen Shot 2021-03-16 at 10.11.08 AM.png</a>
┆Issue Number: FXA-3180

**Comment by data-sync-user** [comment] 2021-03-16 16:30
➤ Wil Clouser commented:

[~rbillings@mozilla.com] - are you able to reproduce this?  We think it might have been a caching issue as we haven't reproduced.

**Comment by data-sync-user** [comment] 2021-03-16 17:12
➤ Rebecca Billings commented:

I was able to reproduce this on staging following the steps above. !Screen Shot 2021-03-16 at 10.11.08 AM.png!

**Comment by data-sync-user** [comment] 2021-03-16 17:41
➤ Rebecca Billings commented:

Doing a bit more research I discovered that I get different flows that may or may not relate to this bug.

1) Steps:

  1. Set up recovery key
  2. Sign out using the FxA toolbar > Account Settings > Sign Out
  3. Forgot password
  4. Receive email, click Create New Password link
  5. Insert the recovery key and click on the "Confirm recovery key".
  6. Complete the fields with the new password and click on the "Change" button.
  7. Click on the "Generate a new recovery key".

Result: This will serve the old Settings page

2) Steps:

  * Set up recovery key
  * Sign out using the Settings page profile icon > Sign Out 
  * Forgot password
  * Receive email, click Create New Password link
  * Insert the recovery key and click on the "Confirm recovery key".
  * Complete the fields with the new password and click on the "Change" button.

Result: This takes the user directly to the new Account Settings page with no modal offering to generate a new recovery key. [but you can create one as usual within Account Settings]

**Comment by data-sync-user** [comment] 2021-03-17 15:28
➤ Wil Clouser commented:

Thanks Rebecca for the detailed steps.

**Comment by 6a68** [comment] 2021-03-19 16:29
@rbillings I can't reproduce flow #1 above, either locally or on staging, but I can reproduce flow #2. Maybe we should close this issue and open a new issue for flow #2 not ending with an offer to create a new recovery key?

**Comment by 6a68** [comment] 2021-03-19 16:43
We chatted about this on slack.

The flow needs to start by signing out from the browser:

<img width="336" alt="Screen Shot 2021-03-19 at 9 42 17 AM" src="https://user-images.githubusercontent.com/96396/111814186-69b76d00-8897-11eb-9712-83f9baa7fa8c.png">

And after creating a password, the user winds up at `/reset_password_with_recovery_key_verified` with `service=sync` in the params:

<img width="465" alt="Screen Shot 2021-03-19 at 9 43 21 AM" src="https://user-images.githubusercontent.com/96396/111814314-8fdd0d00-8897-11eb-86f8-50cc2a556672.png">

**Closed** 2021-03-19 18:44 UTC
Labels: severity:normal

**Comment by data-sync-user** [comment] 2021-03-30 12:20
➤ Vasilica Tamas commented:

This issue is verified as fixed on Stage [Train 1.203.2] under Windows 10 64-bit. "Generate a new recovery key" button successfully redirects to the 'Recovery key -Step 1 of 2" screen from the New Settings page.
