### ISSUE TITLE
No card icon displayed when entering a card number

### ISSUE THREAD

**Issue by bsurd** [mozilla/fxa#2197] opened 2019-08-14 09:14 UTC
#### Affected versions:
- All Firefox 

#### Affected Platforms:
- All Windows

#### Steps to reproduce
1. Go to [123done](https://123done-stage.dev.lcip.org/).
2. Sign in/up with an account.
3. Click on "Subscribe to Pro".
4. Enter the following card number: 5200 8282 8282 8210

#### Expected result:
A Mastercard icon is displayed in the card number field.

#### Actual result:
No card icon is displayed.

#### Notes:
Tested on the Stripe website and it would seem they have/support this functionality.

**Stripe:**
![image](https://user-images.githubusercontent.com/17178945/63009118-8bb36700-be8c-11e9-8564-cf98ee374062.png)

**Mozilla:**
![image](https://user-images.githubusercontent.com/17178945/63009331-f49adf00-be8c-11e9-9e71-f4d854600341.png)

**Comment by lmorchard** [comment] 2019-08-14 16:55
Duplicate of issue #1842 - FWIW, the example on the stripe website is using different components than we're using on our payment pages, so it's a non-trivial fix

**Closed by lmorchard** 2019-08-14 16:55 UTC
Labels: [QA]:Enhancement, status:enhancement
