### ISSUE TITLE
Reopening the same deep-link from your SMS doesn't autofill the email

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla/fxa#860] opened 2019-04-17 12:29 UTC
Device: Huawei P9 Lite (Android 6.0);
Build: Firefox Release 66.0.2;

Prerequisites:
Send an install link from your desktop log-in flow.

Steps to reproduce:
1. Open the received SMS;
2. Open the link using Firefox;
3. Close the app and reopen the same link from SMS;

Expected results:
The email is still pre-filled.

Actual results:
The email is not pre-filled.

Notes:
- [video](https://drive.google.com/file/d/0B-OVCGyglYi_QU5IS21LTktGM3pNNzJQWDcxYnpYUXgtV0lN/view?usp=sharing)

**Comment by shane-tomlinson** [comment] 2019-04-17 13:30
This is the intended behavior to prevent the links from being replayed elsewhere. We could change the behavior for the link to be valid for a given amount of time rather than a single use, though I'm not sure it's worth the effort.

**Comment by shane-tomlinson** [comment] 2019-04-17 13:31
tentatively labeling wontfix, if anyone has a strong objection we can re-open it.

**Closed by shane-tomlinson** 2019-04-17 13:31 UTC
Labels: status:wontfix
