### ISSUE TITLE
Firefox Accounts won't forget my old email address

### ISSUE THREAD

**Issue by anewuser** [mozilla/fxa#13947] opened 2022-08-15 17:45 UTC
I've changed the email I use with my Firefox account a long time ago. The account settings page and [my AMO profile](https://addons.mozilla.org/user/15134295/) show only my current address as the primary email and **no** secondary email.

The login page kept showing my old address for months, but it now finally displays only the correct address.

However, when I logged in to Mozilla Connect for the first time, I was surprised to see my old address again on [my profile page there](https://connect.mozilla.org/t5/user/viewprofilepage/user-id/8315). I manually changed it to my new address, but every time I open Mozilla Connect, it gets changed back to the old address again.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5753)

**Comment by clouserw** [comment] 2022-08-16 17:32
Hi @anewuser .  Thanks for filing this and sorry for the troubles.  It sounds like your correct address is showing everywhere except Mozilla Connect.  I'll reach out to that team and ask them to look into this.

**Comment by anewuser** [comment] 2022-08-16 18:04
Thank you for the reply. Please bring these other issues to their attention too:

* Proton Mail users see this warning in the Mozilla Connect confirmation email: https://proton.me/support/email-has-failed-its-domains-authentication-requirements-warning
* When I created my Mozilla Connect account, it was set to an American time zone by default instead of my local time zone. The site could detect the user's correct time automatically or ask him/her to select it

**Comment by clouserw** [comment] 2022-08-16 18:28
What email did you see that warning on?  I'd like to know more about what check is failing if there are any more details.

**Comment by anewuser** [comment] 2022-08-16 19:04
This happens with emails from `community@connect.mozilla.com`. [Another user has reported the same issue](https://connect.mozilla.org/t5/discussions/protonmail-does-not-recognize-any-email-from-lt-community/m-p/12143).

To reproduce it and see the full email headers, [open your Mozilla Connect settings](https://connect.mozilla.org/t5/user/myprofilepage/tab/personal-profile) and change your email to a [Proton Mail](https://mail.proton.me/u/0/inbox) address (you can create a free account in under a minute).

**Comment by clouserw** [comment] 2022-08-18 20:44
Got ya.  

I talked to the team responsible for connect.m.c and it sounds like there is a 3rd party doing the engineering there and we've opened a support ticket with them.  That ticket isn't publicly visible though and I don't have a link I can redirect you to.  

However, this isn't an FxA issue so I'm going to close this and I'm sorry I can't send you a link to next steps.  If I hear any more from the connect.m.c team I'll comment here.

**Closed by clouserw** 2022-08-18 20:44 UTC

**Comment by clouserw** [comment] 2024-06-21 12:51
@anewuser Hi.  Sorry to hear that.  I've asked them to look at it again and they are asking for your username on connect so they can investigate.  If you're not comfortable putting it here my email is my username at mozilla.com.  Thanks

**Comment by anewuser** [comment] 2025-03-23 02:23
@clouserw 

My old email address also appears on these pages:

* https://www.mozilla.org/newsletter/existing/?fxa=1 
* https://discourse.mozilla.org/signup - it displays both my name and old email while creating a new account

**Comment by clouserw** [comment] 2025-03-24 15:39
Maybe it's your browser filling in the fields with what you normally type?  if you go to accounts.firefox.com/clear it will delete all cookies, sessions, and local storage for accounts if you want to try it.  support@mozilla.com might be able to help further.

**Comment by anewuser** [comment] 2025-03-25 05:25
My old email is still **on your servers** even though I deleted it from my profile many years ago.  I'm not the only one affected by this: [Bug 1864189](https://bugzilla.mozilla.org/show_bug.cgi?id=1864189).

You originally believed this was a Mozilla Connect specific issue, but other Mozilla websites show the old address and name too:

![Image](https://github.com/user-attachments/assets/d1248807-b92b-4142-a64c-928209476b53)

![Image](https://github.com/user-attachments/assets/7187e24e-a955-4dcc-8f06-54025e88e89c)

**Comment by clouserw** [comment] 2025-03-25 14:56
Thanks for the screenshots.  That really helps to clarify what the problem is.  I'll send those teams a link to this discussion.

**Comment by clouserw** [comment] 2025-03-25 16:03
Please CC yourself on https://bugzilla.mozilla.org/show_bug.cgi?id=1933278 for the newsletter one.  It's an active bug that the newsletter team needs to fix.

**Comment by anewuser** [comment] 2025-04-13 13:16
I don't think the Mozilla Connect, Newsletters, or Discourse teams can do anything about it. They're all getting my old email address from the centralized Mozilla Accounts system.

I've never signed up to receive any newsletter, and had already changed my email address before opening Mozilla Connect for the first time.

**Comment by clouserw** [comment] 2025-04-14 14:13
If you'd like to send me your email (I'm clouserw at mozilla.com) I can check if your account has any other emails associated with it.

**Comment by RokeJulianLockhart** [comment] 2025-05-09 13:19
> https://github.com/mozilla/fxa/issues/13947#issuecomment-2866500847

Likewise, @clouserw, are you willing to add yourself to assist? I've been asked to ask you.
