### ISSUE TITLE
Problem loading customer error displayed when trying to create a subscription

### ISSUE THREAD

**Issue by madalincm** [mozilla/fxa#4450] opened 2020-03-06 09:02 UTC
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Windows 10 (64-bit)

#### Preconditions
- existent FxA account with no subscriptions

#### Steps to reproduce
1. Open the [stage website](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn)
2. Click on the Subscribe now button and complete the subscription process.

#### Expected result:
- The payment is completed the user is redirected to the survey page.

#### Actual result:
- An error is displayed

![image](https://user-images.githubusercontent.com/15685441/76068443-d36d1d80-5f99-11ea-91f6-8499b093f18c.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1310)
┆Issue Number: FXA-1310

**Comment by jrgm** [comment] 2020-03-06 09:12
From https://bugzilla.mozilla.org/show_bug.cgi?id=1620435

> We have tried creating a new subscription in stage and we have encountered this issue: https://github.com/mozilla/fxa/issues/4450
@John Morrison is this related to https://github.com/mozilla/fxa/issues/4449?

Yes. Same UI and I checked the logs, same log message with stack trace.

**Comment by jrgm** [comment] 2020-03-06 09:13
I was going to close as a duplicate, but, changed my mind. It's the same bug, but close when re-tested.

**Comment by jrgm** [comment] 2020-03-06 09:26
Actually, same stack, but on a different route (/v1/oauth/subscriptions/customer in this STR).

But same root cause on validation.

**Comment by bbangert** [comment] 2020-03-06 17:38
Duplicate of #4449, which was closed.

**Closed by bbangert** 2020-03-06 17:38 UTC
Labels: severity:blocker, status:bug

**Comment by madalincm** [comment] 2020-03-09 12:17
I have retested stage today and the issue is no longer reproducing. Marking issue as verified fixed.
