### ISSUE TITLE
Confused FxA State if Signed in on First Run Page

### ISSUE THREAD

**Issue by juliemccracken** [mozilla/fxa#258] opened 2017-07-27 17:48 UTC
While signed into my Firefox Account in Nightly, I visited the new first run page. The fact that I was already logged in to my Firefox Account was not detected. 
1. I was prompted to sign in.
2. I entered my password to sign in and was prompted to confirm
3. It confirmed that I had a new sign in
4. I got the confirmation in the browser. 

For screen shots: 
https://docs.google.com/document/d/1cEV87Gi13-vy1MTb_N731tcxRAlSNCnzzMQmrj4rkqQ/edit

**Comment by ryanfeeley** [comment] 2017-07-27 20:15
Ohhh, I think I see the problem. At first I didn't think this was a big deal because only we would ever that URL after the fact. But I see the criticial problem. Let's me be pedantic and rewrite this.

STEPS TO REPRODUCE
1. Be signed in to Sync and visit the first run page

EXPECTED RESULTS
1. In the iframe, user is signed in to Settings

ACTUAL RESULTS
1. Sign-in screen with existing username and avatar is presented
2. Upon sign-in submission, user is signed of of Sync in their browser and asked to confirm sign-in

**Comment by rfk** [comment] 2017-07-27 22:17
Direct link to first-run page, for helping to reproduce: https://www.mozilla.org/en-US/firefox/54.0/firstrun/

**Comment by rfk** [comment] 2017-07-27 22:32
I'm able to reproduce this in release firefox, Julie reports she was it on nightly.  Basic steps are as described:

* Sign in to sync
* Visit https://www.mozilla.org/en-US/firefox/54.0/firstrun/

Result:
<img width="315" alt="capture" src="https://user-images.githubusercontent.com/34695/28694600-03cb32ca-736e-11e7-87c3-1ff8983e3f58.PNG">

It clearly knows that I'm signed in, because it's able to access my profile picture.  It's just re-prompting me for my password because it thinks I want to do a new signin rather than using the existing login state.

I expect this is simply a result of the frame explicitly requesting "https://accounts.firefox.com/signin?service=sync".  The frame is asking us for the sign-in page, so we're showing the sign-in page.

What URL was the iframe displaying in previous iterations, was it "https://accounts.firefox.com/?service=sync"?  Hitting that URL when you're signed in to the browser will display the settings page rather than a sign-in form as described in "expected results".

So I feel like the fact this this is in the first-run page is a bit of a red herring, and the real question is: if I visit https://accounts.firefox.com/signin?service=sync in a browser that's already signed in to sync, what should happen?

**Comment by timdream** [comment] 2017-08-01 09:41
[Bug 1386184](https://bugzilla.mozilla.org/show_bug.cgi?id=1386184) is filed to track the same thing, as this will be more visible once profile refresh is implemented.

**Comment by timdream** [comment] 2017-08-02 09:29
@rfk The question Verdi asked was that whether or not Firefox sync marked as "logged in" in the refreshed profile actually works when the user see that login page. I assume it does? If so this is not really a blocker to bug 1386184; we can go ahead asks mozilla.org to hide the login page from firstrun.

**Comment by rfk** [comment] 2017-08-05 01:41
I believe that the browser will still be logged in and syncing correctly in this, unless we can repro a case whre browser gets disconnected?  I think hiding the login page will be fine.

**Comment by timdream** [comment] 2017-08-05 01:43
👍🏻
-- 
(Apologies — sent from mobile)

**Comment by rfk** [comment] 2017-08-07 22:35
IIUC we don't plan to change anything here, the first-run experience will be updated to avoid showing the form if the user is already logged in.  Closing this bug, but please re-open or file a new one if there's some change required on the FxA side.

**Comment by Verdi** [comment] 2017-08-30 16:46
This issue just happened to me without going through the /firstrun page.

- Opened computer that I have not used in a while with Nightly on it - signed into sync.
- I refreshed nightly (via about:support). 
- Then and hour later I noticed that it didn't say I was signed into sync in the hamburger menu. Clicked on that and it takes me to options where it says I am signed in.
- Then a few seconds later a tab opens for an add-on I installed on another computer (which I guess know just got synced over).

It appears that after a refresh, sync isn't working until you visit the sync preferences. If that is really the case, then it seems like our plan to just skip the sign in form on the /firstrun page for auto-refreshed users will fail to have sync working for those that were previously signed in. This is a issue for 57 because we're going to run a good deal of people though that flow.

**Comment by davismtl** [comment] 2017-10-18 20:58
@ryanfeeley I would like to call out that this is still an issue. I can reproduce it. If a user sees firstrun page, they are asked to sign in. If they do but don't confirm their email, the browser becomes in a Yellow state and is no longer syncing even though it was before.

> So I feel like the fact that this is in the first-run page is a bit of a red herring, and the real question is: if I visit https://accounts.firefox.com/signin?service=sync in a browser that's already signed in to sync, what should happen?

I think we should send to Settings.

Question is, how many people are running into this? Probably more than we'd like. Unless users close tab after registration, there is a good chance they run into it.

**Comment by ryanfeeley** [comment] 2017-10-18 21:01
At first I thought that this page was only shown to users without existing profiles NOR active sync sessions.

If they are already signed in to Sync, we should simply auto-trigger the "Skip this step" because anything else is confusing. Users might be signed in, but forget their password.

I'm not sure what the engineering solution is though. @rfk ideas?

**Comment by rfk** [comment] 2017-10-18 22:39
> Unless users close tab after registration, there is a good chance they run into it.

I don't understand why this means there's a good chance they run into it, do we expect them to reload the /firstrun tab after registration?

> > if I visit https://accounts.firefox.com/signin?service=sync in a browser that's already signed in to
> > sync, what should happen?
> I think we should send to Settings.

@davismtl do you consider this a blocker for the 57 release, and we should drop something else from train-99 to pick it up?

**Comment by davismtl** [comment] 2017-10-18 23:35
Let me re-go through the flows and double check the experiences.

**Comment by rfk** [comment] 2017-10-19 02:33
> if I visit https://accounts.firefox.com/signin?service=sync in a browser that's already signed in to
> sync, what should happen?

Another possibility here, is that we still show the "signin" screen as requested, but we find a way to ensure that you get a verified login session rather than having to go back through the sign-in confirmation loop.  This would avoid us having to guess at what the user's intention is, while avoiding the problem where they wind up disconnected from sync.

**Comment by shane-tomlinson** [comment] 2017-10-19 09:15
I'm going to be contrarian, all of this sounds like too much work. We already have what they need to make the correct, smart decision. 

Firstrun should send users to `/` and specify `action=signin` if they want unauthenticated users to to go /signin, `action=signup` will send unauthenticated users to `/signup`. Authenticated users will be sent to /settings in either case.

In either case, sending users directly to /signin or /signup should not be done unless we know for certain the user should be doing that action.

**Comment by davismtl** [comment] 2017-10-19 17:26
While I totally understand and agree that they should send users to the right place (and we can ask them to fix that), it still sounds to me like like they should know better than us if a user is signed in and almost a excuse for not handling the user's state properly. 

At a minimum, 
1) we should not ask them to verify their email when they are already in a verified state. 
2) we should not be causing the browser to disconnect from Sync.
3) we should not put the full responsibility of handling users states in the hands of other teams. I don't like it.

Anyways... let's leave things as they are for now since few users will run into this with the current automatic redirect. More importantly, nobody will be making any big changes before 57 but I think this needs to be revisited.

**Comment by rfk** [comment] 2017-10-19 19:30
I'm going to re-open this so that we don't lose track of it.  In the meantime, if we do decide that something needs to change here for 57, by far the safest option will be this:

> Firstrun should send users to / and specify action=signin

**Comment by rfk** [comment] 2017-10-19 19:32
> almost a excuse for not handling the user's state properly

It's not that we don't know the user's state, it's that we're being told misleading things about the user's intention.  Any bigger change we want to make here will need to be thought about more holistically than just the first-run experience.

**Comment by shane-tomlinson** [comment] 2017-10-20 05:24
> 1. we should not ask them to verify their email when they are already in a verified state.
> 2. we should not be causing the browser to disconnect from Sync.
> 3. we should not put the full responsibility of handling users states in the hands of other teams. I don't like it.

I'm a bit confused... All 3 of these are taken care of if the firstrun team stops sending users to `/signin` directly and instead send users to `/?action=signin` 3 is what happens if the firstrun team opens `/?action=signin` - we make the choice based on the knowledge we have. 1 and 2 happen as a result of that knowledge - we won't ask the user to sign in if they are already signed in, and because of that, we won't disconnect the user from Sync.

**Comment by rfk** [comment] 2017-10-20 05:29
From backchannel in slack, IIUC Alex was worried there might be other flows that could also lead users to /signin and have this unintended behaviour, and/or that other such flows might pop up in future without us knowing about it.

Also to be clear, the answer to this:

> do you consider this a blocker for the 57 release, and we should drop something else
> from train-99 to pick it up?

Was a "no, but we might want to change behaviour here long term".

**Comment by vbudhram** [comment] 2017-12-15 17:07
from mtg: this should be fixed now

**Closed by vbudhram** 2017-12-15 17:07 UTC
Labels: waffle:backlog
