### ISSUE TITLE
[fxa-event-broker] TypeError: query.select is not a function

### ISSUE THREAD

**Issue by Zirak** [mozilla/fxa#1586] opened 2019-06-15 12:30 UTC
Hello!

Running from master, `event-broker` exited with status 1. After some debugging, it all came down to [this line](https://github.com/mozilla/fxa/blob/90d4bf753385536dfb396262e172c9ef4c95f2f8/packages/fxa-event-broker/lib/db/firestore.ts#L48) (below is the compiled js):

```js
    fetchClientIdWebhooks() {
        return __awaiter(this, void 0, void 0, function* () {
            const query = this.db.collection('clients');
            const results = yield query.select('webhookUrl').get(); // <----
            const clientWebhooks = {};
            results.docs.forEach(doc => {
                clientWebhooks[doc.id] = doc.get('webhookUrl');
            });
            return clientWebhooks;
        });
    }
```

The [firestore documentation](https://firebase.google.com/docs/reference/js/firebase.firestore.CollectionReference.html) also doesn't mention any `select` method. Perhaps the intention was to use [`where`](https://firebase.google.com/docs/reference/js/firebase.firestore.CollectionReference.html#where)?

Am I perhaps looking at the wrong package/documentation, or is it maybe a versioning thing? `npm ls` shows `@google-cloud/firestore@2.0.0`.
Thanks!

**Comment by bbangert** [comment] 2019-06-20 20:25
The Collection Reference inherits all the methods of Query, per the doc link you cited:
```
A CollectionReference object can be used for adding documents, getting document references, and querying for documents (using the methods inherited from Query).
```

select is a Query method, though I have seen the error you mention in some cases. The tests and using this code in a full integration test also works. Is there more to the error you got?

**Comment by bbangert** [comment] 2019-06-20 20:33
The link there is actually somewhat inaccurate, as its to the client-side Javascript library. There's a separate doc link to the Node.js Firestore library, where it claims the CollectionRef inherits from Query, which has a select method. However Google apparently has messed up their docs and I can't even get to them right now.

This does work correctly against the Firestore emulator and actual Firestore in tests though. How are you triggering the error?

**Comment by bbangert** [comment] 2019-06-21 20:20
I did find the doc, in my history (their sidebar doesn't seem to work right for me), here's the select method on the CollectionRef:
https://cloud.google.com/nodejs/docs/reference/firestore/1.3.x/CollectionReference#select

**Comment by Zirak** [comment] 2019-06-22 00:09
Thanks for the clarification on the firestore version. I've triggered the error by plainly cloning the main fxa repo and debugging why `event-broker` seemed to be failing to start.

Manually, I made sure the firestore emulator is up:

```
$ ss -antopl | grep 8006
LISTEN0      128                                          *:8006              *:*                    users:(("docker-proxy",pid=1081,fd=4))
$ docker ps
30379319e0f0        jdlk7/firestore-emulator    "gcloud beta emulato…"   2 minutes ago       Up 2 minutes        0.0.0.0:8006->9090/tcp     firestore
```

Running the event broker:

```
$ pwd
/path/to/fxa/packages/fxa-event-broker
$ npm run start-dev
> fxa-event-broker@1.137.1 start-dev /home/me/ff/fxa/packages/fxa-event-broker
> npm run build && NODE_ENV=development PUBSUB_EMULATOR_HOST=localhost:8005 FIRESTORE_EMULATOR_HOST=localhost:8006 node ./dist/bin/workerDev.js


> fxa-event-broker@1.137.1 build /home/me/ff/fxa/packages/fxa-event-broker
> ./node_modules/typescript/bin/tsc

fxa-event-broker.notificationProcessor.INFO: startup {"message":"Starting event broker..."}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fxa-event-broker@1.137.1 start-dev: `npm run build && NODE_ENV=development PUBSUB_EMULATOR_HOST=localhost:8005 FIRESTORE_EMULATOR_HOST=localhost:8006 node ./dist/bin/workerDev.js`
npm ERR! Exit status 1
[...snip...]
```

And debugging from there.

After digging around some more, it looks like there's a mismatch between google's firestore API and the `@firebase/firestore` one. Here's an excerpt from `/path/to/fxa/packages/fxa-event-broker/node_modules/@firebase/firestore/dist/src/api/database.d.ts`:

```ts
export declare class Query implements firestore.Query {
    _query: InternalQuery;
    readonly firestore: Firestore;
    constructor(_query: InternalQuery, firestore: Firestore);
    where(field: string | ExternalFieldPath, opStr: firestore.WhereFilterOp, value: unknown): firestore.Query;
    orderBy(field: string | ExternalFieldPath, directionStr?: firestore.OrderByDirection): firestore.Query;
    // [...snip...]
```

When running `start-dev`, the `FirestoreDatastore` is constructed twice, once not given a firestore which initialises google's version, and second time it's given the result of `firebase.initializeTestApp` which uses `@firebase/testing` and thus the firebase version, which lacks the `select`.

Is this something that maybe should be filed against firebase's firestore API? I'm not familiar with it, so maybe API parity with google's firestore isn't a goal of theirs.

**Comment by bbangert** [comment] 2019-06-24 19:50
It appears that an issue was filed for this, then closed as it was missing a reproduction test case. Which is somewhat odd, it's pretty obvious its missing this method.

https://github.com/firebase/firebase-js-sdk/issues/1091

**Comment by bbangert** [comment] 2019-06-24 20:03
@Zirak I have removed the select for now, because of the bug in the firebase testing app. I'll need to restore that later as the documents get larger, but at the moment the ability to restore it is blocked.

**Closed** 2019-06-25 14:47 UTC

**Comment by Zirak** [comment] 2019-06-29 16:39
Oh, how weird about the firestore inconsistency! Thanks for the followup!
