### ISSUE TITLE
3D Secure card number does not require authentication at payment update

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#6113] opened 2020-08-03 14:14 UTC
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.182.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Prerequisites:
- Have an FxA account with active subscription;

 #### Steps to reproduce:
1. Load https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/subscriptions page;
2. Change the URL by adding a “/v2” value after .net/
3. Click on the “Change” button to update payment details;
5. Use the card no. *4000 0000 0000 3063* and fill all mandatory fields;
6. Click the “Update” button;

#### Expected result:
- A 3D secure popup window appears.

#### Actual result:
- The payment is updated as in a normal flow. (without v2)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2375)
┆Issue Number: FXA-2375

**Comment by data-sync-user** [comment] 2020-08-04 22:14
➤ Vijay Budhram commented:

From mtg: Les looking at this

**Comment by data-sync-user** [comment] 2020-08-12 21:17
➤ Jackie Munroe commented:

After looking into it: this is not a bug. The triggered event from Stripe that initiates the 3DSecure flow only happens when a charge is occurring. We will need to see what happens when the subscription comes due for payment.

**Comment by data-sync-user** [comment] 2020-08-12 22:00
➤ Jackie Munroe commented:

There do seem to be more issues present though that will require a greater amount of research.

  * We are ending up in a situation where a user has 2 subscriptions upon updating their payment. One is incomplete set to charge to the new card, and the other is the initial subscription, still active and set to charge the old card.

**Comment by data-sync-user** [comment] 2020-08-13 00:01
➤ Les Orchard commented:

So here's a strange thing to add here that I found while digging into FXA-2376:

I've noticed that a 3D Secure card is accepted without an auth popup - 4000000000003063

However, a 3D Secure 2 card does trigger an auth popup - 4000000000003220

**Comment by data-sync-user** [comment] 2020-08-13 20:57
➤ Benjamin Bangert commented:

Our rules do require a 3D Secure in stage for 4000000000003063. That should trigger an auth popup.

**Comment by data-sync-user** [comment] 2020-08-13 21:15
➤ Benjamin Bangert commented:

Ok, not handling this card in stage mode is apparently a known bug:

https://github.com/stripe/react-stripe-elements/issues/402 ( https://github.com/stripe/react-stripe-elements/issues/402 )

As such I will cease looking into that, and instead look at the issue [~jmunroe@mozilla.com] noted above regarding multiple subscriptions.

**Comment by data-sync-user** [comment] 2020-08-13 21:15
➤ Benjamin Bangert commented:

Also from above thread:

"It's getting created as an Incomplete subscription."

So it seems possible/probable that this is a quirk of the Stripe SDK in non-live mode. And supposedly this will work correctly in Live mode.

**Comment by data-sync-user** [comment] 2020-08-19 16:50
➤ Benjamin Bangert commented:

I tested with a 3184 ending card on v2/subscriptions to update, the SCA process came up correctly, no duplicate subscriptions were created, and the updated card was displayed correctly. I checked in Stripe, and everything looks as expected.

**Closed** 2020-08-19 16:54 UTC
Labels: severity:normal, status:bug

**Comment by data-sync-user** [comment] 2020-08-19 18:05
➤ Les Orchard commented:

This is already closed, but maybe also relevant is this issue & comment I saw today on the react-stripe-elements repo on SetupIntents (which we use for billing update):

https://github.com/stripe/react-stripe-elements/issues/402#issuecomment-520492702 ( https://github.com/stripe/react-stripe-elements/issues/402#issuecomment-520492702 )
{quote}It is expected that "3063" does not perform 3DS when using SetupIntents. This card has been around for a while and mimics the behavior of a bank which has decided to require 3DS on all payments. This is somewhat different from SCA rules. In particular, because a SetupIntent does not actually perform a payment, Stripe would not know that the bank requires 3DS and would not perform it. If you then attempt to make a payment with this card, 3DS should be required. If you want to test what it looks like when SCA rules require Stripe to perform 3DS just to save a card, you should use one of our regulatory test cards ( https://stripe.com/docs/testing#regulatory-cards ).
{quote}

**Comment by ValentinaPC** [comment] 2020-08-21 08:38
Verified as fixed in stage, using Fx79 and Windows 10 (64-bit).
The "4000000000003063" card, does not trigger a 3D auth if used at payment update, but triggers it at initial subscription. Also using a card from Regulatory Stripe section (4000002500003155) at payment update, triggers the 3D auth.
