### ISSUE TITLE
App store download images have mixed padding

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#7969] opened 2021-03-25 18:01 UTC
Refer to the attached image. The App Store image has a p-2 class, but the Play Store image doesn't. This creates different click areas and focus outlines, and also pushes the badges in from the right. I think the p-2 is just being used for spacing, so let's replace it with ml-2

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3251)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15596/Screen+Shot+2021-03-25+at+1.56.49+PM.png">Screen Shot 2021-03-25 at 1.56.49 PM.png</a>
┆Issue Number: FXA-3251

**Comment by jodyheavener** [comment] 2021-03-26 20:24
Dupe of #7005

**Closed by jodyheavener** 2021-03-26 20:24 UTC
