### ISSUE TITLE
[subplat] WError: An internal server error occurred

### ISSUE THREAD

**Issue by chenba** [mozilla/fxa#11901] opened 2022-02-09 19:37 UTC
Should deleted customers trigger this error?  That seems to be expected.

https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/17543827/?referrer=github_plugin

```
WError: An internal server error occurred
  File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/payments/stripe-firestore.js", line 15, in newFirestoreStripeError
    const error = new Error(message);
  File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/payments/stripe-firestore.js", line 96, in StripeFirestore.fetchAndInsertCustomer
    throw newFirestoreStripeError(`Customer ${customerId} was deleted`, FirestoreStripeError.STRIPE_CUSTOMER_DELETED);
  ?, in runMicrotasks
  File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/payments/stripe.js", line 1871, in async StripeHelper.expandResource
    await this.stripeFirestore.retrieveAndFetchCustomer(paymentMethod.customer);
  File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.js", line 80, in async StripeWebhookHandler.handleWebhookEvent
    event.data.object = await this.stripeHelper.expandResource(stripeObject.id, resourceType);
...
(6 additional frame(s) were not displayed)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4590)

**Comment by data-sync-user** [comment] 2022-03-16 19:34
➤ Barry Chen commented:

The patch in 227 didn’t seem to fix this?!  See https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/18673184/?query=is%3Aunresolved ( https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/18673184/?query=is%3Aunresolved )

**Comment by data-sync-user** [comment] 2022-04-01 16:03
➤ Barry Chen commented:

I think the newer Sentry issue is caused by the same problem in https://mozilla-hub.atlassian.net/browse/FXA-3983 ( https://mozilla-hub.atlassian.net/browse/FXA-3983|smart-link ).  There’s already a open PR for that.  I’ll mark this Jira as fulfilled by https://mozilla-hub.atlassian.net/browse/FXA-3983 ( https://mozilla-hub.atlassian.net/browse/FXA-3983|smart-link ).  I’ll verify in Sentry after that patch’s deployed.

**Comment by data-sync-user** [comment] 2022-04-01 16:04
➤ Barry Chen commented:

I should be more clear here: the new Sentry issue is not the same as the one fixed in the first patch.

**Comment by data-sync-user** [comment] 2022-04-01 18:26
➤ Barry Chen commented:

The original issue is from the webhook handlers for Firestore.  The original patch https://github.com/mozilla/fxa/pull/11983 ( https://github.com/mozilla/fxa/pull/11983|smart-link ) ignored the error based on the type of the webhook event.

The newer Sentry issue (in comment https://mozilla-hub.atlassian.net/browse/FXA-4590?focusedCommentId=524192 ( https://mozilla-hub.atlassian.net/browse/FXA-4590?focusedCommentId=524192|smart-link )) is from our Stripe webhook handlers.  At some point, we made a change to “expand” the resource in the webhook event for all events.  This meant that we’d try to expand a payment method belonging to a customer that’s been deleted.  In Reino’s patch for https://mozilla-hub.atlassian.net/browse/FXA-3983 ( https://mozilla-hub.atlassian.net/browse/FXA-3983|smart-link ), we skip the “expand” call, thus preventing the issue from happening.

**Comment by data-sync-user** [comment] 2022-04-07 18:15
➤ Barry Chen commented:

Marking this as Done to avoid confusion.  See comments below for details.

**Closed** 2022-04-07 18:15 UTC
