### ISSUE TITLE
"You've tried too many times" error is displayed partly localized

### ISSUE THREAD

**Issue by selimsumlu** [mozilla/fxa#17069] opened 2024-06-04 09:53 UTC
## Description

"You've tried too many times" error is displayed in English when trying to login multiple times using a wrong password.

### Steps to reproduce

1. Visit Mozilla accounts website in a locale other than English. It's Turkish in my case.
2. Input a wrong password multiple times.

### Expected result

Error message should be display in Turkish.

### Actual result

Error message is displayed in English except the %(retryAfterLocalized)s part.

Here's the corresponding string in Pontoon: https://pontoon.mozilla.org/tr/all-projects/all-resources/?string=158613

![you've tried too many times](https://github.com/mozilla/fxa/assets/1046789/eb2b0326-ac03-4c6a-81d1-5ce3df29b2ad)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-9770)

**Comment by clouserw** [comment] 2024-06-10 18:55
This is a dupe of https://github.com/mozilla/fxa/issues/9562 and something we're still tracking internally at https://mozilla-hub.atlassian.net/browse/FXA-1332.  We're (slowly) converting our pages to react from backbone and this has been fixed on react so new pages don't have this problem.  Thanks for filing this, but I'm going to close it as it's a known issue

**Closed by clouserw** 2024-06-10 18:55 UTC
