### ISSUE TITLE
Password is saved in the Delete account section

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla/fxa#2283] opened 2019-08-21 11:45 UTC
Environment:
Builds: Stage [Train 144];
Devices: Android, Windows 10 ;

Prerequisites:
Choose "Remember" from the doorhanger when logging in.

Steps to reproduce:

1. Go to Manage account;
2. Tap on "Delete..." button from the Delete account section;
3. Observe the password field. 

Expected results:
The password field is empty.

Actual results:
The password field contains the password saved when logged in.

Notes:
When deleting the password from the password field, the autofill list is available and the user can choose the password from there. The password should be typed in.
Reproducible on production but only for the first log in.
Not reproducible on iOS.
[Screenshot](https://drive.google.com/file/d/10WJCdaCkqnjLdDeWOImDaDiQ9Yvu6S_Z/view)

**Comment by bsurd** [comment] 2019-08-21 14:20
As an extra security measure autofill suggestion could be disabled as well for that field forcing the user to manually introduce his password to confirm account deletion.

**Comment by LZoog** [comment] 2019-08-21 15:59
I will let UX confirm, but per this issue, I believe this is by design: https://github.com/mozilla/fxa/issues/2210

**Comment by clouserw** [comment] 2019-08-30 16:03
Closing based on decision in #2210

**Closed by clouserw** 2019-08-30 16:03 UTC
Labels: needs:ux
