### ISSUE TITLE
Safari does not handle tab focus on subscription form

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa#3303] opened 2019-11-11 15:10 UTC
Filed in Beta test:

Fields do not properly focus on Safari on the payments page.

> When submitting payment information (at least on Safari on macOS), the input fields don't gain focus properly when tabbing between the fields and I cannot input my credit card information without manually clicking on each field individually with my mouse.

**Comment by johngruen** [comment] 2019-11-11 15:16
Possibly a dupe of #3089, but i cannot repro in chrome still

**Comment by LZoog** [comment] 2019-11-22 23:20
The culprit appears to be `<span tabindex="-1"` adjacent to every `input`. When I remove this from the DOM on each input, the issue is fixed.
<img width="1296" alt="image" src="https://user-images.githubusercontent.com/13018240/69466832-4932dd80-0d4b-11ea-9847-fa0909b7fc56.png">

It looks like this is coming directly from [Stripe Elements](https://stripe.com/payments/elements) and inside the iframe. They have an [Elements Examples](https://github.com/stripe/elements-examples) repo but I don't see one that seems like the "right" place to create an issue in (`react-stripe-elements` is just a wrapper) so based on a previous issue I know a Moz team member made in another related Stripe repo wherein the issue was closed, I've filled out Stripe's "contact us" form to let them know of this issue.

While searching through their docs, it seems likely the [issue described here for iOS Safari](https://support.stripe.com/questions/ios-13-and-stripe-elements-label-focus-issue) is one in the same.

This seems like a "won't fix" for us, but we could leave it open so I can share their response here.

**Comment by LZoog** [comment] 2019-11-25 15:22
Stripe responded over the weekend and said there are a few other known, similar issues around Safari and form fields. They're flagging it on their end. I imagine this is low priority for them but hopefully it gets us somewhere.

I'm going to close this issue since it's not something we'll resolve.

**Closed by LZoog** 2019-11-25 15:22 UTC
Labels: BETA
