### ISSUE TITLE
Fenix "Desktop Site" makes FxA show a spinner, fail to load

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#2036] opened 2019-08-01 13:39 UTC
### STR

* Get Firefox Preview
* Open accounts.firefox.com
* Use the fenix menu and tap "Desktop Site"

### Actual

Page is zoomed in, scrollable to the mozilla logo and a blue spinner

Ref: https://github.com/mozilla-mobile/fenix/issues/3947

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-243)
┆Issue Number: FXA-243

**Comment by vbudhram** [comment] 2019-08-05 17:20
@vladikoff Any ideas what might be going on here? Do you have console logs to help?

**Comment by data-sync-user** [comment] 2021-04-01 16:06
➤ Wil Clouser commented:

The referenced bug is closed as can't reproduce so also closing here.

**Closed by data-sync-user** 2021-04-01 16:06 UTC
