### ISSUE TITLE
Incorrect one-time fee value listed in subscription upgrade mail

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#5418] opened 2020-05-22 10:47 UTC
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.172.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Preconditions
- existent FxA account with active upgraded subscription;

#### Steps to reproduce
1. Go to subscription upgrade email.
2. Observe the one-time fee value.

#### Expected result:
- One-time fee value is correct.

#### Actual result:
- One-time fee value is incorrect.

#### Notes:
- We are guessing, the decimal format is missing.

![image](https://user-images.githubusercontent.com/15685960/82659756-e3f47200-9c31-11ea-89c4-a0bb63cea013.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1957)
┆Issue Number: FXA-1957

**Comment by data-sync-user** [comment] 2020-05-26 16:56
➤ Les Orchard commented:

I can reproduce this issue and will have a fix shortly. Looks like it's the same email as FXA-1958

**Comment by data-sync-user** [comment] 2020-05-26 18:31
➤ Les Orchard commented:

https://github.com/mozilla/fxa/pull/5442

**Comment by ValentinaPC** [comment] 2020-06-02 09:23
Verified this in stage, using Fx76 and Windows 10 (64-bit) and obtained the following results:
- having a normal subscription (from Guardian site) beside the upgrade subscription, will generate a correct one-time-fee value.
![onlysubscr-upgrade](https://user-images.githubusercontent.com/15685960/83503500-d362b800-a4cb-11ea-816c-297bcac7d39d.png)

- having only a upgrade subscription will generate incorrect one-time-fee value
![onetimefee](https://user-images.githubusercontent.com/15685960/83503362-a0b8bf80-a4cb-11ea-94d7-7dcf33d0458f.png)

**Comment by data-sync-user** [comment] 2020-06-02 17:35
➤ Les Orchard commented:

I can reproduce. However, it looks like auth-server in staging hasn't been updated to v1.173.0 where this fix was landed:

➜  ~ date && curl https://api-accounts.stage.mozaws.net/__version__
Tue Jun  2 10:24:10 PDT 2020
{
  "version": "1.172.0",
  "commit": "3a6a83ac76b01f1d4d3f8ae92a4098b11e6a0bd8",
  "source": "https://github.com/mozilla/fxa"
}

**Closed** 2020-06-02 17:47 UTC
Labels: severity:major, status:bug

**Comment by ValentinaPC** [comment] 2020-06-03 07:19
Verified as fixed in stage, using Fx76 and Windows 10 (64-bit).
Postfix screenshot below.
![image](https://user-images.githubusercontent.com/15685960/83604073-301eab00-a57e-11ea-8ccc-2e6488162380.png)
