### ISSUE TITLE
Functional tests often fail because element is not fully faded in

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#3165] opened 2019-10-29 12:32 UTC
Ref https://circleci.com/gh/mozilla/fxa/104174#tests/containers/2

> Screenshot saved at: https://screencap.co.uk/images/78e9dd0d3b945562073ce13db5c62002f2cd4794.png
× firefox on linux 4.15.0-1043-aws - Fx Fennec Sync v1 sign_in - signup in desktop, send an SMS, open deferred deeplink in Fennec (4.911s)
    AssertionError: expected '' to equal 'sync0.90232043444388@restmail.net'
    E sync0.90232043444388@restmail.net
      at Command.<anonymous> @ tests/functional/lib/helpers.js:2045:14
      at Command.<anonymous> @ tests/functional/lib/helpers.js:2044:6
      at Command.<anonymous> @ tests/functional/lib/helpers.js:61:10
      at Command.<anonymous> @ tests/functional/lib/helpers.js:75:18
      at Command.<anonymous> @ tests/functional/lib/helpers.js:69:10
      at Command.<anonymous> @ tests/functional/fx_fennec_v1_sign_in.js:152:18
      at Test.test @ tests/functional/fx_fennec_v1_sign_in.js:145:14
      @ src/lib/Test.ts:263:51

You can see in the image that the email is displayed, just not fully faded in.

**Comment by chenba** [comment] 2019-11-27 00:12
I cannot reproduce this locally (with 20+ test runs).  And I don't recall seeing the failure often recently.

Also, since `testElementTextEquals` is already calling `visibleByQSA`, the test looks correct...?

I'm going to WONTFIX this.  We can always re-open or re-file.

**Closed** 2019-11-27 00:12 UTC
Labels: P2, cat:code quality
