### ISSUE TITLE
”System unavailable, try again soon“ error when setting an edited picture as Firefox avatar

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#5264] opened 2020-05-11 09:48 UTC
**Build:**
Stage [Train 1.170.0]

**Affected platforms:**
Windows 10 64-bit

**Steps to reproduce:**
1. Launch Firefox and login into fxa using a mozilla account.
2. Go to https://accounts.stage.mozaws.net/settings/
3. Click "Add" button from the Account picture area.
4. Click on the “Upload” button.
5. Zoom it to maximum.
6. Drag down the picture at maximum.
7. Click “Change” button.
 
**Expected results:**
The picture is successfully displayed in the avatar pop-up.

**Actual Results:**
”System unavailable, try again soon“ error message is displayed.

**Additional notes:**
- This issue is reproducible only following the above steps.
- I was able to reproduce the error only using the attached picture.
- I am attaching the above used image: ![Screenshot_4](https://user-images.githubusercontent.com/18114210/81548075-5ee1a100-9385-11ea-8301-065f92dd80d4.png)

![system unavailable](https://user-images.githubusercontent.com/18114210/81548086-64d78200-9385-11ea-9ea1-5d63718c2de7.gif)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1858)
┆Issue Number: FXA-1858

**Comment by data-sync-user** [comment] 2020-05-18 14:18
➤ Barry Chen commented:

This is caused by the upload file size limit.  I'll close this issue as a WONTFIX.  However, I'll file a follow-up for a better error message.

**Comment by data-sync-user** [comment] 2020-05-18 14:18
➤ Barry Chen commented:

Uploaded image > limit.

**Closed by data-sync-user** 2020-05-18 14:18 UTC
Labels: severity:minor

**Comment by data-sync-user** [comment] 2020-05-18 14:23
➤ Barry Chen commented:

FXA-1908 is the follow-up.
