### ISSUE TITLE
Deeplinking on Android appears broken with new JSR type adjust links

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#5069] opened 2020-04-22 17:09 UTC
We've updated how our deeplinking work per [adjust docs](https://www.adjust.com/product-updates/adjust-deeplink-generator/) to use their javascript based flows. This was done in https://github.com/mozilla/fxa/pull/4777 and appeared to worked correctly in iOS.

### STR on Android

Prerequisites: Firefox Android is removed from the device

1. Goto [connect another device](https://accounts.firefox.com/sms)
2. Send yourself an SMS with the link
3. Click the link

### Actual:

Page opens and is blank

### Expected:

Page opens and redirects to the Play Store

I'm not sure exactly why the updated adjust link does not work, but I think we should at least revert to the old android link in the meantime since that seemed to be working according to this [dashboard](https://analytics.amplitude.com/mozilla-corp/chart/new/66m2t0i).

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1736)
┆Issue Number: FXA-1736

**Comment by chenba** [comment] 2020-04-22 17:21
Cannot reproduce on my phone.  The link did open the Play Store correctly.

**Comment by lmorchard** [comment] 2020-04-22 17:25
I *can* reproduce on my phone: I get a blank page if the link is opened in Chrome or Samsung Internet. The link works in release Firefox and Fenix

**Comment by chenba** [comment] 2020-04-22 17:31
I opened it in Chrome.

**Comment by lmorchard** [comment] 2020-04-22 17:43
Finally got a remote console on Chrome. It reports just this message, "Navigation is blocked"

<img width="504" alt="Capture" src="https://user-images.githubusercontent.com/21687/80015087-16218100-8486-11ea-9ef7-8abe0f8d09a9.PNG">

**Comment by jodyheavener** [comment] 2020-04-22 17:47
Both Chrome and Samsung Internet open the Play Store for me. Android 7.

**Comment by lmorchard** [comment] 2020-04-22 17:49
Oh yeah, and I'm reproducing on Android 10 on a Samsung Galaxy S10 running Chrome 81.0.4044.111

**Comment by chenba** [comment] 2020-04-22 17:53
Same version of Chrome as Les but on Android 8.

**Comment by lmorchard** [comment] 2020-04-22 17:59
There's also [this 2015 blog post about deep linking by Paul Kinlan](https://paul.kinlan.me/deep-app-linking-on-android-and-chrome/) that mentions using `intent:` based URLs rather than a custom protocol like `market:` - just skimming, so I'm not 100% sure what all this entails, but it seems like a lead maybe?

**Comment by vbudhram** [comment] 2020-04-22 18:32
Thanks for testing everyone. I've put a [PR](https://github.com/mozilla/fxa/pull/5076) to revert the android link so I can debug a bit more (need to get physical android vs emulator).

**Comment by data-sync-user** [comment] 2020-04-28 20:14
➤ Wil Clouser commented:

This is fixed by reverting.

**Closed by data-sync-user** 2020-04-28 20:14 UTC
