### ISSUE TITLE
[meta] Post-June 4th - Rollout Trailhead Style and Copy to All Touch Points, Service, Langues and Platforms

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#1245] opened 2019-05-23 21:08 UTC
For June 4th, we were only rolling our trailhead design and copy to about:welcome and /whatnew. Specifically, whatever touchpoint passes us `style=trailhead`.

Post-June 4th, we need to roll-out copy and styling across all of our products, touchpoints and platforms.

This issue/bug is to identify changes that may need to be done to the new trailhead flows to make them compatible everywhere. In other words, how do we display it in places that don't pass `style=trailhead`.

We need to:
- design/document mobile flows (we've only been thinking about desktop)
- audit to make sure that the trailhead flow is relevant from all entrypoints in the browser (we made a lot of choices specific to the context of about:welcome)
- identify and understand if/what changes are needed for our relying parties.
- integrate these

**Comment by shane-tomlinson** [comment] 2019-05-24 09:19
We also have to remember RTL. I've tried to do the best I can with mobile and RTL, though we need to verify both of those work as expected.

**Comment by clouserw** [comment] 2019-06-06 16:05
This is a dupe of #1029.  I will tentatively close it, but let me know if I'm messing up anyone's flows.

**Closed by clouserw** 2019-06-06 16:05 UTC
Labels: P3
