### ISSUE TITLE
Don't block user from proceeding when utm_* parameters are invalid

### ISSUE THREAD

**Issue by rlr** [mozilla/fxa#5991] opened 2020-07-20 21:47 UTC
## Description

It appears there is some sort of validation of utm_* metric parameters. When one is invalid, the user is stuck and can't proceed.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/36629/87989902-e3048300-cab0-11ea-8485-467e7df80da9.png)

### Expected result

FxA should just ignore the parameter but not block the user.

### Actual result

User is stuck.

### Environment

What browser and operating system are you using?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2313)
┆Issue Number: FXA-2313

**Comment by rlr** [comment] 2020-07-20 21:52
I'm able to reproduce by setting `utm_source=(not set)` for example. Full URL: https://accounts.stage.mozaws.net/oauth/signup?client_id=6089c54fdc970aed&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Foauth%2Fsuccess&scope=profile&response_type=code&state=604b1f32da297a6b9d0795fe4dafc1d863036600e4e669497bbec6e899380c0b0e6dadc904476935&access_type=offline&action=email&utm_source=(not%2Bset)

<img width="804" alt="Screen Shot 2020-07-20 at 5 51 59 PM" src="https://user-images.githubusercontent.com/36629/87990307-ba30bd80-cab1-11ea-8b03-f088814b6763.png">

**Comment by clouserw** [comment] 2020-07-20 21:55
This is a dupe of https://github.com/mozilla/fxa/issues/3673

**Closed by clouserw** 2020-07-20 21:55 UTC
