### ISSUE TITLE
A loop is created between Recovery codes message and back button

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa#628] opened 2018-05-23 14:09 UTC
Environment: 62.0a1 - Sony Xperia Z2 (Android 6.0.1), WIN 10
Server: production

Steps to reproduce:
1. Log in with an account with 2FA enabled;
2. Go to Manage account and generate new recovery codes;
3. Tap on Done;
4. Tap on browser back button or device back button.

Expected results: the manage account page is no longer available, and the user is taken to the previous page visited.

Actual results: the message with recovery codes is displayed, and tapping on "done" and again on back button has the same behavior. A loop is created between the message and the back button. 

Note: the message can be dismiss only if you tap 2,3 times on back button.

See the video: https://drive.google.com/file/d/0B_kDj8vLfC8IQmhtWFZrSGpRbGQxS3o4Vng3dzhHYnJlZ29n/view?usp=sharing

**Comment by vbudhram** [comment] 2019-06-25 18:23
Closing this since I believe it is working as intended. When the user clicks back, they view the recovery codes pages with an option to generate new ones.

**Closed by vbudhram** 2019-06-25 18:23 UTC
Labels: P3, fxa-content-server
