### ISSUE TITLE
Cannot delete Firefox Accounts account

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/fxa#2896] opened 2019-10-15 07:48 UTC
## Description
I cannot delete my account in staging, I'm getting an "Unexpected error", with no info on what's the error. 

### Steps to reproduce
1. Login to https://accounts.stage.mozaws.net
2. Click "Delete" button
3. Check all 3 checkboxes and enter your password
4. Click "Delete Account" button

### Expected result
Confirmation message that the account is deleted is returned

### Actual result
"Unexpected error" message is displayed, account is not deleted
![image](https://user-images.githubusercontent.com/5293100/66810969-ee7eb880-ef38-11e9-92b0-31e5174e66b5.png)

### Environment

Ubuntu 16.04, Firefox 69.0.3

**Comment by shane-tomlinson** [comment] 2019-10-15 13:21
I'm wondering if this is the cause of #2900

**Comment by shane-tomlinson** [comment] 2019-10-15 13:23
Note, this happens on prod too and is almost certainly the cause of #2900.

**Comment by shane-tomlinson** [comment] 2019-10-15 19:18
fixed by #2903, closing.

**Closed by shane-tomlinson** 2019-10-15 19:18 UTC
Labels: [QA]:Blocker issue, status:bug
