### ISSUE TITLE
[FxA-Settings] Signing out of a connected service mobile UI issue

### ISSUE THREAD

**Issue by rbillings** [mozilla/fxa#7483] opened 2021-02-09 20:19 UTC
## Description

Signing out of a connected service on mobile makes it appear that I signed out of a different service.
Submitted by: Alex Davis

### Steps to reproduce

- Manage account
- Connected services
- Disconnect a service

### Expected result

What should happen?

### Actual result

<img width="256" alt="Screen Shot 2021-02-09 at 12 17 17 PM" src="https://user-images.githubusercontent.com/737878/107423132-d7ba8880-6ad0-11eb-8ed4-4f786845a0d0.png">

### Environment

iOS 14.2
[rbillings: I was unable to repro on Android]

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3022)
┆Issue Number: FXA-3022

**Comment by vasilicatamas** [comment] 2021-02-10 16:33
This might be a dupe of #6371 . I will confirm it by checking the #6371 fix which will land in the next train.

**Comment by data-sync-user** [comment] 2021-02-10 20:17
➤ Barry Chen commented:

Triage note: waiting on dupe confirmation.

**Comment by data-sync-user** [comment] 2021-02-16 15:07
➤ Vasilica Tamas commented:

I was not able to reproduce this issue on Stage [Train 1.200.0] under iOS 13.6. Confirm that this is a dupe of FXA-2512.

**Closed by data-sync-user** 2021-02-16 15:07 UTC
