### ISSUE TITLE
Don't allow `unsafe-inline` in the payments server

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2649] opened 2019-09-27 16:15 UTC
It looks like CSP is allowing `unsafe-inline` scripts.  We shouldn't have that.  This came out of #1128.

**Comment by clouserw** [comment] 2019-09-27 16:21
From @lmorchard in #1923 

> If I recall, we need unsafe-inline for style-src because React injects inline styles. In particular, for the third-party Stripe elements over which we don't have much control otherwise (because they're managed by Stripe's JS). Might need to dig to verify this, but I think that's the reason. So, we could remove it but not have any styling for the Stripe elements.

**Comment by chenba** [comment] 2019-09-27 16:26
Unsafe scripts aren't allowed already, hence the fix in https://github.com/mozilla/fxa/issues/2242.

**Comment by LZoog** [comment] 2019-09-27 16:30
This looks like a duplicate of #2138. We have unsafe-inline _styles_, not _scripts_.

From @g-k in that issue:
> ... That said unsafe-inline styles aren't a huge concern to me, and we do allow other inline styles on other sites.

I'll look into Greg's suggestion for the next train.

**Closed by LZoog** 2019-09-27 16:30 UTC
