### ISSUE TITLE
“Need another code? Resend” and “Use a different email” are not displayed at the same time

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#4544] opened 2020-03-13 13:06 UTC
**Build:**
Stage [Train 1.162.0]

**Affected platforms:**
Windows 10 x64
Android 9

**Steps to reproduce:**
1. Create and confirm a new Firefox account.
2. Go to the email inbox and open the "Set up recovery email" email.
3. Add a different email address in the field and tap on "Continue".
4. Check how the “Need another code? Resend” and “Use a different email” links are displayed..

**Expected results:**
Both links from “Enter verification code” page are displayed at the same time.

**Actual Results:**
“Use a different email” link appears from the beginning and “Need another code? Resend” link is displayed with delay.

![verificationcode](https://user-images.githubusercontent.com/18114210/76623363-04ba9000-653c-11ea-9b12-b390ec9d6253.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1373)
┆Issue Number: FXA-1373

**Comment by vbudhram** [comment] 2020-03-13 14:41
@vasilicatamas I believe this is intended behavior. It is to avoid users clicking the resend button right away with the hopes that they actually go check their inbox.

@ryanfeeley Is this pattern still useful here or should we do something different?

**Comment by data-sync-user** [comment] 2020-03-17 20:20
➤ Wil Clouser commented:

[~adavis@mozilla.com] might also be able help

**Comment by data-sync-user** [comment] 2021-04-01 19:44
➤ Lauren Zugai commented:

Closing this as it's over a year old and this should be intended behavior.

**Closed by data-sync-user** 2021-04-01 19:44 UTC
Labels: needs:ux
