### ISSUE TITLE
1Password cannot fill into FxA credential forms

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#1687] opened 2019-07-08 14:04 UTC
STEPS TO REPRODUCE
1. Use 1Password and have Firefox extension installed (v4.7.5.90)
1. Have credentials stored for accounts.firefox.com
1. Try to fill in credentials on any FxA authentication form

EXPECTED RESULTS
1. Credentials are filled

ACTUAL RESULTS
1. Credentials are not filled

**Comment by shane-tomlinson** [comment] 2019-07-08 14:26
This is because *no* 3rd party extension is allowed to interact with FxA, see https://bugzilla.mozilla.org/show_bug.cgi?id=1476755. Team FxA can't do anything about this without browser support.

**Comment by clouserw** [comment] 2019-07-08 17:06
Closing as a dupe of bug 1476755

**Closed by clouserw** 2019-07-08 17:06 UTC
