### ISSUE TITLE
Double error messages after the second card number

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla/fxa#4087] opened 2020-02-10 14:54 UTC
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Windows 10 (x64)

#### Preconditions
- Have a FxA account without a subscription.

#### Steps to reproduce
1. Open the [stage website](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn).
2. Click on the "Subscribe Now" button and complete the subscription process using the following Card number: 4000-0000-0000-0101.
3. Click on the Subscribe button.
4.  Complete again the subscription process using the following Card number: 4000-0000-0000-0127.
5. Click on the Subscribe button.

#### Expected result:
- A "Try again" error message is displayed.
- No payment is made.

#### Actual result:
- A "Something went wrong. Please try again later." message appears twice on the top of each other.

#### Notes:
- Arart from the two mentioned card numbers, it's the same result with the following card numbers, used after each other: 
4000-0000-0000-9979
4000-0000-0000-9987
4000-0000-0000-9995
4000-0000-0000-0002

![Screenshot_2020-02-10 Firefox Accounts](https://user-images.githubusercontent.com/48829350/74160338-eb18e680-4c25-11ea-85c4-26d23706612e.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1060)
┆Issue Number: FXA-1060

**Comment by data-sync-user** [comment] 2020-02-13 16:06
➤ Les Orchard commented:

I think this is fixed with a combination of these:

  * https://github.com/mozilla/fxa/pull/4047 ( https://github.com/mozilla/fxa/pull/4047 ) (merged)
  * https://github.com/mozilla/fxa/pull/4135 ( https://github.com/mozilla/fxa/pull/4135 ) (waiting on CI)

Or, at least fixed insofar as I can't reproduce the issue at this point. Will wait to close until after 4135 is merged.

**Closed** 2020-02-13 16:16 UTC
Labels: severity:minor, status:bug

**Comment by SoftVision-LorandJanos** [comment] 2020-02-14 10:28
This issue is no longer reproducible on [Guardian VPN stage](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn). Using Firefox Release 73.0. Tested on MacOS 10.14.6.
