### ISSUE TITLE
Unable to delete account on stage server

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fxa#5002] opened 2020-04-17 18:18 UTC
## Description

I'm unable to delete my account on the stage server

### Steps to reproduce
Note: I have a secondary email on the account

1. Go to https://accounts.stage.mozaws.net/settings/
2. Click "Delete" next to "Delete account"
3. Check all 3 boxes
4. Enter password

### Expected result

Should delete the account

### Actual result

Received weird "Incorrect email case" error.

![image](https://user-images.githubusercontent.com/71928/79601062-d0dc0880-80ad-11ea-9eda-e46c46907946.png)

### Environment

Mac Firefox 77.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1686)
┆Issue Number: FXA-1686

**Comment by jrgm** [comment] 2020-04-17 18:43
One theory (perhaps) - https://github.com/mozilla/fxa/issues/5003#issuecomment-615398757

**Comment by jrgm** [comment] 2020-04-17 18:53
Perhaps this is a scenario to explain this: Password is mistyped so https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/lib/routes/account.js#L1369-L1376
But because of the email/account history the check in error handling fails here https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/lib/error.js#L329-L342 and converts incorrect password into incorrect email case (?)

**Comment by jrgm** [comment] 2020-04-17 18:55
Note: the only way I see to get 'Incorrect email case' is to be in AppError.incorrectPassword

**Comment by vbudhram** [comment] 2020-04-17 19:05
@jrgm This is reproducible on master as well. When the request to delete account fails because of incorrect case, it should reattempt with the email returned by the server (correct case). It doesn't do that now, so I suspect that might be part of the problem. I'll continue to dig into it

**Comment by vbudhram** [comment] 2020-04-17 19:15
Per typescript docs, this might need an await [here](https://github.com/mozilla/fxa/blob/536a69eb19611fa23085a75b9a73e75c8df729c7/packages/fxa-content-server/app/scripts/lib/auth/client.ts#L457). I'll prep a PR and see why the tests couldn't have caught this.

**Comment by vbudhram** [comment] 2020-04-23 14:39
This was fixed in https://github.com/mozilla/fxa/pull/5004

**Closed by vbudhram** 2020-04-23 14:39 UTC
