### ISSUE TITLE
Subscription for “123 Done... Pro” product fails with 500 error if the user made another subscription before

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#6045] opened 2020-07-27 12:52 UTC
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.181.0

#### Affected Platforms:
- Windows 10 (64-bit);

#### Prerequisites:
- Have an FxA account with an active subscription for Mozilla VPN product;

 #### Steps to reproduce:
1. Load https://123done-stage.dev.lcip.org/ page
2. Click on “Sign Up” button;
3. Use the same account as in prerequisites and click on the “Subscribe for Pro” button;
4. Fill all mandatory fields and click “Pay now” button;

#### Expected result:
- Subscription is finalized with success.

#### Actual result:
- Subscription cannot be done. The “An internal server error occurred” message is displayed.

#### Notes:
- Issue is not reproduced if user did not make a subscription for another product before; 

![image](https://user-images.githubusercontent.com/15685960/88543654-f4a1d980-d020-11ea-85c7-363cd79ac054.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2350)
┆Issue Number: FXA-2350

**Comment by chenba** [comment] 2020-08-17 19:38
I was able to subscribe to two products _as long as those products are in the same currency_.  I can see in the screenshot that One, Two, Three Done...PRO is in MYR, so that's the cause of the error.  Closing this now.  Please re-open if I've misunderstood the issue.

**Closed by chenba** 2020-08-17 19:38 UTC
Labels: severity:normal, status:bug

**Comment by ValentinaPC** [comment] 2020-08-18 08:22
This issue was fixed when we added the multiple currency options for 123Done product.
