### ISSUE TITLE
ZIP code field has no min-max length restrictions

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#5852] opened 2020-07-03 09:23 UTC
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.178.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Prerequisites:
- Have an active FxA account;

#### Steps to reproduce
1. Go to https://stage-browser.guardian.nonprod.cloudops.mozgcp.net/  ;
2. Click on the subscription button;
3. Type something in the zip code field;

#### Expected result:
- There is a min-max length restriction.

#### Actual result:
- There is NO min-max length restriction

![zip](https://user-images.githubusercontent.com/15685960/86454224-99cdd880-bd27-11ea-8ab1-a820783e4474.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2231)
┆Issue Number: FXA-2231

**Comment by data-sync-user** [comment] 2020-07-06 16:09
➤ Chelsea Lewis commented:

[~vvirlics@mozilla.com] Thank you for filing. Per [~jgruen@mozilla.com] this is not a bug, and in fact is a requirement to launch payments in additional countries. As countries such as the UK have alphanumeric zip/postal codes, and various countries have as few as four and as many as seven (if I recall correctly, although perhaps we shouldn't quote me here!), we needed to remove the restrictions to allow for additional forms of payments.

Closing as a WONTFIX, but John - please feel free to comment if you have additional information. Valentina, our apologies that this change in experience was not called out more explicitly, we'll be sure to do that in the future. Please update your test case accordingly.

**Closed by data-sync-user** 2020-07-06 16:09 UTC
Labels: severity:minor, status:bug
