### ISSUE TITLE
Intermittent failing tests in content-server: support form redirects

### ISSUE THREAD

**Issue by 6a68** [mozilla/fxa#3364] opened 2019-11-13 20:59 UTC
These tests have failed fairly often recently, see [this build](https://app.circleci.com/jobs/github/mozilla/fxa/112795) as an example. Tests are:

* support form without active subscriptions - go to support form, redirects to subscription management, then back to settings (24.473s)
* support form with an active subscription - go to support form, cancel, redirects to subscription management (26.898s)
* support form with an active subscription - go to support form, submits the form (26.631s)
* support form without active subscriptions - go to support form, redirects to subscription management, then back to settings (24.123s)

**Comment by vladikoff** [comment] 2019-11-13 21:10
is there supposed to be a subscription button in the ui:

![](https://screencap.co.uk/images/29055133975d8d5c95215ad5466a33f232d93a36.png)

**Comment by shane-tomlinson** [comment] 2019-11-14 12:44
Dup of #3297, but this has more context so closing that one.

**Comment by chenba** [comment] 2019-11-15 17:48
I ran the support form functional tests many times, and the one test that failure somewhat regularly was "support form without active subscriptions - go to support form, redirects to subscription management, then back to settings".  The others passed 100% of the time.

I'll create a patch to update the flaky test and see that will improve the situation in CI.

**Comment by chenba** [comment] 2019-11-18 22:14
I'll keep an eye on content server tests in CircleCI this week.  If branches with PR #3374 don't have any support form functional test failures, I'll close this by the end of the week.

**Comment by chenba** [comment] 2019-11-22 14:43
None of the CI failures so far this week were caused by a support form functional test [0].  I'm going to close this.

[0] Builds for branches with PR #3374 in them.

**Closed by chenba** 2019-11-22 14:43 UTC
Labels: P2, cat:code quality
