### ISSUE TITLE
Password Verification Tooltip Incorrectly Displayed

### ISSUE THREAD

**Issue by chenba** [mozilla/fxa#3504] opened 2019-11-27 16:55 UTC
There's a timing(?) issue somewhere that's causing the not matching password tooltip to be displayed, even when the passwords are matching.

![image](https://user-images.githubusercontent.com/198055/69743604-501f6e80-1104-11ea-9cdc-f1ce1ab031de.png)

**Comment by chenba** [comment] 2019-11-27 16:56
The user can still successfully sign up.  It doesn't block form submission.

**Comment by vasilicatamas** [comment] 2019-12-02 09:29
I’m suspecting that this is a dupe of #3486

**Comment by clouserw** [comment] 2019-12-02 18:18
This is currently listening to the keyUp event.  We probably need to add support for the paste event (or whichever event gets triggered for pasting in a password)

**Closed** 2019-12-04 19:37 UTC
Labels: good first issue, help wanted, skill:js
