### ISSUE TITLE
[FXA-Settings] Connected Services copy should be left-aligned

### ISSUE THREAD

**Issue by janiceahn** [mozilla/fxa#7759] opened 2021-03-09 17:34 UTC
## Description
Should be left-aligned:

Missing or duplicate items?
Get Firefox on mobile or tablet...

### Steps to reproduce
![image](https://user-images.githubusercontent.com/6219141/110512837-94553900-80d3-11eb-83ec-bca7548aaad1.png)

### Expected result
<img width="532" alt="Untitled" src="https://user-images.githubusercontent.com/6219141/110512890-a46d1880-80d3-11eb-96e8-819350c5312f.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3154)
┆Issue Number: FXA-3154

**Comment by data-sync-user** [comment] 2021-03-11 09:32
➤ Vasilica Tamas commented:

Closing as dupe of FXA-2844

**Closed by data-sync-user** 2021-03-11 09:32 UTC
