### ISSUE TITLE
Large spinning wheel image missing?

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#1124] opened 2019-05-16 13:29 UTC
STEPS TO REPRODUCE
1. Visit https://latest.dev.lcip.org/settings/avatar/change
2. Set an avatar
3. Reload page, or return to this dialog

EXPECTED RESULTS
* Spinning wheel indicates loading progress

ACTUAL RESULTS
* Looks like maybe the image file is missing? Not sure

<img width="472" alt="image" src="https://user-images.githubusercontent.com/68213/57857421-1c5ea600-77bd-11e9-87ef-6fdaf1f36c9c.png">

**Comment by clouserw** [comment] 2019-05-20 17:16
Marking as a duplicate of #1107

**Closed by clouserw** 2019-05-20 17:16 UTC
