### ISSUE TITLE
I request my old email to be updated [bz1493217]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#1966] opened 2019-07-26 20:01 UTC
From https://bugzilla.mozilla.org/show_bug.cgi?id=1493217

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0
Build ID: 20180830143136

Steps to reproduce:

Over three months ago I asked Mozilla to change my email administratively since I no longer have access to it. Citing security considerations, for instance, I could be an imposter, I was refused. I presume that three months are enough to prove that I am who I am. Also you have a complete login history for the previous and current emails, so you can see for yourself that I'm using the same networks and I'm indeed the same person.

If that's still not enough, I can scan and upload a copy of my country passport, my international passport, my driving license and my birth certificate.

That all sounds like a humiliation because out of approximately 40 services/websites that I had to change my email for, Mozilla is the only one which doesn't allow to do that without verifying your old email.

The company behind my old email, Lycos Com, is in a shaky financial state and I cannot restore access to my old email, t.artem@mailcity.com. My new email is the one I'm filing this bug report from.

If there's any associated encrypted data linked to the old email, I'm totally OK if this information gets destroyed in a process.

I have the password my old account and I can use it without any issues, however for simplicity sake I'd like everything to be in order.

Please change my email.

**Comment by shane-tomlinson** [comment] 2019-07-29 09:58
Resolved as a duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1469785

**Closed by shane-tomlinson** 2019-07-29 09:58 UTC
