### ISSUE TITLE
[FxA-Settings] The tooltip error does not disappear after removing the field data

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#7019] opened 2020-11-27 06:30 UTC
**Build**
Stage [Train 1.194.0]

**Affected platforms**
Windows 10 64-bit
Android 9
iOS 13.6

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Click on the "Add" button from the Secondary email section.
3. Enter an email address that was already added as a secondary email by another user
4. Click on the “Save” button.
5. Erase the email address.
6. Start typing a new email address.

**Expected results**
The error tooltip disappears after the invalid data is removed.

**Actual Results**
The error tooltip persists also after typing a new value.

![issue55](https://user-images.githubusercontent.com/18114210/100418037-b4b03900-308a-11eb-82b3-f5873887b2e7.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2748)
┆Issue Number: FXA-2748

**Comment by vbudhram** [comment] 2021-01-06 15:56
I couldn't reproduce this issue in stage, closing.

**Closed by vbudhram** 2021-01-06 15:56 UTC
Labels: severity:normal
