### ISSUE TITLE
“Unknown subscription plan” error message blocks the subscription upgrade flow

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#5358] opened 2020-05-19 10:06 UTC
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.171.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Steps to reproduce
1. Go to  https://123done-stage.dev.lcip.org/ page and make a subscription.
2. Load this page https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/products/prod_GVNS86uMUO3VRM using the same browser session.
3. Check  the “authorization” box. 
4. Click the “Confirm upgrade” blue button.

#### Expected result:
- The subscription upgrade to the new plan is made with success.

#### Actual result:
- The message ”Plan update failed. Unknown subscription plan” is displayed. The upgrade is not made.

![upgrade](https://user-images.githubusercontent.com/15685960/82313648-4f8bd480-99d1-11ea-9511-ddff64890db9.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1913)
┆Issue Number: FXA-1913

**Comment by jackiemunroe** [comment] 2020-05-21 19:28
This was an issue with a typo in Stripe - the Product Metadata key was incorrect. This has been updated, and the Upgrade flow is now working in Staging. Please confirm @ValentinaPC

**Comment by data-sync-user** [comment] 2020-05-21 19:30
➤ Jackie Munroe commented:

This appears to be a caused by a typo in the Stripe Product metadata. This is now resolved in Stripe and has been confirmed via a manual test in Staging.

**Closed by data-sync-user** 2020-05-21 19:30 UTC
Labels: severity:blocker, status:bug
