### ISSUE TITLE
FxA opens a blank page from the VPN

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8176] opened 2021-04-07 18:23 UTC
Clicking the app's "Get started" button opened a URL in my Firefox, but the page was blank and never finished loading. I have two Firefox Accounts: a personal account I use for Firefox and an @mozilla.com account I created for testing VPN. Perhaps the login URL is getting confused by the two accounts?
[https://accounts.stage.mozaws.net/authorization?client_id=XXX&redirect_uri=https%3A%2F%2Fstage.guardian.nonprod.cloudops.mozgcp.net%2Foauth%2Fsuccess&scope=profile&response_type=code&state=pkce2-bd2eff9cf21c5338508fe29ff7b1e6e8e5541d74fe9575d2ad01fabaace7059be00ef7d499104aaf&access_type=offline&action=email](https://accounts.stage.mozaws.net/authorization?client_id=XXX&redirect_uri=https%3A%2F%2Fstage.guardian.nonprod.cloudops.mozgcp.net%2Foauth%2Fsuccess&scope=profile&response_type=code&state=pkce2-bd2eff9cf21c5338508fe29ff7b1e6e8e5541d74fe9575d2ad01fabaace7059be00ef7d499104aaf&access_type=offline&action=email)

Found by: cpeterson

Env = Staging, Platform = Windows

  * [rbillings] I was not able to repro this issue

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3331)
┆Issue Number: FXA-3331

**Comment by clouserw** [comment] 2021-04-07 19:22
Maybe, it's hard to say.  You can try loading https://accounts.stage.mozaws.net/clear to clear your local storage and then try doing this again and see if you can reproduce it.

**Comment by cpeterso** [comment] 2021-04-08 06:37
I re-tested and this works for me now. I think you can close this issue as it seems to have been a transitory issue.

**Comment by rbillings** [comment] 2021-04-08 17:38
I wasn't able to repro either after clearing local storage. Closing.

**Comment by rbillings** [comment] 2021-04-08 17:39
@clouserw I don't have permission to close this, so please do when you have time.

**Closed** 2021-04-08 19:15 UTC
