### ISSUE TITLE
[FxA-Settings] Sign out fails returning status code 400

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6362] opened 2020-09-02 16:23 UTC
**Build**
Stage [Train 1.186.0]

**Affected platforms**
Windows 10 64-bit
Android 9
iOS 13.6 

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Open the avatar drop-down.
3. Click on the "Sign out" button.

**Expected results**
The user is successfully logged out from Firefox Account settings page.

**Actual Results**
“Error text TBD. Response not successful: Received status code 400” error message is received. 

![Screenshot_27](https://user-images.githubusercontent.com/18114210/92009674-848a2000-ed51-11ea-96e9-07d459abd499.png)

![image](https://user-images.githubusercontent.com/18114210/92009677-8653e380-ed51-11ea-872d-52ed6d76f571.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2508)
┆Issue Number: FXA-2508
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/14208/alert-bar-console-error.png">alert-bar-console-error.png</a> | <a href="https://jira.mozilla.com/secure/attachment/14209/alert-bar-console-error-attempted-message.png">alert-bar-console-error-attempted-message.png</a> | <a href="https://jira.mozilla.com/secure/attachment/14207/alert-bar-message-attempted-error-code-location.png">alert-bar-message-attempted-error-code-location.png</a>

**Comment by LZoog** [comment] 2020-09-02 16:29
While we need to fix the console.error, I'm hoping the sign out issue will be resolved with a point release today in which we update the `fxa-graphql-api` to latest.

**Comment by data-sync-user** [comment] 2020-10-06 03:00
➤ Dave Justice commented:

The actual issue logged was fixed in the train release referred to by [~lzugai@mozilla.com] above.

As for the console error, I'm only able to reproduce in one specific state.

You must:

  * attempt to navigate to `/beta/settings` while signed out
  * create a NEW signing
  * once all of the redirects finish the error will show up once or twice depending on how long the loading spinner is up, once the page loads the alert bar component finds the `#alert-bar-root` element (which lives in `AppLayout` component) and attaches to it.

The error does not show up when:

  * logged in a navigating to `beta/settings/`
  * Signing in with an existing account, redirecting to `beta/settings`

What seems to be happening is that we attempt to show the message "Account verified Successfully" while the Loading screen is still up. This means that `<AppLayout/>` component isn't attached yet and therefore `#alert-bar-root` is not present in the dom.

The thing that is confusing to me, is where the Success message is coming from, when I grep for it in the project it's only coming up in `fxa-content-server`.

!alert-bar-message-attempted-error-code-location.png!

I haven't been able to figure out where this success message is fired, so I'm not able to fix the race condition.

Here are screenshots of the moment when the error is thrown

!alert-bar-console-error.png!

I propose we throw this into the backlog as it doesn't affect the user experience and isn't run into frequently. I have a feeling that it may go away after we finish the conversion.

**Comment by data-sync-user** [comment] 2020-10-06 19:01
➤ Dave Justice commented:

Closing this as the original issue has been addressed. Filing a new low priority issue for the console error.

**Closed by data-sync-user** 2020-10-06 19:01 UTC
Labels: severity:major

**Comment by vasilicatamas** [comment] 2020-10-29 16:32
This issue is verified as fixed on Stage [Train 1.192.0] under Windows 10 64-bit, Android 9 and iOS 13.6. The user is successfully logged out from Firefox Account settings page.

![issue24](https://user-images.githubusercontent.com/18114210/97603375-0d050400-1a15-11eb-8e1b-a41ca66345c3.gif)
