### ISSUE TITLE
"Done" button unresponsive from Secondary email section

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa#626] opened 2018-05-31 12:21 UTC
Environment: 
Platforms: Android, Win10, iOS
Sever: Stage and prod

Steps to reproduce:

1. Login with FxA account and go to manage account page;
2. Tap on "Add" from Secondary email section;
3. Type a new email and choose "Add";
4. Tap on "Done".

Expected results: tapping on "done" button closes the section.
Actual results: nothing happens, the button is unresponsive. 

Video: https://drive.google.com/open?id=1qxDOY7nYPrXm6EiK_L8a4omns3BQ4lpz

**Comment by ryanfeeley** [comment] 2019-04-04 21:42
This behaves as designed – user cannot close section until they deal with this action. If we had a badging system, perhaps we could let the user close it, but I don't think it's warranted.

**Comment by karansapolia** [comment] 2019-04-16 08:30
I had a PR #723 opened for this. I'll close it now.

**Comment by shane-tomlinson** [comment] 2019-04-16 11:14
> This behaves as designed – user cannot close section until they deal with this action. If we had a badging system, perhaps we could let the user close it, but I don't think it's warranted.

@ryanfeeley I understand the sentiment, but it's a bit of an annoying behavior and the user can just click the open button of another panel.

**Comment by ryanfeeley** [comment] 2019-04-17 02:25
@shane-tomlinson Does that close the secondary email panel? It should remain open until verified.

A better solution is doing what I proposed, which is showing a summary for each section.

* Account picture
Set / Not set
* Display name
Ryan Feeley / Not set
* Secondary email
secondary@email.com / **Verification required** / Not set
* Account recovery
Configured / Not configured
* Two-step authentication
Configured / Not configured
* Devices & apps
4 clients
* Communication preferences
Subscribed / Not subscribed
* Password
Last changed 41 days ago / Never changed
* Delete account
Created December 3, 2017

Styled like this:
![image](https://user-images.githubusercontent.com/68213/56256402-8db01980-6096-11e9-84a8-1881d89488c8.png)

What do you think?

**Comment by shane-tomlinson** [comment] 2019-04-17 05:53
> @shane-tomlinson Does that close the secondary email panel? It should remain open until verified.

I'd rather avoid this because it would require us to override default behaviors for a single panel.


> What do you think?

This is a more robust solution that avoids special cases, love it.

**Comment by ryanfeeley** [comment] 2019-04-17 14:41
@shane-tomlinson Currently @shorlander is working on a visual refresh of the page. How feasible are my examples above? I can create a new issue that could get these in with his design.

**Comment by vbudhram** [comment] 2019-04-18 13:01
> How feasible are my examples above? I can create a new issue that could get these in with his design.

@ryanfeeley sure! At a glance it seems like most of those values are exposed in the account model so maybe not too bad?

I'm going to close this issue (and linked prs) since it is working as intended.

**Closed by vbudhram** 2019-04-18 13:01 UTC
Labels: P3, fxa-content-server, help wanted, help wanted (taken)
