### ISSUE TITLE
Enable amplitude processing for payments server in stage

### ISSUE THREAD

**Issue by 6a68** [mozilla/fxa#2913] opened 2019-10-15 16:11 UTC
Once https://github.com/mozilla/fxa/pull/2734 lands, we'll want to start ingesting amplitude metrics events from the payments server, as is currently done for content server.

**Comment by 6a68** [comment] 2019-10-17 18:25
@jbuck @jrgm is this issue needed here, or should I file it against the fxa-amplitude-send repo?

**Comment by jbuck** [comment] 2019-10-17 18:36
Yeah, I'll add links to PRs where I enable this

**Comment by johngruen** [comment] 2019-10-28 16:15
@jbuck so we can close this, ya?

**Comment by jbuck** [comment] 2019-10-28 17:47
I'd like to keep this open until #3053 is on stage and confirmed working

**Comment by jbuck** [comment] 2019-10-29 16:27
#3053 didn't fix this, continuing to track in #3050

**Comment by clouserw** [comment] 2019-11-11 16:55
It looks like #3050 is closed.  Should this be closed to?  Should this be kicked to the next milestone?  Thanks

**Comment by 6a68** [comment] 2019-11-12 18:23
Hopefully payments metrics will be working on stage today, and then we can close this :+1:

**Comment by clouserw** [comment] 2019-11-15 17:10
We checked amplitude stage and saw some numbers in there so it looks like this works.  Thanks!

**Closed by clouserw** 2019-11-15 17:10 UTC

**Comment by 6a68** [comment] 2019-11-18 23:47
@jbuck Hey, is this bug good to close?
