### ISSUE TITLE
Allow users to set up 2FA/TOTP for RPs that pass acr_values=AAL2

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#589] opened 2018-10-31 14:25 UTC
Follow on from #6545.

If a user does not have TOTP enabled and the relier specifies acr_values=AAL2, the user is displayed a message that says `This request requires two step authentication enabled on your account.` but does not provide an easy way for the user to do so.

Over in https://github.com/mozilla/addons/issues/732#issuecomment-434664293, @diox has requested that we make it possible for users to do so.

ref #6661 
ref https://github.com/mozilla/fxa-auth-server/issues/2708

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-735)
┆Issue Number: FXA-735

**Comment by rfk** [comment] 2019-06-27 03:49
It's been a while since we looked at this issue, so I just wanted to summarize the current state and next steps. A simple way to reproduce the underlying issue is as follows:

* Open a private browsing window and visit this URL, which requests that the auth flow require 2FA:
  * https://accounts.firefox.com/oauth/signin?client_id=3a1f53aabe17ba32&scope=profile&state=1237&acr_values=AAL2
* Sign in with an account that does not have 2FA enabled.
* Observe that you hit a dead end with the following error message:

<img alt="dead-end screen with error message" src="https://user-images.githubusercontent.com/34695/60232895-5a350b00-98e1-11e9-8e5e-f4691737c1af.PNG" height="400" />

To proceed, the user has to open a new tab, go to their account settings, set up 2FA, then return to the original login flow and complete it.

This flow would be significantly improved if, rather than getting an error message, we took the user to a page where they can set up 2FA inline in the signin flow.  From @vbudhram's experience implementing the initial version, it sounded like this could be a fairly complex bit of state management. It also depends on some UX input for details, although starting from the existing 2FA setup screen seems like a fine approach.

**Comment by ryanfeeley** [comment] 2019-08-08 17:02
Could the user instead be redirected to account settings, with a message (modal or red bar) that says:
* Accessing {replying party} requires you to have **Two Step Authentication** enabled on your account.

**Comment by rfk** [comment] 2019-08-08 22:17
> Could the user instead be redirected to account settings

This sounds similar to what we do right now (although we don't direct them straight to the settings page, we provide a "more information" link that they can follow to get to the settings page).

The desired experience here is to set up 2fa "inline" in the login flow, so that when the user is done they can easily continue with signing in to the requesting RP. It would be great to re-use the settings page for this, but it's not clear to me how we then direct the user back to their login flow.

**Comment by shane-tomlinson** [comment] 2019-09-05 13:09
> It would be great to re-use the settings page for this

I would be fearful that the user would get totally lost within the settings page by clicking around on other things.

**Comment by ryanfeeley** [comment] 2019-09-09 17:09
> I would be fearful that the user would get totally lost within the settings page by clicking around on other things.

Normal users yes, but not extension developers.

**Comment by shane-tomlinson** [comment] 2019-09-10 09:39
> Normal users yes, but not extension developers.

I'm not buying this assertion, and am very weary of adding special case logic within the settings page to redirect back to AMO.

**Comment by data-sync-user** [comment] 2020-04-23 17:24
➤ Jared Hirsch commented:

The separate issue for extracting the 2FA setup flow into mixins was an artificial distinction: I had to put the flow together to understand how to extract the code. Converted FXA-308 to a subtask of this issue. Reducing points for this issue down to 3 to reflect work remaining.

**Comment by data-sync-user** [comment] 2020-04-23 17:39
➤ Jared Hirsch commented:

This issue is really old and doesn't make it clear what work's left for this epic.

Closing in favor of https://jira.mozilla.com/browse/FXA-1750.

**Closed by data-sync-user** 2020-04-23 17:39 UTC
Labels: fxa-content-server
