### ISSUE TITLE
E-mail first flow - mobile autofocuses on first password input

### ISSUE THREAD

**Issue by LZoog** [mozilla/fxa#3040] opened 2019-10-21 15:49 UTC
Expected behavior is that autofocus is present on desktop but _not_ mobile.

We've had a lot of issues open around this. See #3025 for a quick fix we got in to add autofocus to desktop that also added focus to mobile.

**Comment by shane-tomlinson** [comment] 2019-10-21 15:52
The autofocus attribute is programatically focused using this code: https://github.com/mozilla/fxa/blob/74f6f333c5d687a4b740238f53c8b119553f0037/packages/fxa-content-server/app/scripts/views/base.js#L954. It is supposed to know enough to not autofocus on mobile because the virtual keyboard pops up and obscures part of the screen. Is that broken?

**Comment by davismtl** [comment] 2019-10-21 16:56
We observe a clear 1.5% absolute drop in form submits on mobile as a likely result of this.

https://analytics.amplitude.com/mozilla-corp/chart/67f16ti/edit/o1masab

**Comment by davismtl** [comment] 2019-10-21 18:58
That chart is inaccurate since it included Android. IIUC, the problem is only on iOS. And if that is the case then the bug had a positive impact:
https://analytics.amplitude.com/mozilla-corp/chart/67f16ti/edit/ptkzryf

Did we accidentally learn something?

**Comment by shane-tomlinson** [comment] 2019-10-21 21:47
> Did we accidentally learn something?

That we should enable autocomplete on Android too?

**Comment by davismtl** [comment] 2019-10-22 14:53
I guess so. 🤔

I filed this one:
https://github.com/mozilla/fxa/issues/3066

**Comment by shane-tomlinson** [comment] 2019-10-23 07:00
> I guess so. 🤔 I filed this one: #3066

I'm going to close this issue since we decided we *want* autofocus on android too!

**Closed by shane-tomlinson** 2019-10-23 07:00 UTC
Labels: P2
