### ISSUE TITLE
2FA screen UI issue

### ISSUE THREAD

**Issue by birdsarah** [mozilla/fxa#8306] opened 2021-04-15 20:57 UTC
## Description

After enabling 2FA, the buttons on the recovery codes screen are all on top of each other

![Screenshot from 2021-04-15 15-53-27](https://user-images.githubusercontent.com/1796208/114937073-edb33500-9e02-11eb-9704-60c83f0c2f38.png)
![Screenshot from 2021-04-15 15-53-17](https://user-images.githubusercontent.com/1796208/114937087-f1df5280-9e02-11eb-91a8-02d370c56b45.png)

(note i've cropped out the middle with my actual recovery codes in it)

### Steps to reproduce

- Perform process to enable 2FA
- see screenshots above

### Expected result

Clearer UI, buttons not overlapping

### Actual result

See screenshots above

### Environment

Linux, Firefox 87.0

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3383)
┆Issue Number: FXA-3383

**Comment by dholbert** [comment] 2021-04-18 20:44
Looks like the CSS is setting a fixed height on the container that holds the recovery codes and the download/copy/print buttons:
CSS:
```css
.h-40 {
  height: 10rem;
}

```
HTML:
```html
<div class="mt-6 flex flex-col items-center h-40 justify-between">
  [...container for recovery codes is here...]
  [...container for download/copy/print is here...]
</div>
<div class="flex justify-center mt-6 mb-4 mx-auto max-w-64">
  <button type="button" class="cta-neutral mx-2 px-10" data-testid="close-modal">Close</button>
</div>
```

The recovery codes themselves are about 10rem tall, so they entirely fill their container's fixed-height, and the download/copy/print icons are pushed beyond that container's bounds and stomp on top of the content that follows (which in this case is the close button).

**Comment by dholbert** [comment] 2021-04-18 20:50
Looks like @chenba has git-blame on the recovery-codes HTML here (including the `h-40` class which is what's imposing the problematic fixed height here).  @chenba, maybe you could take a look here?

(Can we just remove the `h-40` class from this element?)

**Comment by chenba** [comment] 2021-04-18 23:28
This is a duplicate of #7126

**Closed** 2021-04-20 16:09 UTC
