### ISSUE TITLE
Unhelpful error when trying to upload an account avatar image that is too large [bz1632246]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#5962] opened 2020-07-16 15:00 UTC
From https://bugzilla.mozilla.org/show_bug.cgi?id=1632246

## Steps to reproduce

When trying to upload a new account avatar image for my account, I kept getting an error message:  "Service Unavailable, try again later".

After some time and guesswork, I figured out that the image was just too large and after resizing it, it worked just fine.

## Expected behavior

I expected the site to indicate the issue was with the file size and not look like a 5xx error or something.

Bonus:  It would be _really_ nice to know that there are restrictions to the image size on the upload page.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2296)
┆Issue Number: FXA-2296

**Comment by data-sync-user** [comment] 2020-07-16 15:29
➤ Jody Heavener commented:

Closed as dupe of FXA-1767, which was fixed this week.

**Closed** 2020-07-16 15:29 UTC
