### ISSUE TITLE
Inconsistency in the way we show error messages when creating a new subscription

### ISSUE THREAD

**Issue by madalincm** [mozilla/fxa#4748] opened 2020-04-03 09:21 UTC
#### Affected versions:
- All Firefox, chrome

#### Affected Platforms:
Android 9, Win10

#### Preconditions
- existent FxA account with no subscriptions

#### Steps to reproduce
1. Open the [stage website](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn)
2. Click on the Subscribe now button
3. Use a credit card number that should return an expired credit card error and use a credit card number that should return an invalid cvc number.

#### Expected result:
-  All errors are displayed in the same way.

#### Actual result:
- The error for expired credit card is displayed in a modal:
![image](https://user-images.githubusercontent.com/15685441/78344693-6901ca00-75a5-11ea-8f65-66f90cd427a3.png)
- The error for invalid cvc number is not displayed in a modal:
![image](https://user-images.githubusercontent.com/15685441/78344795-8f276a00-75a5-11ea-8501-2d487ee3fb0e.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1486)
┆Issue Number: FXA-1486

**Comment by data-sync-user** [comment] 2020-04-07 20:23
➤ Wil Clouser commented:

It looks like this is a duplicate of https://jira.mozilla.com/browse/FXA-1119 which got closed one day before this one.  Is this still the case or was this fixed?  To be clear: all errors should be in the red box now.

**Comment by madalincm** [comment] 2020-04-08 07:13
In the create subscription flow there are some errors that are being displayed in a modal:
Payment processing error (4000-0000-0000-0119):
![image](https://user-images.githubusercontent.com/15685441/78754494-3af30000-7980-11ea-8b5e-19a9ee6410f9.png)

Expired card (4000-0000-0000-0069): 
![image](https://user-images.githubusercontent.com/15685441/78754323-f5363780-797f-11ea-831c-6db3d763b6fb.png)

For the update billing info flow the issue is not reproducing.  All the errors are displayed in the red box now.

**Closed** 2020-04-16 15:42 UTC
Labels: severity:minor, status:bug
