### ISSUE TITLE
[FXA-Settings] Time stamp needs time zone info

### ISSUE THREAD

**Issue by janiceahn** [mozilla/fxa#7761] opened 2021-03-09 17:48 UTC
## Description

In the comps, password change includes date but not time.
Staging includes the time.

If we are definitely keeping time, then we need to add the time zone information.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/6219141/110514776-a59f4500-80d5-11eb-9c9f-069ad38be106.png)

### Expected result

Add time zone information.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3152)
┆Issue Number: FXA-3152

**Comment by data-sync-user** [comment] 2021-03-16 16:17
➤ Wil Clouser commented:

Let's remove the time and only show the date.

**Comment by Yogita98** [comment] 2021-03-16 18:09
I'm quite confused on how do I reproduce this issue. @janiceahn Can you please explain me the detailed steps of reproducing this issue?

**Comment by janiceahn** [comment] 2021-03-16 18:27
@Yogita98 I believe that you can reproduce this by resetting your password — the date and time should then both appear.

**Comment by Yogita98** [comment] 2021-03-16 18:50
You have mentioned in the issue:
> In the comps, password change includes date but not time.
> Staging includes the time.
Do I need to navigate to any route because when I'm changing the password via forgot password on the sign in screen or by selecting change password on the http://localhost:3030/settings I'm redirected again to http://localhost:3030/settings which doesn't indicate the time or date of password creation

**Comment by jodyheavener** [comment] 2021-03-16 19:14
@Yogita98 there have been some recent changes to paths as FXA rolls out a new Settings UI. Can you make sure you've pulled in the latest changes from `main`? I think if everything is set up properly accessing the address above _should_ redirect you to `/beta/settings`.

**Comment by Yogita98** [comment] 2021-03-18 14:37
Yes correct I was working with the old version. I have pulled in new changes from `main` and will get started on this. Thanks @jodyheavener

**Comment by LZoog** [comment] 2021-03-26 19:28
This was closed in #7914

**Closed by LZoog** 2021-03-26 19:28 UTC
Labels: good first issue, help wanted, skill:js

**Comment by data-sync-user** [comment] 2021-03-31 07:05
➤ Bianca Oltean commented:

This issue was verified as Fixed on Stage [Train 1.203.2] under Windows 10 and Android 11. The time is removed and only the password creation date is displayed.
