### ISSUE TITLE
Firefox account "sms" post-signin-page has missing space between "Why sign in on another device?Not now" [bz1615041]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#4115] opened 2020-02-12 20:00 UTC
From https://bugzilla.mozilla.org/show_bug.cgi?id=1615041

Created attachment 9126198
image.png

STR:
1. Be signed into your Firefox account.
2. Visit https://accounts.firefox.com/sms
(Note that I was automatically directed there after logging in to my Firefox account today - I didn't seek out that /sms page specifically on my own)

ACTUAL RESULTS:
The bottom of the page says:
`Why sign in on another device?Not now`

EXPECTED RESULTS:
White space (or a linebreak) between the "?" and "Not now"

Screenshot attached.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1078)
┆Issue Number: FXA-1078

**Comment by vasilicatamas** [comment] 2020-02-13 09:55
Closing as dupe of #3820

**Closed by vasilicatamas** 2020-02-13 09:55 UTC
