### ISSUE TITLE
[foxfooding] QR code on Firefox Accounts "Download Firefox on your phone or tablet" has an invalid link

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#14058] opened 2022-09-02 19:07 UTC
**Firefox Version:** Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0
**Window Size (inner width and height):** 1638x1127
**GitHub Username:** @Vinnl
## Steps to Reproduce
1) Enabled sync and created a new Firefox account on Nightly.
2) On the last screen, it showed a QR code to download Firefox to my phone.
3) I scanned the QR code with my phone.

## Expected Behavior
I get taken to a page where I can download Firefox Nightly for my phone.

## Actual Behavior
The QR code resolves to https://mzl.la/3NDxAIS. Following that link I get redirected to https://app.adjust.com/r991ba8?campaign=firefox-desktop&adgroup=firefoxview&creative=FIDE-718. Before landing there, uBlock Origin tells me it has prevented that page from loading - I temporarily disable strict blocking for app.adjust.com.

I then get a screen that says the certificate is invalid (IIRC). Tapping "Accept the risk and continue", I get to a plain 404 Not Found page.

## Attachment
![Attachment](https://mk-mozilla-campaign-form.s3.eu-central-1.amazonaws.com/96e8e30d-c396-4246-8bd3-d7c8ac9600a3.png)
[Link to the original attachment](https://mk-mozilla-campaign-form.s3.eu-central-1.amazonaws.com/96e8e30d-c396-4246-8bd3-d7c8ac9600a3.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5867)

**Comment by clouserw** [comment] 2024-04-08 19:08
Thanks for filing but I can't reproduce this.  Obviously blocking something with uBlock is on your local machine, but loading that end URL is not a 404 for me, so, I'm going to close this.  Thanks.

**Closed by clouserw** 2024-04-08 19:08 UTC
